### ISSUE TITLE
cc_toolchain configured to link with "-pie" will fail the build of proc_macro crates

### ISSUE THREAD

**Issue by ikalchev** [bazelbuild/rules_rust#1005]
If the `cc_toolchain` has been configured to compile with `-fPIC` and link with `-pie`, compiling a `proc_macro` crate will fail with `undefined reference to main`. This is explained in depth [here](https://github.com/xd009642/tarpaulin/issues/23#issuecomment-329067018). In short, `proc_macro`s are always produced as dynamic libraries (since they need to be loaded by the rust compiler at build time), but adding `-pie` to the linker confuses it to try to produce an executable.

FWIW, adding `--codegen=link-args=-shared` _at the end_ of the `rustc` command fixes the issue, but it's a messy hack to have.

PR with a small fix coming soon.

**Comment by dfreese** [comment]
I had run into similar with #578. I started to discuss some potential solutions there.

**Comment by ikalchev** [comment]
Hey thanks for sharing. Let's continue there then.
