### ISSUE TITLE
pre-release dependency ignored by crate_universe in member_packages_version_mapping

### ISSUE THREAD

**Issue by shikhar** [bazelbuild/rules_rust#1018]
The dependency in question from `Cargo.toml`:
```
tantivy = { git = "https://github.com/quickwit-inc/tantivy", rev="72cef12db1697a230a0e51170d9801af410f529b", default-features = false }
```

The version in there is `0.17.0-dev`. In diffing the `crate_universe` lockfile vs before when the dependency was a non-pre-release version `0.16.1`, I see it is being removed altogether from the `member_packages_version_mapping` section.

The build fails for the package where this dependency is required, but it succeeds if I add a mapping manually as `0.17.0`.

**Comment by illicitonion** [comment]
Thanks for the report - this is an interesting edge-case of semver! https://github.com/bazelbuild/rules_rust/pull/1028 should fix it up :)
