### ISSUE TITLE
Way to configure `target-cpu`?

### ISSUE THREAD

**Issue by SUPERCILEX** [bazelbuild/rules_rust#1023]
It would be nice to have a mechanism that configures global flags for all dependencies. Is this possible? I'd like to be able to specify `rustflags = ["-C", "target-cpu=native"]` for all dependencies.

**Comment by UebelAndre** [comment]
is [--@rules_rust//:extra_rustc_flags](https://bazelbuild.github.io/rules_rust/flatten.html#extra_rustc_flags) what you're looking for?

**Comment by SUPERCILEX** [comment]
Yes, thank you!
