### ISSUE TITLE
Is the main branch currently compatible with cargo-raze?

### ISSUE THREAD

**Issue by dae** [bazelbuild/rules_rust#1026]
I haven't seen anyone else mention issues with it, and it makes me wonder whether I've just overlooked something.

https://github.com/bazelbuild/rules_rust/issues/591#issuecomment-968194751

**Comment by dfreese** [comment]
It is. rust_library still exists, but only produces rlib artifacts.

**Comment by yagehu** [comment]
I don't think it is. `main` doesn't have `/rust/rust.bzl` while cargo-raze v0.13 tries to load it. I got this:

```
error loading package '@cargo_raze//impl': cannot load '@rules_rust//rust:rust.bzl': no such file and referenced by '@cargo_raze//tools:raze'
```

b3e26e0c6e02bebd954135f2ce4dd578fc6d94c0 works for me btw.

**Comment by dae** [comment]
Sorry for the noise, this did end up being user error on my part. We override a few raze-generated BUILD files with hand-edited versions, and it was one of those that was breaking our build.
