### ISSUE TITLE
Clippy aspect prevents customization of lints for bindgen targets

### ISSUE THREAD

**Issue by csmulhern** [bazelbuild/rules_rust#1048]
The Clippy aspect attempts to prevent some errors in bindgen targets by limiting the lints that are denied. See:
https://github.com/bazelbuild/rules_rust/blob/dc66c1612b7a3e96531eff22136570124c8eec81/rust/private/clippy.bzl#L129

However, because these clippy flags are being appended to the rustc flags, clippy lint customizations in the rustc flags (e.g. ["-A," "clippy::assertions_on_constants"]) will be overridden.

**Comment by csmulhern** [comment]
A simple fix that would not regress anything would be to not have this enforcement for __bindgen crates. I like the idea of doing this regardless, because assuming what subset of flags is appropriate doesn't really seem right, and is broken for e.g. harfbuzz (which has tabs characters in comments which are turned into rust doc comments, violating a clippy lint).

In other words, replace the if / else block with:
```python
# bindgen-generated content is likely to trigger warnings, so
# clippy is not enabled for these targets
if "__bindgen" not in ctx.rule.attr.tags:
    # fail on any warning
    args.rustc_flags.add("-Dwarnings")
```

In addition, we should probably be passing any additional rustc_flags to construct_arguments's rust_flags parameter:
https://github.com/bazelbuild/rules_rust/blob/ded0e56fb2cfab35ec31e2e1d20f554c275297f0/rust/private/clippy.bzl#L89-L106

As these flags are prepended before those that come from build rules:
https://github.com/bazelbuild/rules_rust/blob/87b74a1d72612e90441fd75a364a6e61bcf80ca6/rust/private/rustc.bzl#L601-L611

**Comment by UebelAndre** [comment]
Does it even make sense to run `clippy` on bindgen targets? Aren't those generated files and the defects are more-or-less out of users control?

**Comment by csmulhern** [comment]
I guess that's no longer true since the addition of clippy_flags in #1264.
