### ISSUE TITLE
How to get the most recent .tar.gz from http_archive?

### ISSUE THREAD

**Issue by peter-kehl** [bazelbuild/rules_rust#1059]
Thank you for `rules_rust`.

https://bazelbuild.github.io/rules_rust says that "the lastest commit on the main branch should be used." However, how to get the URL and sha256? `https://github.com/bazelbuild/rules_rust/archive/` is not browsable.

```
urls = [
        # `main` branch as of 2021-08-23
        "https://github.com/bazelbuild/rules_rust/archive/d8238877c0e552639d3e057aadd6bfcf37592408.tar.gz",
    ],
```

**Comment by ddeville** [comment]
You can get the list of commits from https://github.com/bazelbuild/rules_rust/commits/main and pick the latest, for example https://github.com/bazelbuild/rules_rust/commit/23a4631cad819003642b1a148e458fe4ed2c54e1

Then just s/commit/archive and append .tar.gz, https://github.com/bazelbuild/rules_rust/archive/23a4631cad819003642b1a148e458fe4ed2c54e1.tar.gz.

To get the sha256 sum you can use `shasum` on the command line, something like `curl -L https://github.com/bazelbuild/rules_rust/archive/23a4631cad819003642b1a148e458fe4ed2c54e1.tar.gz | shasum -a 256`

**Comment by UebelAndre** [comment]
We've started doing releases and for each release we provide an `http_archive` snippet for getting the rules:
https://github.com/bazelbuild/rules_rust/releases/tag/0.1.0

This in addition to https://github.com/bazelbuild/rules_rust/issues/1059#issuecomment-990067237 (thanks btw for the assist!) should allow you to get any version of the rules you want Gonna close this out but please reopen if there's something I missed.
