### ISSUE TITLE
Strange interaction of `$(location )` expansion, repo's build rules, and `rust_test`

### ISSUE THREAD

**Issue by jon-chuang** [bazelbuild/rules_rust#1084]
My `rust_test` looks like the following:
```python
rust_test(
    name = "test",
    srcs = ["src/test.rs"],
    deps = [
      ":ray_rs_sys",
      ":ray_rs_sys_shared",
      "@cxx.rs//:cxx",
    ] + crates_from("//rust/ray-rs-sys:Cargo.toml"),
    env = {
      "RUST_TEST_NOCAPTURE": "1",
      "RAY_RUST_LIBRARY_PATHS": "--ray_code_search_path=$(location ray_rs_sys_shared)"
    },
)
```

However, `$(location ray_rs_sys_shared)` expands to 
```
/home/jonch/.cache/bazel/_bazel_jonch/3819ce4da5bb63a59f7ecd1a722a08d9/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/rust/ray-rs-sys/test.launcher.runfiles/com_github_ray_project_ray/bazel-out/k8-opt/bin/rust/ray-rs-sys/libray_rs_sys-1398298517.so
```
Where the directory `bazel-out` doesn't exist in
```
/home/jonch/.cache/bazel/_bazel_jonch/3819ce4da5bb63a59f7ecd1a722a08d9/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/rust/ray-rs-sys/test.launcher.runfiles/com_github_ray_project_ray
```
Instead of passing in this non-existent symlinked dir (?), things work fine if I substitute the build artifact from the execroot project dir directly, e.g.
```
/home/jonch/.cache/bazel/_bazel_jonch/3819ce4da5bb63a59f7ecd1a722a08d9/execroot/com_github_ray_project_ray/bazel-out/k8-opt/bin/rust/ray-rs-sys/libray_rs_sys-1398298517.so
```
Which implies that there is something wrong with the symlinking and `test.launcher.runfiles` dir generation.

**Comment by jon-chuang** [comment]
Now that I've analyzed the problem, it seems trivial - try to determine how to get the rules_rust code to symlink in the `bazel-out` dir in the `test.runfiles` dir

**Comment by jon-chuang** [comment]
Related issue: https://github.com/bazelbuild/rules_rust/pull/588/files
@UebelAndre @illicitonion could you guys advise?

**Comment by jon-chuang** [comment]
Ok, I've fixed by changing my build rule to be:
```
rust_test(
    name = "test",
    srcs = ["src/test.rs"],
    deps = [
      ":ray_rs_sys",
      "@cxx.rs//:cxx",
    ] + crates_from("//rust/ray-rs-sys:Cargo.toml"),
    data = [":ray_rs_sys_shared"],
    env = {
      "RUST_TEST_NOCAPTURE": "1",
      "RAY_RUST_LIBRARY_PATHS": "--ray_code_search_path=$(rootpath ray_rs_sys_shared)"
    },
)
```

So I had to put the dependency in `data` rather than `deps` and use `rootpath` rather than `execpath` or `location`. No other config I've tested works.

I'm not sure if this is expected behaviour but I'm glad I managed to fix.

**Comment by illicitonion** [comment]
I'm glad you got things working! From the sounds of thing, a `data` dep is correct vs a `dep` (`data` is for "files I may read a runtime" whereas `deps` is intended to be a compile-time concept).

As for which of `execpath`, `rootpath`, and `location`: Looking at the code, I think `execpath` is realistically something we probably can't support, as by the time our test wrapper is invoked we can't recover what the exec-root actually was, so we can't expand it properly. It looks like we're currently expanding it to a nonsense value, and we should probably guard against that. For a test, I think `rootpath` is the correct thing to be using. We should maybe better document this on `rust_test` itself, and error if you try to use something we can't support :)

**Comment by jon-chuang** [comment]
Ok, thank you! I guess `$execpath` and `$rootpath` are preferred over `$location`.

I think the behaviour that execpath gives a nonsense output is indeed something to guard against. 

It's actually a miracle that rootpath still worked in my case, I suppose :)

**Comment by UebelAndre** [comment]
@jon-chuang does that mean your issue is resolved?

**Comment by jon-chuang** [comment]
yep, thanks!
