### ISSUE TITLE
Confusion on the use of 'extra_target_triples' in `rust_repository_set`

### ISSUE THREAD

**Issue by photex** [bazelbuild/rules_rust#109]
Howdy!

I'm not sure if this is related to #101 or not but I had expected this to work: 
```
rust_repository_set(
    name = "rust_linux_x86_64",
    exec_triple = "x86_64-unknown-linux-gnu",
    extra_target_triples = [
        "aarch64-unknown-linux-gnu"
    ],
    version = "1.27.2",
)
```

The error I get: 
```
ERROR: /home/kopernikus/.cache/bazel/_bazel_kopernikus/3b8e07831dccba8888e630aef5b461f7/external/rust_linux_x86_64_toolchains/BUILD:11:1: no such target '@bazel_tools//platforms:aarch64': target 'aarch64' not declared in package 'platforms' defined by /home/kopernikus/.cache/bazel/_bazel_kopernikus/3b8e07831dccba8888e630aef5b461f7/external/bazel_tools/platforms/BUILD and referenced by '@rust_linux_x86_64_toolchains//:toolchain_for_aarch64-unknown-linux-gnu'
ERROR: While resolving toolchains for target //components/services/kpns-bus/rust:kpns-bus: invalid registered toolchain '@rust_linux_x86_64_toolchains//:toolchain_for_aarch64-unknown-linux-gnu': Analysis failed
ERROR: Analysis of target '//components/services/kpns-bus/rust:kpns-bus' failed; build aborted: invalid registered toolchain '@rust_linux_x86_64_toolchains//:toolchain_for_aarch64-unknown-linux-gnu': Analysis failed
INFO: Elapsed time: 0.751s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded)
```

What "extra_target_triples" seemed to be was the ability to have this pull down appropriate versions of the stdlib for alternate targets in the style of `rustup target add aarch64-unknown-linux-gnu`.

**Comment by acmcarther** [comment]
Two parts:

**First, regd:**
```
target 'aarch64' not declared in package 'platforms'
```
This is a normal bug that I need to fix. Will investigate soon

**Second, more generally around the cross compilation story:**

This is a very new feature that isn't completely implemented and I apologize for the confusion. Currently the `extra_target_triples` field downloads the requisite stdlibs for those alternative targets, but it doesn't configure the additional host-to-target toolchains, or expose a way for you to provide the cross-linker that you'll need.

I'll keep this bug issue update with the implementation progress.

**Comment by photex** [comment]
No need to apologize. Thanks for explaining. Please let me know if I can be of any assistance.

**Comment by photex** [comment]
Howdy again!

So after having added my aarch64 toolchain I no longer get this error. I still have to mess around with this now and attempt to get cross-compilation working.

**Comment by Noia** [comment]
Any update on this? I am trying to compile some rust for a Raspberry Pi and I'm running into similar issues:

```
rust_repository_set(
    name = "rust_linux_arm",
    exec_triple = "arm-unknown-linux-gnueabihf",
    extra_target_triples = [
    ],
    version = RUST_VERSION,
)
```
```
$ blaze query '"@rust_linux_arm//..."'
INFO: Invocation ID: d7ed739f-ba95-4f9c-b258-c457105cd215
@rust_linux_arm//:toolchain_for_arm-unknown-linux-gnueabihf_impl
@rust_linux_arm//:rustdoc
@rust_linux_arm//:rustc_lib
@rust_linux_arm//:rustc
@rust_linux_arm//:rust_lib-arm-unknown-linux-gnueabihf

```
None of these targets appear to export a PlatformInfo, when I try to use @rust_linux_arm//:toolchain_for_arm-unknown-linux-gnueabihf_impl I get a different error however.

```
$ blaze build --platforms=@rust_linux_arm//:toolchain_for_arm-unknown-linux-gnueabihf_impl //04:hello --sandbox_debug 
INFO: Invocation ID: 734f9c77-2714-46ca-b4a2-eba88b61f35e
ERROR: /home/emis/.cache/bazel/_bazel_emis/e492159d29688c624934eedb7f1a4c0b/external/rust_linux_arm/BUILD:36:1: in rust_toolchain rule @rust_linux_arm//:toolchain_for_arm-unknown-linux-gnueabihf_impl: cycle in dependency graph:
    //04:hello
.-> @rust_linux_arm//:toolchain_for_arm-unknown-linux-gnueabihf_impl [self-edge]
`--
This cycle occurred because of a configuration option
ERROR: Analysis of target '//04:hello' failed; build aborted
INFO: Elapsed time: 0.039s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
```
Am I missing something? How am I supposed to invoke this? I get basically the same error when using --extra_toolchains. Could you post an example of how you expect this to be done?

**Comment by acmcarther** [comment]
I don't have an update on this feature. The cross compilation functionality itself is still soft-blocked on adding a toolchain configuration option for specifying a per target crosslinker[*], though if you're willing to wait long enough that problem will eliminate itself when lld becomes the default linker (which ostensibly can crosslink to any supported target).

Crosslink-aside, I don't understand the circular dependency you're seeing there. I can't promise that it'll be enlightening, but can you add the result of:

```
$ blaze query --output=build //04:hello
```

---

[*] This isn't actually "hard" to do, its just something I was supposed to do and haven't done. Don't worry, [this isn't the only feature I've been neglecting](https://github.com/google/cargo-raze/issues/79).

**Comment by Noia** [comment]
That's just the hello world I'm compiling, noting exciting in there:

```
$ blaze query --output=build //04:hello
INFO: Invocation ID: 138cd105-fff1-4ce5-bbbc-63c1e50fcf50
# /home/emis/Documents/git/stuff/04/BUILD:20:1
rust_binary(
  name = "hello",
  srcs = ["//04:hello.rs"],
)
```

**Comment by mfarrugi** [comment]
The couple of blog posts on the topic make it look like cargo passes https://github.com/bazelbuild/rules_rust/blob/23ab9d5ed7e78ed3c9fd2cf7627eaa6ea60742bf/rust/private/rustc.bzl#L224 to the cross-linker.. other than that I would prod cargo to see what command lines it produces.

@acmcarther can you qualify "not hard to do" with an outline of what needs to be done? Is lld usable, or should we do something else?

**Comment by m3rcuriel** [comment]
I've had success currently setting up the cross-linker using typical Bazel cc toolchain setup, so I'm not sure it needs to be exposed through rules_rust specifically since it's arguably a cc link step, or more fairly it's on the onus of upstream (or more rules?) to set up some "LLVM" link step since even in our case it isn't a "rust specific" link since the cc deps would be linked in at that point.

**Comment by TheAifam5** [comment]
I've encounter similar problem when setting `extra_target_triples` as `x86_64-unknown-uefi`. Any workaround available?
