### ISSUE TITLE
Runfiles Tests are failing on remote execution

### ISSUE THREAD

**Issue by xingao267** [bazelbuild/rules_rust#112]
A lot of tests are failing on RBE when I tested with https://github.com/bazelbuild/rules_rust/pull/111 where I added the Buildkite config to test against RBE. You can find the set of tests that are failing in the PR (https://github.com/bazelbuild/rules_rust/pull/111/files) where I have to skip them.

We previously tested rules_rust repo at commit ef77316503f1ad88c348d9cbc03bf60dbad49317 internally and this set of test targets pass on RBE:

-- @examples//... -@examples//hello_runfiles:hello_runfiles_test

It's likely there is some regression between ef77316503f1ad88c348d9cbc03bf60dbad49317 and 1944c8a9c104fb73e3058a86204373df63b79eca

**Comment by acmcarther** [comment]
I missed this codegen-backends directory when I changed the toolchain fetching logic.

I'm putting together a fix now in https://github.com/bazelbuild/rules_rust/compare/acm-fix-remote-exec.

**Comment by mfarrugi** [comment]
#122 skipped the (newly added / fixed) doc tests as well, I don't have any visibility into the test failures though.

**Comment by xingao267** [comment]
@mfarrugi Can you access test links like https://source.cloud.google.com/results/invocations/4b0d4425-d14f-4baa-b248-f36463b9d08b/targets?

**Comment by mfarrugi** [comment]
Yes, those links are visible
