### ISSUE TITLE
gen_rust_project should use absolute paths for modules whose root is a generated file

### ISSUE THREAD

**Issue by csmulhern** [bazelbuild/rules_rust#1121]
For example, when creating a rust library that wraps bindgen generated source, the following JSON entry is created for gen_rust_project.

```
{
    "display_name": "png_sys",
    "root_module": "bazel-out/darwin-fastbuild/bin/png_sys/png_sys__bindgen.rs",
    "edition": "2021",
    "deps": [],
    "is_workspace_member": true,
    "cfg": [
        "test",
        "debug_assertions"
    ],
    "target": "x86_64-apple-darwin",
    "env": {},
    "is_proc_macro": false
}
```

The relative path for root_module causes rust_analyzer to be unable to find the right file when not using convenience symlinks (i.e. when `--experimental_convenience_symlinks=ignore` is set). This would be fixed by using an absolute path instead.

**Comment by UebelAndre** [comment]
Sorry for the delay here. @csmulhern could we trouble you for a pull request? I'd be happy to collaborate on it with you (or anyone else interested in picking up this work)
