### ISSUE TITLE
Printing output from bazel_test rules

### ISSUE THREAD

**Issue by husafan** [bazelbuild/rules_rust#1149]
Hi all,

I am having trouble getting unconditional output from `bazel_test` rules. For example, if I have a `println!` in my test code, and the test passes, I will not see the `println!` output. If the test fails, I do see the `println!` output.

I have tried setting `RUST_TEST_NOCAPTURE` to `1` in the rustc_flags and it does not change the behavior. What is the right way to use the console when debugging tests?

Thank you for your time and help.

**Comment by dae** [comment]
If you mean rust_rest, use `bazel run //path:tests -- --nocapture`

**Comment by husafan** [comment]
That's exactly what I was looking for! Thank you so much for the quick response.
