### ISSUE TITLE
CARGO_MANIFEST_DIR points to a non-existing directory in cargo_build_script() on Windows

### ISSUE THREAD

**Issue by korDen** [bazelbuild/rules_rust#1155]
On Windows, when I declare a cargo_build_script(), CARGO_MANIFEST_DIR is set to something like bazel-out/x64_windows-opt-exec-2B5CBBC6/bin/workspace_name/build_script_.exe.runfiles/workspace_name/package_name

That directory, however, is not created.

bazel-out/x64_windows-opt-exec-2B5CBBC6/bin/workspace_name/build_script_.exe.runfiles - exists, containing MANIFEST file and nothing else. No child directories.

This causes cargo_build_script() to fail since we are trying to use CARGO_MANIFEST_DIR as the current directory and fail. Also, manifest isn't there anyway.

I tried adding some data dependencies to random files to force creating the directory, but it didn't seem to have any effect.

SInce my build script is bare-bones, here is the definition:

cargo_build_script(
    name = "build_script",
    srcs = ["build.rs"],
)

**Comment by UebelAndre** [comment]
Have you tried enabling [--enable_runfiles](https://bazel.build/reference/command-line-reference#flag--enable_runfiles) and [--windows_enable_symlinks](https://bazel.build/reference/command-line-reference#flag--windows_enable_symlinks)?

**Comment by korDen** [comment]
[--enable_runfiles](https://bazel.build/reference/command-line-reference#flag--enable_runfiles) fixed it, thanks!

**Comment by UebelAndre** [comment]
Glad it's working for you! If you run into any more issues, let is know what rule is causing you issues on https://github.com/bazelbuild/rules_rust/issues/1156.
