### ISSUE TITLE
add rule for cbindgen

### ISSUE THREAD

**Issue by mfarrugi** [bazelbuild/rules_rust#116]
This would look something like https://github.com/mfarrugi/rules_rust/blob/c-bind-gen/rust/cbindgen.bzl

Main issue here is that this wants `cargo metadata` to work under bazel, which essentially requires Cargo.toml`s to be available at build time, similar to #71 and #95.

I am not actually familiar with the tool, so I am not sure if there are additional corner cases that make this less straight forward; potentially there are issues with generating sensible Cargo.toml's that cbindgen will be happy with.

**Comment by mfarrugi** [comment]
cc @photex

**Comment by damienmg** [comment]
Deduping this one in favor of #381 which has more information and is more up to date.
