### ISSUE TITLE
`crates_repository`: The `default_features` field in `crate.spec` doesn't seem to work

### ISSUE THREAD

**Issue by SlyMarbo** [bazelbuild/rules_rust#1168]
Hi there. I'm currently updating from `crate_universe` to the new `crates_repository` functionality introduced in #1158. The introduction of support for `default_features = False` is exciting, as I'm building a lot of `#![no_std]` code, so I often need to disable the default features to turn off the `std` feature.

However, setting `default_features = False` in a `crate.spec` doesn't seem to have any effect. I've had a quick look through the code and `crate.spec` propagates the field to the JSON it produces, but I can't find anything pulling it out of the JSON and crates still seem to be using their default features. Have I missed something? Thanks for your help.

**Comment by SlyMarbo** [comment]
I should add that with `crate_universe`, I worked around the inability to disable default features by using `crate.override`'s `features_to_remove` field. There doesn't seem to be anything similar in the new `crate.annotate`, so I'm not sure how to work around the issue.

**Comment by UebelAndre** [comment]
@SlyMarbo can you check if https://github.com/bazelbuild/rules_rust/pull/1174 solved the issue you were seeing with `default_features = False` having no effect?

Additionally, could you file a separate issue for [your last comment](https://github.com/bazelbuild/rules_rust/issues/1168#issuecomment-1059806271)?

**Comment by SlyMarbo** [comment]
@UebelAndre sadly #1174 doesn't seem to have helped. If it helps, I tried it by using commit 261f4e0. That commit also seems to have no reference to `default_features`, beside the field in `crate.spec`. I've opened #1176 for my second comment. Thanks :)

**Comment by UebelAndre** [comment]
@SlyMarbo Can you provide a repro case to test with?

**Comment by SlyMarbo** [comment]
I'm working on a smaller repro, but that doesn't seem to be exhibiting the issue so I'll keep debugging my main case ([ProjectSerenity/firefly](https://github.com/ProjectSerenity/firefly)) and let you know how I get on.

**Comment by SlyMarbo** [comment]
Here's my failed reproduction, just in case that helps: [SlyMarbo/sample-rules-rust-std](https://github.com/SlyMarbo/sample-rules-rust-std).

**Comment by SlyMarbo** [comment]
I have now been able to reproduce the issue in the smaller repro. For some reason, `default_features = False` worked correctly with just the `managed` crate, but not `smoltcp`. I can make a branch using the previous `crates_universe` functionality if that would help.

**Comment by UebelAndre** [comment]
> I have now been able to reproduce the issue in the smaller repro. For some reason, `default_features = False` worked correctly with just the `managed` crate, but not `smoltcp`. I can make a branch using the previous `crates_universe` functionality if that would help.

```diff
diff --git a/WORKSPACE b/WORKSPACE
index ec0989f..2fd1f2e 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -64,7 +64,6 @@ crates_repository(
             features = [
                 "alloc",
                 "async",
-                "default",
                 "libc",
                 "medium-ethernet",
                 "proto-dhcpv4",
```
This seems to work for me.

**Comment by SlyMarbo** [comment]
I'm the world's biggest idiot. Sorry for wasting your time. I really appreciate the help.

**Comment by UebelAndre** [comment]
> I'm the world's biggest idiot. Sorry for wasting your time. I really appreciate the help.

You're no idiot, I'd have done the exact same thing 😄 

Happy the tool is working for you. Don't hesitate to report any more funny behavior!

**Comment by SlyMarbo** [comment]
Will do. It's been working really well for me. I've migrated completely from Cargo to Bazel and rules_rust to allow the use of other languages and simpler code generation. Thanks again 😄
