### ISSUE TITLE
Crate universe examples on Windows super slow on the CI

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/rules_rust#1191]
Howdy folks, is it expected that these presubmits are taking >30 mins? One of the recent successful builds took >15mins.

**Comment by hlopko** [comment]
Example slow build: https://buildkite.com/bazel/rules-rust-rustlang/builds/5655#2bdcb386-6efa-48ff-b18b-90dfb828b492

**Comment by illicitonion** [comment]
I ran into the same surprise today - looks like it's spending forever on these steps:

```
Compiling Rust proc-macro async_trait v0.1.52 (21 files); 4369s local, remote-cache
Compiling Rust proc-macro async_stream_impl v0.3.3 (1 files); 4368s local, remote-cache
```

I _think_ this presubmit should be taking single-digit minutes, but I don't have a Windows environment to be debugging - @UebelAndre, any ideas?

**Comment by hlopko** [comment]
@meteorcloudy is the Windows CI healthy today?

**Comment by meteorcloudy** [comment]
Yes, Windows jobs for other projects look normal.

**Comment by UebelAndre** [comment]
A +1 hour action `Rustc` is unheard of to me. My Windows dev environment is a tiny VM that's barely staying together and no build has taken this long. 😞

**Comment by hlopko** [comment]
Today the CI is fast again (Last run finished in 4 minutes). I'm afraid this was a CI flake.
