### ISSUE TITLE
crates_universe: no documentation on how to create and maintain Cargo.Bazel.lock

### ISSUE THREAD

**Issue by roman-kashitsyn** [bazelbuild/rules_rust#1205]
The docs describing cargo-free setup of crates_universe mention `Cargo.Bazel.lock` file:
```bazel
crates_repository(
    name = "crate_index",
    lockfile = "//:Cargo.Bazel.lock",
    packages = {
        "async-trait": crate.spec(
            version = "0.1.51",
        ),
        "mockall": crate.spec(
            version = "0.10.2",
        ),
        "tokio": crate.spec(
            version = "1.12.0",
        ),
    },
    render_config = render_config(
        default_package_name = ""
    ),
)
```
The `lockfile` parameter is mandatory, but the doc does not explain how to create and maintain the `Cargo.Bazel.lock` file.
In the case of Cargo, `Cargo.lock` is automatically created and updated by `cargo`, no extra steps from users are required.

**Comment by UebelAndre** [comment]
Unfortuantely, as of right now you need to manually create the file before running Bazel. https://github.com/abrisco/cargo-bazel/issues/112 was the issue tracking making that better but I can get a new one open in `rules_rust` too. Once the file is there, the rule will be able to update it when you repin dependencies.

**Comment by roman-kashitsyn** [comment]
Creating an empty file worked, thanks a lot!
