### ISSUE TITLE
rust_clippy: no way to pass flags

### ISSUE THREAD

**Issue by roman-kashitsyn** [bazelbuild/rules_rust#1211]
The current documentation does not specify how to pass flags to the `clippy` tool: https://bazelbuild.github.io/rules_rust/rust_clippy.html#rust_clippy_aspect

Unfortunately, `clippy.toml` does not allow configuring lint levels: https://github.com/rust-lang/rust-clippy/issues/6625
The lints need to be configured on the command line, for example:
```
    -D warnings \
    -D clippy::all \
    -D clippy::mem_forget \
    -A clippy::redundant_closure \
    -A clippy::too_many_arguments \
    -C debug-assertions=off
```
Enabling this sort of configuration in `BUILD.bazel` or `.bazelrc` would be a very nice feature.

**Comment by UebelAndre** [comment]
Is this a duplicate of https://github.com/bazelbuild/rules_rust/issues/514 ?

**Comment by roman-kashitsyn** [comment]
> Is this a duplicate of #514 ?

Yes, that is the same issue. Thanks for finding the original!
