### ISSUE TITLE
Missing env variable NUM_JOBS for cargo build script

### ISSUE THREAD

**Issue by jgao54** [bazelbuild/rules_rust#1215]
While using rules_rust with cargo-raze, I encountered an issue where the [build script](https://github.com/gnzlbg/jemallocator/blob/c27a859e98e3cb790dc269773d9da71a1e918458/jemalloc-sys/build.rs#L60) for a dependency crate `jemalloc-sys 0.3.2` expects env var `NUM_JOBS`, which [cargo sets by default for build scripts](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts).

Not sure if `NUM_JOBS` is intentionally left out from [cargo_build_script_runner/bin.rs](https://github.com/bazelbuild/rules_rust/blob/main/cargo/cargo_build_script_runner/bin.rs) or not -- happy to create a PR to add it. 

There's also a related issue tracked in [cargo-raze](https://github.com/google/cargo-raze/issues/287) to support passing in custom build env vars. However, given this is a default cargo environment variable this might be a better place to add it.

**Comment by illicitonion** [comment]
Good catch, thanks for the bug report! Fixed in https://github.com/bazelbuild/rules_rust/pull/1216 :)
