### ISSUE TITLE
"Specifying Rust version" recommends `rust_repositories` but `rust_repositories` docs say it's deprecated

### ISSUE THREAD

**Issue by jfirebaugh** [bazelbuild/rules_rust#1224]
https://bazelbuild.github.io/rules_rust/#specifying-rust-version recommends to use `rust_repositories` to build with a particular version of the Rust compiler.

However, https://bazelbuild.github.io/rules_rust/flatten.html#rust_repositories says that `rust_repositories` is deprecated. If it's deprecated, it shouldn't be featured on the documentation landing page.

**Comment by UebelAndre** [comment]
Ah yeah, the docs there need to be updated, but https://bazelbuild.github.io/rules_rust/flatten.html#rust_repositories is correct, you just replace `rust_repositories` with `rules_rust_dependencies`. If you have a second to open a PR I'd super appreciate it and would be happy to be your reviewer 😄

**Comment by jfirebaugh** [comment]
Did you mean `rust_register_toolchains` rather than `rules_rust_dependencies`? The docs for `rust_register_toolchains` and `rules_rust_dependencies` seem to be missing, but the docs for `rust_repositories` say that the keyword arguments get passed to `rust_register_toolchains`.

**Comment by UebelAndre** [comment]
It's recommended to use `rules_rust_dependencies` to fetch other repositories `rules_rust` needs to function and `rust_register_toolchains` to download and register toolchains for the Rust compiler.
https://github.com/bazelbuild/rules_rust/blob/0.1.0/WORKSPACE.bazel#L3-L7
