### ISSUE TITLE
Release 0.2.1 with fixes for proto package

### ISSUE THREAD

**Issue by djmarcin** [bazelbuild/rules_rust#1242]
Release 0.2.0 seems broken when using the proto packages. #1241 fixed this but needs a release package to be built.

**Comment by UebelAndre** [comment]
Seems reasonable to me. I've opened https://github.com/bazelbuild/rules_rust/pull/1243 and am just waiting for concurrence from the other maintainers.

**Comment by UebelAndre** [comment]
This is done.
