### ISSUE TITLE
wasm_bindgen/BUILD.bazel is missing from 0.2.1 release

### ISSUE THREAD

**Issue by flaub** [bazelbuild/rules_rust#1246]
There seem to be some files missing from the released tarballs. Here's the WORKSPACE that fails for me:

```
http_archive(
    name = "rules_rust",
    sha256 = "b58c63a6d8221f408f8852b4f74f81bc8c7aac9273f3899a74e32e6168a2c624",
    url = "https://github.com/bazelbuild/rules_rust/releases/download/0.2.1/rules_rust-v0.2.1.tar.gz",
)

load("@rules_rust//wasm_bindgen:repositories.bzl", "rust_wasm_bindgen_repositories")

rust_wasm_bindgen_repositories()
```

I get the following error:
```
Label '@rules_rust//wasm_bindgen:repositories.bzl' is invalid because 'wasm_bindgen' is not a package; perhaps you meant to put the colon here: '@rules_rust//:wasm_bindgen/repositories.bzl'?
```

Downloading the tarball manually and inspecting the contents, it does appear that `wasm_bindgen/BUILD.bazel` is misssing.

**Comment by diceride** [comment]
@UebelAndre

**Comment by diceride** [comment]
Release version 0.2.0 is duped too.

**Comment by UebelAndre** [comment]
Hi, is this something you could submit a PR for? The fix seems pretty easy in that the `BUILD.bazel` file needs to be included here:
https://github.com/bazelbuild/rules_rust/blob/0.2.1/wasm_bindgen/BUILD.bazel#L14-L21
