### ISSUE TITLE
third party dependency libraries do are not properly disambiguated when the exec and target configurations are used

### ISSUE THREAD

**Issue by tzilist** [bazelbuild/rules_rust#1258]
Hello! I am running into a problem only in linux, build is fine in mac osx. The error I am seeing looks like this:

```
  = note: /usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/crates/billing/_ambiguous_libs/bin/libssl-648849910.a(bio_ssl.o): multiple definition of 'BIO_f_ssl'
          /usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/crates/billing/_ambiguous_libs/bin/libssl-944345047.a(bio_ssl.o): previous definition here
          /usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/crates/billing/_ambiguous_libs/bin/libssl-648849910.a(bio_ssl.o): multiple definition of 'BIO_new_ssl'
          /usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/crates/billing/_ambiguous_libs/bin/libssl-944345047.a(bio_ssl.o): previous definition here
          # hundreds of lines of similar output
 ```
 
 It appears that ambiguous libs are being linked from `fastbuild` and the `opt-exec`. Any thoughts on what could be causing this? These libs are coming from openssl, which I have copied verbatim from the examples directory in this repo. When I cd into the repo containing the issue I see this:
 
 ```
lrwxrwxrwx 1 root root  100 Apr 13 07:16 libcrypto-778601226.a -> /workspace/.bazel/execroot/osmos/bazel-out/k8-fastbuild/bin/external/openssl/openssl/lib/libcrypto.a
lrwxrwxrwx 1 root root  108 Apr 13 07:17 libcrypto-808729207.a -> /workspace/.bazel/execroot/osmos/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/openssl/openssl/lib/libcrypto.a
lrwxrwxrwx 1 root root  105 Apr 13 07:17 libssl-648849910.a -> /workspace/.bazel/execroot/osmos/bazel-out/k8-opt-exec-2B5CBBC6/bin/external/openssl/openssl/lib/libssl.a
lrwxrwxrwx 1 root root   97 Apr 13 07:16 libssl-944345047.a -> /workspace/.bazel/execroot/osmos/bazel-out/k8-fastbuild/bin/external/openssl/openssl/lib/libssl.a
 ```

**Comment by keith** [comment]
Can you make sure sandboxing is enabled in your build?

**Comment by tzilist** [comment]
I did try running with `--strategy=sandboxed` and I still ran into the same issue. What I _think_ I am seeing here is this

```
openssl -> libssh2 -> crate1 -|
                                                  | -> crate3
openssl  -----------> crate2 -|
```

This is somehow causing openssl to be imported 2 times but I am not entirely sure why

**Comment by scentini** [comment]
Hey @tzilist, could you confirm that this happens at `HEAD`?

**Comment by tzilist** [comment]
I can indeed confirm that this is still happening. On further inspection the dependency graph looks like such:

```
openssl -> libssh2 -> crate1 --|
openssl  --------------------> | -> crate3
openssl -> postgres -> crate2 -|
```

**Comment by tzilist** [comment]
After a bit of digging, it appears that this issue:
https://stackoverflow.com/questions/71203290/what-is-causing-duplicate-builds-of-same-target-in-bazel#comment126227591_71390131

Is indeed what is happening here. I am not exactly sure how to solve this as it involves foreign_cc and rust_rules interop

**Comment by tzilist** [comment]
I think this is the crate causing an issue
![graph](https://user-images.githubusercontent.com/14153237/166169173-a026cb49-efdb-4df0-ac71-56315134cfc3.png)

**Comment by tzilist** [comment]
After lots of digging, I believe I have isolated down the issue:

It appears that the portion of code where ambiguous libs is handled does not differentiate between libs for the `target` configuration and the libs for the `exec` configuration

**Comment by scentini** [comment]
Thanks for investigating!

I think the issue here is that we still propagate some inputs from `proc_macro`s (which are built in host configuration) to the dependents. I fixed this for crates in https://github.com/bazelbuild/rules_rust/pull/1206 but not for non-crate inputs.

Could you try modifying this: https://github.com/bazelbuild/rules_rust/blob/b04fe3b21fde35b6d4ab8eae0e8be2067cc87d31/rust/private/rustc.bzl#L194
to be:
```
if "proc-macro" not in [crate_info.type, crate_info.wrapped_crate_type]:
    transitive_noncrates.append(dep_info.transitive_noncrates)
```

**Comment by tzilist** [comment]
Aha! That fixed it!

If anyone else runs into this before the fix is merged/released, you can just create a file

`rust_rules.patch`
```patch
diff --git a/rust/private/rustc.bzl b/rust/private/rustc.bzl
index 47fc576..b976a93 100644
--- a/rust/private/rustc.bzl
+++ b/rust/private/rustc.bzl
@@ -191,7 +191,8 @@ def collect_deps(
                     ] else [dep_info.transitive_crate_outputs],
                 ),
             )
-            transitive_noncrates.append(dep_info.transitive_noncrates)
+            if "proc-macro" not in [crate_info.type, crate_info.wrapped_crate_type]:
+              transitive_noncrates.append(dep_info.transitive_noncrates)
             transitive_build_infos.append(dep_info.transitive_build_infos)
             transitive_link_search_paths.append(dep_info.link_search_path_files)
 
```

and add the following to your `http_archive` rule for `rules_rust`
```starlark
http_archive(
    name = "rules_rust",
    patch_args = ["-p1"], # here
    patches = ["//:rules_rust.patch"], # here
    sha256 = "e074f1e203607c5fcd549929d956170346f8807d2bbaeb98b2ed213c37e0870f",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_rust/releases/download/0.3.1/rules_rust-v0.3.1.tar.gz",
        "https://github.com/bazelbuild/rules_rust/releases/download/0.3.1/rules_rust-v0.3.1.tar.gz",
    ],
)
```
