### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_rust#1272]
It would be great to have a new release cut for those of us who don't consume rules_rust at HEAD. Since 0.2.1, an [important fix](https://github.com/bazelbuild/rules_rust/commit/b594f90f175edd883ab29c936f1bb019e600094f) was merged, as well as some [ergonomics](https://github.com/bazelbuild/rules_rust/commit/b778fca0ac4dfcf3c9e24f1517e73d39d739c730).

**Comment by duarten** [comment]
@UebelAndre the release seems broken, it's missing the `util/process_wrapper/BUILD.tinyjson.bazel` file :(

**Comment by UebelAndre** [comment]
Always something!

**Comment by UebelAndre** [comment]
> @UebelAndre the release seems broken, it's missing the `util/process_wrapper/BUILD.tinyjson.bazel` file :(

@duarten, could I trouble you for a bugfix PR?
