### ISSUE TITLE
Tool for generating BUILD files from Cargo.toml

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/rules_rust#13]
Creating a tool for generating BUILD/WORKSPACE files from Cargo.toml+Cargo.lock would be very useful and would greatly lower the barrier for Rust developers who are used to Cargo to use Bazel to build Rust projects.

This would be similar in concept to the `glaze` tool for generating BUILD files for Go projects (bazelbuild/rules_go#15).

One possible fun name for this tool: `raze`

**Comment by yugui** [comment]
Now I'm trying to implement a `BUILD` file generator for Go, called `gazel`.

In this effort, I realized that there are some language-independent features required by such `BUILD` file generator. So it might be better if we can share implementation of such features.

The features are, for example,
1. Locate existing `WORKSPACE` files in the target repository.
2. Reconcile existing manually-configured rules with the automatically generated ones.
    e.g. sometimes users need to manually add `data`, `license` or `args` attributes into automatically generated rules.
   In this case, `BUILD` file generator needs to respect such attributes when it runs next time.

**Comment by davidzchen** [comment]
+cc @kchodorow, @damienmg

Those are some good ideas, @yugui. Ideally, it would be great to have a generic tool for generating BUILD/WORKSPACE with extensions that are specific to different languages and different build systems (e.g. Cargo for Rust, `go build` for Go, Dub for D, etc.). Ideally, this should also make it possible to bring in the [`generate_workspace`](https://github.com/bazelbuild/bazel/tree/master/src/tools/generate_workspace) for Java projects as an extension as well.

I am thinking perhaps the language-specific extension can be something like a separate command line tool that outputs data in a common format such as JSON (since most likely, most languages should have a JSON library) that would specify what should be added to the WORKSPACE file, the BUILD files to generate, etc.

WDYT?

As for naming, have you considered keeping the name of the tool as `glaze` or maybe even `gaze`? I'm thinking that the name `gazel` might be a bit obscure since it doesn't sound like another word (as opposed to Bazel sounding like "basil") and the original pun around the name would be lost.

**Comment by damienmg** [comment]
+cc @laurentlb has proposed making the skylark/build file parser from bazel an independent library.

**Comment by lilianmoraru** [comment]
Update: a similar tool was created and it seems to do the job pretty ok: https://github.com/acmcarther/cargo-raze

**Comment by mfarrugi** [comment]
Raze now lives at https://github.com/google/cargo-raze
