### ISSUE TITLE
Cargo.Bazel.lock generator behaves differently on Linux and macOS

### ISSUE THREAD

**Issue by roman-kashitsyn** [bazelbuild/rules_rust#1328]
I have
```
        "prometheus": crate.spec(
            features = ["process"],
            version = "0.13.0",
        )
```
in my crate_index config, and on macOS I see "selects": {} for the `prometheus` package in `Cargo.Bazel.lock`, while on Linux I see
```
"selects": {
   "cfg(target_os = \"linux\")": [
     {
       "id": "procfs 0.10.1",
       "target": "procfs"
     }
   ]
}
```
The version generated on macOS doesn't compile on Linux:
```
error[E0433]: failed to resolve: use of undeclared crate or module `procfs`
   --> external/crate_index__prometheus-0.13.0/src/process_collector.rs:137:23
    |
137 |         let p = match procfs::process::Process::new(self.pid) {
    |                       ^^^^^^ use of undeclared crate or module `procfs`
```

**Comment by roman-kashitsyn** [comment]
I tried to reproduce this behavior on a small example but it didn't work.
Furthermore, I can't reproduce this behavior on a fresh checkout of my repo.

**Comment by UebelAndre** [comment]
I'm gonna close this out until there's another repro. This would definitely be a major bug so if anyone has a repro I'd be happy to take a look.
