### ISSUE TITLE
crate_universe: explicitly added packages do not override transitive dependencies

### ISSUE THREAD

**Issue by roman-kashitsyn** [bazelbuild/rules_rust#1369]
If I have a single package in the workspace,
```
crates_repository(
    name = "crate_index",
    lockfile = "//:Cargo.Bazel.lock",
    packages = {
        "webpki": crate.spec(
            git = "https://github.com/dfinity-lab/webpki",
            rev = "3e783d8eb46c3f28f4c43f882d9a11f35acb0dab",
        ),
    },
    splicing_config = splicing_config(
        resolver_version = "2",
    ),
)
```
cargo-bazel picks the correct repository for the `webpki` package in `Cargo.Bazel.lock`:
```
    "webpki 0.21.4": {
      "name": "webpki",
      "version": "0.21.4",
      "repository": {
        "Git": {
          "remote": "https://github.com/dfinity-lab/webpki",
          "commitish": {
            "Rev": "3e783d8eb46c3f28f4c43f882d9a11f35acb0dab"
          }
        }
      },
```
However, if I add another package to the workspace that needs `webpki` transitively:
```
crates_repository(
    name = "crate_index",
    lockfile = "//:Cargo.Bazel.lock",
    packages = {
        "rustls": crate.spec(version = "0.19.1"),
        "webpki": crate.spec(
            git = "https://github.com/dfinity-lab/webpki",
            rev = "3e783d8eb46c3f28f4c43f882d9a11f35acb0dab",
        ),
    },
    splicing_config = splicing_config(
        resolver_version = "2",
    ),
)
```
Then cargo-bazel picks the version from [crates.io](http://crates.io/):
```
    "webpki 0.21.4": {
      "name": "webpki",
      "version": "0.21.4",
      "repository": {
        "Http": {
          "url": "https://crates.io/api/v1/crates/webpki/0.21.4/download",
          "sha256": "b8e38c0608262c46d4a56202ebabdeb094cef7e560ca7a226c6bf055188aa4ea"
        }
      },
```

Expected behavior: `cargo-bazel` uses the explicitly specified version of `webpki` for transitive dependencies just as Cargo does.

**Comment by UebelAndre** [comment]
Is there not another instance of `webpki` within the lockfile? This feels like behavior I've hit in standard cargo setups (and `crate_universe` basically just maps cargo dependency trees to Bazel).

**Comment by roman-kashitsyn** [comment]
> Is there not another instance of `webpki` within the lockfile? This feels like behavior I've hit in standard cargo setups (and `crate_universe` basically just maps cargo dependency trees to Bazel).

I think that's true, it's not crate_universe's issue.
We worked around the problem by using `cargo_config` parameter of the `crates_repository` rule (https://sourcegraph.com/github.com/dfinity/ic@c01d7d1b2e18490a2f70d2fdf5b6aceccab5860c/-/blob/bazel/external_crates.bzl?L14).

**Comment by UebelAndre** [comment]
I’ve had some success also using [`[patch]`](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#the-patch-section) to coerce all versions of a package into whatever’s specified. If you have access to an alternate crates registry you can use that in combination with your Cargo config file. Git repositories should also work just fine.
