### ISSUE TITLE
Feature Request: support air-gapped builds

### ISSUE THREAD

**Issue by cfrantz** [bazelbuild/rules_rust#1373]
The [OpenTitan Project](https://opentitan.org) needs to use bazel in air-gapped/offline configurations.  It appears that currently, rules_rust does not support an air-gapped configuration.

We are currently using a modified version of rules_rust to support this configuration.  My teammate (@timothytrippel) worked out a [small change](https://github.com/lowRISC/rules_rust/commit/be0d6ca492f64cc8d460f54f467925ef2753ed89) to support offline environments.  From his commit message:

"""
These `rust_rules` attempt to download the `rust_linux_x86_64` external
repository using the `ctx.download` action. Unfortunately, it seems this
action does not first check in the repository cache for files before
downloading, whereas the `ctx.download_and_extract` action does.
"""

What is the proper approach for adding air-gapped support to rules_rust?

**Comment by hlopko** [comment]
@UebelAndre, what do you think about using download_and_extract?

**Comment by UebelAndre** [comment]
I've had the same thought and was trying to implement https://github.com/bazelbuild/rules_rust/pull/1163 as a means of accounting for this (in addition to other things) but if there's a way to achieve this with a small update I'm for it. However, I'm not sure I'm the biggest fan of the `execute` call:
```starlark
    compressed_tool_path = tool_path + ".tar.gz"
    ctx.execute(["tar", "-czvf", compressed_tool_path, tool_path])
```
If we're really going to need to download, extract, compress, then extract the content again? Why couldn't we just call `download_and_extract` multiple times if it's going to be the same archive from a repository cache?

That said though, the real solution seems as though `ctx.download` *should* check the repository cache and an issue should be opened in upstream Bazel.

**Comment by cfrantz** [comment]
I agree that `download_and_extract` followed by "tar it back up again" is suboptimal.  Multiple calls to `download_and_extract` sounds good to me.
