### ISSUE TITLE
Possible regression causing linking of proc_macro

### ISSUE THREAD

**Issue by snowp** [bazelbuild/rules_rust#1374]
We updated rules_rust from 0.4.0 to 28ac6b133dfce65f9e9e01a5de2b4e034410e080 and ran into an issue where proc_macro is now statically linked into a test binary, causing 

```
/home/runner/.cache/bazel/_bazel_runner/374864cd5aeb008ef6a614637fda772e/sandbox/linux-sandbox/630/execroot/__main__/bazel-out/k8-fastbuild/bin/src/wrapper/buffer_test.runfiles/__main__/src/wrapper/_buffer_test: error while loading shared libraries: libstd-05b39ac0cb4c5688.so: cannot open shared object file: No such file or directory
```

21eed19188c0359d72f9a508a0c0e7040ff20070...28ac6b133dfce65f9e9e01a5de2b4e034410e080

I made sure that this was not coming from the Rust version upgrade (tried bad sha + 1.60). 

I don't have a simple reproducer, though I suspect it's coming from our usage of cxx, though we also make use of other proc_macro libraries such as tokio, thiserror, prost, etc.

**Comment by scentini** [comment]
I managed to create a [simple repro](https://github.com/scentini/repro_1374). This is not related to `proc_macros`; the culprit is https://github.com/bazelbuild/rules_rust/pull/1333 and @krasimirgg and I are discussing the best way forward.

**Comment by scentini** [comment]
@snowp could you check whether https://github.com/bazelbuild/rules_rust/pull/1394 solves the problem for you?

**Comment by scentini** [comment]
Thanks! That's the same error, just on macos this time, which is a reminder that we should apply the solution to all platforms.

**Comment by Reflejo** [comment]
@scentini Were you able to make any progress with this issue? Thanks!

**Comment by scentini** [comment]
Hey folks, I have https://github.com/bazelbuild/rules_rust/pull/1500 up for review.

**Comment by snowp** [comment]
After applying this fix I'm still seeing
```
dyld[51630]: Library not loaded: '@rpath/libtest-e6734f05acc07fba.dylib'
  Referenced from: '/private/var/tmp/_bazel_snowp/c1591b76b8a2fcd15b6ff3cd34fdd7da/execroot/__main__/bazel-out/darwin_arm64-fastbuild/bin/test/client/logger_runner'
  Reason: tried: '/usr/local/lib/libtest-e6734f05acc07fba.dylib' (no such file), '/usr/lib/libtest-e6734f05acc07fba.dylib' (no such file)

```

for one of our use cases on macos (linux is fine). Would you prefer me to open up a new issue to track this?
