### ISSUE TITLE
Prevent dependabot from opening issues about test or example data

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#1390]
Over the weekend it seems someone enabled dependabot and it now suggest changes that are likely to generate a ton of noise and do not have a meaningful impact to users. We should make sure we don't get walls of similar issues in the future.

New issues:
- https://github.com/bazelbuild/rules_rust/pull/1389
- https://github.com/bazelbuild/rules_rust/pull/1388
- https://github.com/bazelbuild/rules_rust/pull/1386

- https://github.com/bazelbuild/rules_rust/pull/1385
- https://github.com/bazelbuild/rules_rust/pull/1383

Of all the new issues, these are the only ones that *might* be remotely beneficial as it's complaining about real dependencies users might consume.
- https://github.com/bazelbuild/rules_rust/pull/1387
- https://github.com/bazelbuild/rules_rust/pull/1382

**Comment by UebelAndre** [comment]
cc @hlopko @scentini

Figured this is something only Googlers would have insight into.

**Comment by scentini** [comment]
It looks like I don't have sufficient permissions to make such changes to this repository, reassigning to @hlopko.

**Comment by hlopko** [comment]
I've just disabled the dependabot completely, but I'm tempted to enable it back again once https://github.com/dependabot/dependabot-core/issues/4364 is resolved (so we can ignore `/examples` since those warnings are not highly important if you ask me, but introduce a lot of noise)
