### ISSUE TITLE
Make it easier to use Rust rules with different versions of Rust

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/rules_rust#14]
Currently, the version of Rust used by the rules are not easily configurable. We should make it easier to use the Rust rules with different Rust versions, such as via a `rust_toolchain` rule (similar to `cc_toolchain`) or look at the approach taken by tools such as multirust.

It would also be good to make it easy to switch between having Bazel download a set of Rust binaries and using the ones installed on the local system.

**Comment by davidzchen** [comment]
+cc @katre

**Comment by katre** [comment]
I am working on this as part of my ongoing work on Bazel Platform support, so I will take this issue.

**Comment by davidzchen** [comment]
Sounds awesome. Thanks!
