### ISSUE TITLE
crate_universe should not modify the manifests provided if they represent a valid cargo workspace

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_rust#1447]
This rust project
https://github.com/swc-project/swc
has a Cargo.lock file in the root, then a tree of Cargo.toml files for all the crates it builds.

https://gist.github.com/alexeagle/b0a290dd09860cf2db04c6f13025d0aa shows how I've tried to fetch 3p dependencies for this project (I'm trying to build it as an external repository)

I get an error about the lockfile being out-of-date:
```
    Updating crates.io index
error: the lock file /tmp/.tmpDxxX85/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```
but this lockfile is in a 3p project and so I don't want to change it.

On slack @UebelAndre says:
> it seems `crates_repository` doesn't think the manifests you provided are all a part of the same workspace and tries to generate a custom root manifest. You can probably fix this by using your own lockfile but otherwise this is a bug in the splicing phase of the tool.

**Comment by diceride** [comment]
I'm having the same problem when creating a new project from scratch using only the rules_rust ruleset and one single workspace member using rust_library.

Cargo.toml
```toml
[workspace]
members = [
    "foo/bar",
]
```

WORKSPACE
```starlark
crates_repository(
    name = "crate_index",
    cargo_lockfile = "//:Cargo.Bazel.lock",
    manifests = [
        "//:Cargo.toml",
        "//foo/bar:Cargo.toml",
    ],
)

load("@crate_index//:defs.bzl", "crate_repositories")

crate_repositories()
```

```
...
error: the lock file /tmp/.tmpBwan59/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.

Error: Failed to fetch crates for lockfile: exit status: 101
...
```

**Comment by boxdot** [comment]
In my case, the lock has to be updated because the generated `Cargo.toml` contains a special `[package]` section:

```
< name = "direct-cargo-bazel-deps"
< version = "0.0.1"
<
< [[package]]
```

**Comment by lbruno** [comment]
For what it's worth I get the same error message, and I have no diffs between the spliced workspace's Cargo.lock and my top-level Cargo.lock

```
crates_repository(
    name = "crate_index",
    cargo_lockfile = "//:Cargo.lock",
    manifests = [
        # TODO: why doesn't it work if i specify a top-level Cargo workspace?
        # "//:Cargo.toml",
        "//:patricia/Cargo.toml",
        "//rshell:Cargo.toml",
        "//tap:Cargo.toml",
    ],
)
```

I had that same diff, so i removed that block [i could've sworn from the toplevel non-spliced Cargo.lock and now i see no diffs when i run

```
code --diff C:\users\bruno\_bazel_bruno\c32mugc7\external\crate_index\splicing-workspace\Cargo.lock .\Cargo.lock
```

**Comment by lbruno** [comment]
K, so i also needed `lockfile = "//:Bazel-cargo-lock.json"`, touch that empty file, and then i'm forced to rerun bazel after setting `$env:CARGO_BAZEL_REPIN=$true`.

so i guess this bit works now :)

i'm having trouble trying to actually use the dependencies i vendored into //cargo/vendor, but that's the subject of a different bug
