### ISSUE TITLE
Issue running coverage, missing util/collect_coverage.sh

### ISSUE THREAD

**Issue by snowp** [bazelbuild/rules_rust#1449]
When trying to run the newly added coverage support via `bazel coverage` the build fails with 

```
ERROR: /Users/snowp/src/sdk/src/debugger/BUILD:3:18: Testing //src/debugger:debugger_test failed: missing input file '@rules_rust//util:collect_coverage.sh'
```

This is using the 0.7.0 release. 

Seems to me like the util/collect_coverage.sh script is not included in the release

cc @keith

**Comment by UebelAndre** [comment]
This is a miss due to the lack of https://github.com/bazelbuild/rules_rust/issues/1294. https://github.com/bazelbuild/rules_rust/pull/1450 should fix this and then we can get a new release out.
