### ISSUE TITLE
Promote crate_universe to non-experimental

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#1495]
I think `crate_universe` is stable enough to be considered non-experimental. Given the amount of unit and integration tests for the tool as well as the integration from the following PRs:

- https://github.com/bazelbuild/rules_rust/pull/1494
- https://github.com/bazelbuild/rules_rust/pull/1492
- https://github.com/bazelbuild/rules_rust/pull/1491
- https://github.com/bazelbuild/rules_rust/pull/1448
- https://github.com/bazelbuild/rules_rust/pull/1440
- https://github.com/bazelbuild/rules_rust/pull/1398

I'd like to remove the [experimental header](https://github.com/bazelbuild/rules_rust/blob/0.8.1/crate_universe/docs.bzl#L5-L7).

**Comment by UebelAndre** [comment]
cc @illicitonion

**Comment by illicitonion** [comment]
I'd be fine with that, but /cc:
- [x] @UebelAndre 
- [x] @illicitonion 
- [ ] @hlopko
- [ ] @scentini
- [ ] @krasimirgg
- [ ] @dfreese

**Comment by UebelAndre** [comment]
I've put together a pull-request (https://github.com/bazelbuild/rules_rust/pull/1504) to update the documentation since it seems maintainers are generally in favor of the change.
