### ISSUE TITLE
Mirror URL for `http_archive` give 404s

### ISSUE THREAD

**Issue by binoche9** [bazelbuild/rules_rust#1502]
If I use the following snippet from https://github.com/bazelbuild/rules_rust/releases/tag/0.8.1:

```txt
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_rust",
    sha256 = "05e15e536cc1e5fd7b395d044fc2dabf73d2b27622fbc10504b7e48219bb09bc",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_rust/releases/download/0.8.1/rules_rust-v0.8.1.tar.gz",
        "https://github.com/bazelbuild/rules_rust/releases/download/0.8.1/rules_rust-v0.8.1.tar.gz",
    ],
)
```

I see the following warning:
```
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_rust/releases/download/0.8.1/rules_rust-v0.2.1.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

Looking at https://mirror.bazel.build/ (and also manually guessing other URLs) it seems like none of the `rules_rust` versions are on the mirror repository - is it possible we're not properly uploading to there?

**Comment by silas-enf** [comment]
I was just searching slack for the same issue and saw another user put in their own request for 0.7.0 (https://github.com/bazelbuild/bazel/issues/15881), so I just did the same for 0.8.0 and 0.8.1 (https://github.com/bazelbuild/bazel/issues/16056).

It seems there may be an unresolved problem with the release process.

**Comment by iamricard** [comment]
👋🏼 this seems to happen consistently (0.11.0 also returns a 404). how about the release notes omit the mirror until the issue is resolved? although i thought there was no automated process, just a [Googler doing it](https://github.com/bazelbuild/rules_python/issues/400#issuecomment-776810051)

**Comment by UebelAndre** [comment]
Reopening until I’ve had time to remove references to the Google mirror from older release notes.

**Comment by UebelAndre** [comment]
The release notes have been updated. The only outstanding item is https://github.com/bazelbuild/rules_rust/pull/1607
