### ISSUE TITLE
Broken rust_library with modules and generated sources

### ISSUE THREAD

**Issue by hchataing** [bazelbuild/rules_rust#1510]
The commit `c7cb5bd7a85496b31ab3e20216e7b35677572d09` wrongly flattens the hierarchy of rust crates.
This results in the any crate using modules not compiling anymore as long as it uses generated sources as well.

```
src/lib.rs
src/my_module/mod.rs
src/my_module/stuff.rs
```

```
rust_library(
   name = "my_crate",
   srcs = [
       "src/my_module/mod.rs",
       "src/my_module/stuff.rs",
       "src/lib.rs",
       ":generated_file",
   ]
)
```

The error comes from the use of `src.basename` in `transform_sources`, instead of the relative file path as it should.

**Comment by cameron-martin** [comment]
I'm struggling to find a way of getting this relative path. [src.short_path](https://bazel.build/rules/lib/File#short_path) and [src.path](https://bazel.build/rules/lib/File#path) both return the file path relative to the workspace root, where I instead want the file path relative to the package root. If it was possible to find the package root, I could do `src.path.removeprefix(package_root)`, but I can't see a way of doing that.

**Comment by hchataing** [comment]
Thanks for the speedy fix!
