### ISSUE TITLE
rust_doc_test fails for libraries with compile_data

### ISSUE THREAD

**Issue by roman-kashitsyn** [bazelbuild/rules_rust#1572]
`rust_doc_test` fails if used on a crate that has compile-time data dependencies.
Minimal example:

`BUILD.bazel` file:

```python
load(
    "@rules_rust//rust:defs.bzl",
    "rust_doc_test",
    "rust_library",
)

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "lib",
    srcs = ["lib.rs"],
    compile_data = [":data.txt"],
    rustc_env = {
        "DATA_PATH": "$(execpath :data.txt)",
    },
)

rust_doc_test(
    name = "doc_test",
    crate = ":lib",
)
```

`lib.rs` file:

```rust
const DATA: &str = include_str!(env!("DATA_PATH"));

/// Returns the embedded textual data.
/// ```
/// assert!(!get_data().is_empty());
/// ```
pub fn get_data() -> &'static str {
    &DATA
}
```

`data.txt` file:

```
Hello, World!
```

How to reproduce:
Copy the files above into `examples/doc_test_compile_data` and run bazel test:

```
λ rules_rust/examples/doc_test_compile_data/ main* bazel test :doc_test
bazel test :doc_test

ERROR: /Users/lifted/Projects/rules_rust/examples/doc_test_compile_data/BUILD.bazel:18:14: in deps attribute of rust_doc_test rule //doc_test_compile_data:doc_test: source file '//doc_test_compile_data:data.txt' is misplaced here (expected no files)
ERROR: /Users/lifted/Projects/rules_rust/examples/doc_test_compile_data/BUILD.bazel:18:14: Analysis of target '//doc_test_compile_data:doc_test' failed
ERROR: Analysis of target '//doc_test_compile_data:doc_test' failed; build aborted: 
```

**Comment by paulfariello** [comment]
We have a similar issue when using expansion like: `$(location :data.txt)`.

It seems to originate from `construct_arguments` in rustc.bzl.

https://github.com/bazelbuild/rules_rust/blob/532e60ff0ee3ac318333b3ae05392c220b17ce28/rust/private/rustc.bzl#L909

When it compute `data_paths` it uses `getattr(attr, "compile_data", [])` which is obviously empty for rust_doc.

It seems like using `crate_info` could  to fix it.

**Comment by UebelAndre** [comment]
It looks like `CrateInfo` has a `compile_data` field. I’d be happy to review a pull-request to integrate that if someone wanted to open one 😄

**Comment by paulfariello** [comment]
I would be happy to open a PR but replacing attr.compile_data with crate_info leads to the following error:
```
 Error in expand_location: at index 0 of targets, got element of type File, want Target
```

If you have any clue on this, I'll go forward ;)
