### ISSUE TITLE
proc_macros do not work with RA on 1.64

### ISSUE THREAD

**Issue by snowp** [bazelbuild/rules_rust#1576]
Per https://github.com/rust-lang/rust-analyzer/issues/13322 for 1.64 we need to provide sysroot in rust-project.json + set up the symlinks for `rust-analyzer-proc-macro-srv` in order for the proc_macros to work out of the box with rules_rust's RA integration

A temporary workaround for anyone that run into this is specifying the proc macro server in the RA config, e.g. 

```
    "rust-analyzer.procMacro.server": "/Users/snowp/.rustup/toolchains/1.64-aarch64-apple-darwin/libexec/rust-analyzer-proc-macro-srv",

```

I got something that I think works, will get a PR up

**Comment by UebelAndre** [comment]
A pull request would be welcome! 🙏
