### ISSUE TITLE
Crates Universe not exposing binary targets

### ISSUE THREAD

**Issue by rdelfin** [bazelbuild/rules_rust#1598]
I'm in the process of switching a repo from `cargo raze` to `crates_universe` and I encountered an issue with binary cargo deps. Specifically, there's a handful of dependencies we use as plain binaries. An example of this would be the [`cxxbridge-cmd` ](https://crates.io/crates/cxxbridge-cmd) crate, which lets us interface with C++ code.

As part of how it works, it has a binary which is responsible for generating the corresponding C++ code that bridges across languages. We execute this inside a genrule, making use of the `package.metadata.raze.binary_deps` setting in `cargo raze`. However, when switching over to crates universe, I noticed there's no such way of exposing binary deps. When adding `cxxbridge-cmd` it just exposes the binary as if it were a library. I did notice however, as you can see in my example repo [rdelfin/rust-bazel-universe-test](https://github.com/rdelfin/rust-bazel-universe-test), that there is a binary target hidden within the generated external workspace for my `crates_repository`. What would need to be done to expose this target out?

**Comment by UebelAndre** [comment]
`crates_repository` generates aliases for binary targets in a package as `{crate_name}__{binary}`. So you should have a binary available for you at `@crate_index//:cxxbridge-cmd__cxxbridge`. Does that work for your use cases?

**Comment by rdelfin** [comment]
Amazing! That seems to work @UebelAndre. I'll go ahead and close this issue and you might see a PR from me adding this to the documentation
