### ISSUE TITLE
Fix Bazel incompatible changes

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_rust#161]
I'd like to be able to build rules_rust with `--all_incompatible_changes`:
`cd rules_rust && bazel build --all_incompatible_changes //...`

It may not be possible to fix every issue now due to transitive dependencies, but we should try to fix the issues from this repository.

**Comment by mhlopko** [comment]
Blocked by https://github.com/bazelbuild/rules_sass/issues/62
