### ISSUE TITLE
Per-toolchain rustflags

### ISSUE THREAD

**Issue by P1n3appl3** [bazelbuild/rules_rust#1623]
You can already set `stdlib_linkflags` on a `rust_toolchain` so that every target that links to std adds those flags. We have a `rust_toolchain` with a stdlib that's compiled with `Cpanic=abort`, so we need every target that's built with that toolchain to also set panic abort in their _rustflags_.

We initially tried setting this globally by putting `'--@rules_rust//:extra_exec_rustc_flags="-Cpanic=abort"'` in our bazelrc, but we have multiple rust_toolchains in our build, and some of them do have a std built with panic=unwind, so we need a way to apply this flag to only targets built under the specific toolchain that sets panic=abort. Would adding `stdlib_rustflags` to the `ToolchainInfo` and threading it through to the compile actions similar to the linkflags be a reasonable way to do this?

**Comment by krasimirgg** [comment]
This will be useful for us as well. I'm experimenting with sanitizer-enabled toolchains, where we want to always pass, e.g., `-Zsanitize=address` when using a specific rust toolchain (that contains pre-built sanitized versions of the standard libraries). Note that since we have two flavours of extra flags (exec and non-exec), we'd need two flavours of per-toolchain rust flags as well, e.g., `ToolchainInfo.extra_rustc_flags` and `ToolchainInfo.extra_exec_rustc_flags`.

**Comment by UebelAndre** [comment]
Isn't there prior art for this too for C/C++ toolchains too? Can't you pass `linkopts` and `copts` to the toolchain too to have it set on all targets? I think it sounds totally reasonable to have some binary/library/test attributes get added to `rust_toolchain` where flags set there would apply to all targets built with it.

**Comment by scentini** [comment]
@UebelAndre Yes, and it is much more powerful than this FR. In C/C++ rules land most of the flags end up going through the toolchain, even flags set via attributes on rules. Most of this is realised via the `--features` option and so-called toolchain variables that get populated in the rule implementation.
For example, there is the [`user_compile_flags`](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/unix_cc_toolchain_config.bzl#L304) feature that is unconditionally enabled (meaning its flags always end up on the command line) and whose `user_compile_flags` toolchain variable contains flags somehow specified by the user (eg via `cc_library.copts`). Then there is the [`thin_lto`](https://github.com/bazelbuild/bazel/blob/master/tools/cpp/unix_cc_toolchain_config.bzl#L1129) feature that contains the ThinLTO specific flags, which is not enabled by default, but the user can enable with `--features=thin_lto`. There is feature algebra that allows for specifying relations between features, eg, feature X and Y cannot both be enabled, the flags of X will only be expanded on the commandline if feature Y is enabled but feature Z is not, and so on.
[C++ Toolchain Configuration ](https://bazel.build/docs/cc-toolchain-config-reference) might be a good read on the topic.

**Comment by UebelAndre** [comment]
Adding features like this sound good to me as long as it doesn't restrict us from picking up similar features to the more mature `cc_toolchain`. 😄

**Comment by rickvanprim** [comment]
Maybe I'm overlooking something, but as implemented in #1635, there doesn't seem to be a good way to set these flags at the top level if you're using `rust_register_toolchains()`.  I've taken a quick stab at plumbing that through (https://github.com/rickvanprim/rules_rust/pull/1).  Is there a better way to do this?

**Comment by sthornington** [comment]
I'm here now too - we have build configs for enabling e.g. ubsan, via adding flags to copts and linkopts in the bazelrc for build.ubsan for instance. Does this feature allow us to add similar flags for rustc e.g. -Z sanitizer=undefined ?

This is primarily to resolve link issues when C++ code compiled in the ubsan config/toolchain is linked into a rust binary via e.g. cxx. Thanks.
