### ISSUE TITLE
crate_universe support for `resolver = "2"` target-specific features

### ISSUE THREAD

**Issue by wmatthews-google** [bazelbuild/rules_rust#1662]
As far as I can tell, `crate_universe` doesn't support target-specific feature selection.

E.g. (from https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2)
```toml
[dependency.common]
version = "1.0"
features = ["f1"]

[target.'cfg(windows)'.dependencies.common]
version = "1.0"
features = ["f2"]
```

will lead to `crate_universe` generating
```python
crate_features = [
    "f1",
    "f2",
]
```

I think it'd be better if it generated something more like
```python
crate_features = select({
    "@rules_rust//rust/platform:x86_64-pc-windows-msvc": ["f1", "f2"],
    "//conditions:default": ["f1"],
})
```

This is particularly an issue for [`wgpu-hal`](https://crates.io/crates/wgpu-hal) and therefore generally for [`wgpu`](https://crates.io/crates/wgpu) which fails with errors like like the following (on Mac):
```
error: DX12 API enabled on non-Windows OS. If your project is not using resolver="2" in Cargo.toml, it should.
  --> external/crates_vendor__wgpu-hal-0.13.2/src/lib.rs:53:1
   |
53 | compile_error!("DX12 API enabled on non-Windows OS. If your project is not using resolver=\"2\" in Cargo.toml, it should.");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: use of undeclared crate or module `winapi`
 --> external/crates_vendor__wgpu-hal-0.13.2/src/auxil/dxgi/conv.rs:1:5
  |
1 | use winapi::shared::dxgiformat;
  |     ^^^^^^ use of undeclared crate or module `winapi`
...
```

Manually updating the BUILD files generated to have the "right" set of features for the given platform allows it to compile successfully.

Looking a bit at [cargo-raze](https://github.com/google/cargo-raze), which handles this reasonably well, it appears they're parsing target-specific feature sets from `cargo tree` rather than `cargo metadata` because the former supports `resolver = "2"` while the latter doesn't.

Would you folks be up for a PR attempting to do a similar thing here?

**Comment by illicitonion** [comment]
Thanks for filing the issue! Yeah, we have https://github.com/rust-lang/cargo/issues/9863 open against cargo to get this exposed via `cargo metadata`, but don't expect any progress to be made on it with any particular time-frame.

I would be very happy to review and merge in a port/rewrite of @sayrer's `cargo tree` code from `cargo-raze`. I think it was mostly originally in https://github.com/google/cargo-raze/pull/478.

FWIW I think this is one of the remaining significant issues blocking folks from migrating from cargo-raze to crate_universe, and it would be great to get resolved!

**Comment by wmatthews-google** [comment]
Sounds good... I'll see what I can do...

Thanks for the links.

**Comment by wmatthews-google** [comment]
I've got this pretty much working, just need to tidy up some rough edges and add a few more tests. Probably expect a PR in the next few days.

**Comment by UebelAndre** [comment]
Why do you mean? Vendoring also generates build files

**Comment by wmatthews-google** [comment]
Ah, sorry. I mean https://github.com/bazelbuild/rules_rust/tree/main/crate_universe/src/cli/generate.rs.
Both the "pinned" `Context` --> output files as well as the non-pinned `Context` --> output files flows.

I think I have code working which is backwards compatible with a pinned `Context`, but I'm not confident on testing...

**Comment by illicitonion** [comment]
I believe this go completed in #1710 - was there anything outstanding here?

**Comment by ttiurani** [comment]
I just tested and this is still not working. It's a tricky one where Cargo is able to ignore a specific feature from an unrelated crate in the workspace for WASM building, but bazel / crate-universe can not. 

https://github.com/bazelbuild/rules_rust/issues/1851

**Comment by illicitonion** [comment]
I believe we currently support equivalent behaviour to `resolver = "2"`, by performing the feature resolves ourselves via `cargo tree`.

https://github.com/bazelbuild/rules_rust/issues/2212 suggests our feature resolving work may not be complete for `build-dependencies`, as it depends on the host platform being run on, and we may need to start also setting `--host-triple`, but this should only affect build dependencies.

https://github.com/bazelbuild/rules_rust/issues/1851#issuecomment-1782894547 is quite scary, as it would probably lead to diamond dependency problems.

**Comment by UebelAndre** [comment]
Closing this out in favor of tracking others related issues in their own issues
