### ISSUE TITLE
Cargo Workspaces fails to build because of transitive dependency

### ISSUE THREAD

**Issue by bazaglia** [bazelbuild/rules_rust#1668]
I'm trying to build a project that uses Cargo Workspaces. One of the dependencies has a transitive dependency on [rusty_v8](https://crates.io/crates/v8), that makes my build fail with:

```
error: could not find native static library `rusty_v8`, perhaps an -L flag is missing?
```

My target looks like the following:

```bzl
rust_binary(
    name = "my_rust_app",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    deps = all_crate_deps(),
)
```

The build actually downloads the [librusty_v8_release_x86_64-apple-darwin.a](https://github.com/denoland/rusty_v8/releases/download/v0.44.3/librusty_v8_release_x86_64-apple-darwin.a) file, because I had `--sandbox_default_allow_network=false` in my .bazelrc to prevent non-hermetic actions/tests, and I had to enable the flag for that target since it was failing without being able to download that file. So I know it is trying to download it, but the build still fails with the error above.

There is a closed issue https://github.com/bazelbuild/rules_rust/issues/507 where a workaround is mentioned using `cc_import`, but that points to an external repository that has been deleted. There was no way I could get my build to succeed. I tried to manually download the `librusty_v8_release_x86_64-apple-darwin.a` file (the `.a` for macOS) and create a `cc_import` target for it. But building that target doesn't create any outputs, and providing that in the `deps` to the `rust_binary` file fails the build with the same message above.

**Comment by bazaglia** [comment]
Repo with the fix: https://github.com/bazaglia/rules_rust_apollo_router

**Comment by UebelAndre** [comment]
Users can also checkout that below:

| archive | sha256 |
| --- | --- |
| [rules_rust_apollo_router-c4af9f2967540d70840e8c8b47599b2cbdee0b4e.zip](https://github.com/bazelbuild/rules_rust/files/10098681/rules_rust_apollo_router-c4af9f2967540d70840e8c8b47599b2cbdee0b4e.zip) | 9b22e5d59698fb57c567d92ca2e39406afbd9ee0563b73b3ad5cad0b5fbbd628 |
