### ISSUE TITLE
Setup instructions are incomplete (or broken)

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/rules_rust#167]
I had to add 

```
load("@io_bazel_rules_rust//:workspace.bzl", "bazel_version")

bazel_version(name = "bazel_version")
```
below the call to `rust_repositories()`

It seems either the README needs to be updated or (better) the call to rust_repositories() should do the loading of the `bazel_version(name = "bazel_version")` repo

**Comment by mfarrugi** [comment]
I agree we should have one public `dependencies` function, I will pick this up eventually if no one else does.
