### ISSUE TITLE
Fail to build a dependency have build script relies on C (-sys)

### ISSUE THREAD

**Issue by kwonoj** [bazelbuild/rules_rust#1670]
I'm not sure if this belongs a bug, or more of a misconfiguration requires troubleshooting, probably latter.

The dependecy I'm trying to build is `tikv-jemallocator` (https://github.com/tikv/jemallocator). It have `jemalloc-sys` as transitive depepdency, which is a rust bindings to c library, and to build it uses [`configure` internally](https://github.com/tikv/jemallocator/blob/8b886be1677d1693834b158e76780a793eb3b8db/jemalloc-sys/build.rs#L143) .

This build fine with normal cargo, but when I attempt to build it with bazel it looks like to fail to configure & build correctly. I guess it needs some additional configuration to the crate `jemalloc-sys`. 

Any way to workaround this failure or fix forward? 

Failing log is here: https://github.com/kwonoj/jemalloc-sys-test/actions/runs/3543283371/jobs/5949597347
And minimal repro can be found at https://github.com/kwonoj/jemalloc-sys-test

**Comment by illicitonion** [comment]
In general the approach I'd recommend for Rust depending on C++ from `cargo_build_script` targets is to, where possible, use Bazel to build the C++ in a `cc_library` or with `rules_foreign_cc`, and wiring the `cargo_build_script` up to use that output.

There's an example of doing this for openssl here: https://github.com/bazelbuild/rules_rust/blob/ed32b6de26118eecf207b7d33c8a4fc31848e0e3/examples/crate_universe/WORKSPACE.bazel#L149-L161

It looks like the jemalloc-sys crate allows putting in a pre-built jemalloc by env var: https://github.com/tikv/jemallocator/blob/8b886be1677d1693834b158e76780a793eb3b8db/jemalloc-sys/build.rs#L84-L105

So if you can get jemalloc building with one of the above approaches (it looks like tensorflow did, but removed it: https://github.com/tensorflow/tensorflow/commits/master/third_party/jemalloc.BUILD) that's probably your best bet.

I'm going to close this as not-quite-a-bug, but very happy to continue discussion about it here if you run into issues or need more pointers :)

**Comment by to266** [comment]
I'm not the original author of the issue, but help building the `jemalloc-sys` crate using bazel would indeed be very welcome @illicitonion

**Comment by glindstedt** [comment]
For the jemalloc-sys crate specifically, I got it to work with this build file:
```python
load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make")

filegroup(
    name = "all_srcs",
    srcs = glob(["**"]),
)

# Check here for options used when jemalloc-sys builds it
# https://github.com/tikv/jemallocator/blob/8b886be1677d1693834b158e76780a793eb3b8db/jemalloc-sys/build.rs
configure_make(
    name = "jemalloc",
    autogen = True,
    configure_in_place = True,
    configure_options = [
        "--disable-cxx",
        "--enable-doc=no",
        "--enable-shared=no",
        "--with-jemalloc-prefix=_rjem_",
    ],
    lib_name = "libjemalloc",
    lib_source = ":all_srcs",
    targets = [
        "install_lib_static",
        "install_include",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "gen_dir",
    srcs = [":jemalloc"],
    output_group = "gen_dir",
    visibility = ["//visibility:public"],
)
```

With abbreviated MODULE.bazel, which unfortunately needs a [workaround](https://github.com/bazelbuild/bazel/issues/19301#issuecomment-1925422153) at the moment due to visibility issues when using `bzlmod`:
```python
# ...
http_archive(
    name = "jemalloc",
    build_file = "@//3rdparty:jemalloc.BUILD",
    integrity = "sha256-7290/UXpXuTvf54Z6+Wwdcprf74BQGErKhYauvt+4Xk=",
    strip_prefix = "jemalloc-5.3.0",
    url = "https://github.com/jemalloc/jemalloc/archive/refs/tags/5.3.0.tar.gz",
)
# ...
crate.annotation(
    # https://github.com/bazelbuild/bazel/issues/19301#issuecomment-1925422153
    build_script_data = [
        "@@//:jemalloc_gen_dir",
    ],
    build_script_env = {
        "JEMALLOC_OVERRIDE": "$(execpath @@//:jemalloc_gen_dir)",
    },
    crate = "tikv-jemalloc-sys",
    data = ["@@//:jemalloc"],
    version = "*",
    deps = ["@@//:jemalloc"],
)

```
