### ISSUE TITLE
Docs default to curly quotes (instead of straight quotes) for Attributes sections

### ISSUE THREAD

**Issue by andrewpollack** [bazelbuild/rules_rust#1679]
I'm loving the docs so far, they are super helpful for stepping through `rules_rust` :smile_cat: 

One problem I've ran into involves copy+pasting quoted values in the `Attributes` sections. For example, [`supported_platform_triples` section here](http://bazelbuild.github.io/rules_rust/crate_universe.html#repinning--updating-dependencies). When copy+pasting, the default is to have curly quotes `“”` instead of straight quotes `""`. This creates issues when pasting code to be ran.

Is it possible to switch the rendering of the docs to use straight quotes for these `Attributes` sections? Thank you!

**Comment by illicitonion** [comment]
Thanks for the report!

This is a stardoc / GitHub Pages interaction - I've reported upstream as https://github.com/bazelbuild/stardoc/issues/142 with a proposed fix in https://github.com/bazelbuild/stardoc/pull/143

https://github.com/bazelbuild/rules_rust/pull/1682 pulls in the proposed fix into rules_rust

**Comment by illicitonion** [comment]
I've verified http://bazelbuild.github.io/rules_rust/crate_universe.html#repinning--updating-dependencies now has non-curly quotes - thanks again for the report!

**Comment by andrewpollack** [comment]
Amazing turnaround -- thank you @illicitonion !
