### ISSUE TITLE
Corrupt Cargo.toml generated by crates_vendor rule for the predicates crate

### ISSUE THREAD

**Issue by howardmoore** [bazelbuild/rules_rust#1708]
Using crates_vendor to generate a set of locally vendored crates that includes the [predicates](https://docs.rs/predicates/2.1.4/predicates/) crate results in a corrupt Cargo.toml file that cannot be built. This was found on linux running the 0.15.0 release.

Part of the file looks as follows.
```
[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-header -->"
replace = """
<!-- next-header -->
## [Unreleased] - ReleaseDate
"""
exactly = 1

[[package.metadata.release.pre-release-replacements]]
file = "CHANGELOG.md"
search = "<!-- next-url -->"
replace = """
<!-- next-url -->
[Unreleased]: https://github.com/assert-rs/predicates-rs/compare/{{tag_name}}...HEAD"""
exactly = 1
```
For comparison the actual [Cargo.toml](https://docs.rs/crate/predicates/2.1.4/source/Cargo.toml). It looks like some newlines have been incorrectly added.

**Comment by UebelAndre** [comment]
Can you provide a small repro of this issue?

**Comment by howardmoore** [comment]
Apologies, looking into this further, it isn't the cause of my problem. Running `cargo vendor` generates the same Cargo.toml. I'll close this issue.
