### ISSUE TITLE
How to control LTO

### ISSUE THREAD

**Issue by GregBowyer** [bazelbuild/rules_rust#176]
I am not sure quite what to do here.

I have a tool that is built in rust and uses clang (through clang-sys).

I am greeted to a very aggressive link, as it looks like my linker is doing LTO for all clang

```
[65 / 66] Compiling Rust bin rework_includes (1 files); 3204s linux-sandbox
```

I am not sure what the ideal solution is here, but maybe we need to pass through `linkopts` or have some way to constrain lto?

**Comment by mfarrugi** [comment]
AFAIU lto does not run by default for rust or cc, do you have a particular command line causing the problem? How confident are you this is caused by lto?

**Comment by mfarrugi** [comment]
I have since built some crates with `rustc_flags = ["--codegen=lto",` and it is indeed much slower, but it should be off by default.

**Comment by GregBowyer** [comment]
I am going to call this issue aged out

**Comment by UebelAndre** [comment]
Perhaps https://github.com/bazelbuild/rules_rust/pull/566 would solve for something here?

**Comment by hlopko** [comment]
It is in my queue to document how (and maybe fix things so it's possible) to do ThinLTO across Rust and C++.

**Comment by GregBowyer** [comment]
I am pretty sure there is good LTO here, just this specific issue is old bazel, toolchains and environments as well as deep llvm magics that I think I would struggle to even reproduce today ;)
