### ISSUE TITLE
`rustfmt` no such file or directory when used as data of sh_binary

### ISSUE THREAD

**Issue by gferon** [bazelbuild/rules_rust#1793]
We have a `sh_binary` that has a `data` dependency to `@rules_rust//rust/toolchain:current_rustfmt_toolchain`. After upgrading to `rules_rust` 0.16.1 from 0.14.0, this fails on runtime with a "no such file or directory" error and after checking, the files from `rustfmt` aren't symlinked as part of the `.runfiles` directory of this script.

I'm not sure what could have changed, but any help is appreciated to try and pin point the issue.

**Comment by UebelAndre** [comment]
Can you share what runfiles you have?

**Comment by gferon** [comment]
Well, there's just nothing related to `rustfmt`. `$(execpath @rules_rust//rust/toolchain:current_rustfmt_toolchain)` returns `external/rustfmt_nightly-2022-12-15__x86_64-unknown-linux-gnu_tools/bin/rustfmt` but the `MANIFEST` file doesn't event mention anything of the sort.

**Comment by UebelAndre** [comment]
Can you try the latest commit on main?

**Comment by gferon** [comment]
I just tried and it does work indeed (so #1794 solved this issue). Thanks!
