### ISSUE TITLE
Sync with re-pin for single crate index causes splicing for all of them

### ISSUE THREAD

**Issue by hobofan** [bazelbuild/rules_rust#1797]
(Previous Slack conversation: https://bazelbuild.slack.com/archives/CSV56UT0F/p1674498123988129)

Given that I have multiple cargo workspaces that use `crate_universe`, I'd expect that I can re-pin a single index via the command provided in the documentation (`CARGO_BAZEL_REPIN=true bazel sync --only=myworkspace_index`). However, on the console, I can see that it causes not only the requested workspace to be re-pinned, but that it executes the splicing for all of them. Given that we already have 4 cargo workspaces in our monorepo and splicing for each workspace can take 1-2 minutes, this is slowly becoming a blocker for adding more workspaces.

I can reproduce this issue with this repo that I had already set up: https://github.com/hobofan/rules_rust_multiple_workspaces . In there running either `CARGO_BAZEL_REPIN=true bazel sync --only=workspace1_index` or `CARGO_BAZEL_REPIN=true bazel sync --only=workspace2_index` will cause both workspaces to be spliced.

Some further info:
- Bazel 5.3.0
- macOS 12.5.1

Happy to provide any further information!

**Comment by UebelAndre** [comment]
Ah, I misunderstood the issue. This feels like an issue with `bazel sync`. If the repository rule re-runs it'll do a repin. The quest is to understand exactly what will run when you invoke `bazel sync --only=<anything>`. This is not something I've ever understood. If I sync things early in my workspace, Bazel seems to continue to download things well passed the `--only` point.

Would it be possible for you to consolidate the cargo workspaces? You'd surely see a performance benefit by being able to benefit from de-duplicating dependencies.

**Comment by hobofan** [comment]
> Would it be possible for you to consolidate the cargo workspaces? You'd surely see a performance benefit by being able to benefit from de-duplicating dependencies.

We are already trying to find a good mixture of how many workspaces we have, but there are some things that really feel better modeled as separate workspace (e.g. mostly standalone projects that should be consumable by others but shouldn't cross-polinate and by infected by feature flags). One of the workspaces is also a workaround for https://github.com/bazelbuild/rules_rust/issues/1662 to have a WASM build of the same workspace with some feature flags and dependencies patched out.

Lacking this feature wouldn't be the worst thing in the world, as being able to use `crate_universe` instead of `cargo-raze` has already made the dependency handling a lot smoother. :)

------

As the repository rules seem to respect the `CARGO_BAZEL_REPIN` envvar, I'm wondering if it would make sense to add an additional `CARGO_BAZEL_REPIN_INDEX` (or `CARGO_BAZEL_REPIN_ONLY`) envvar that could be used to specify the indices to repin?

**Comment by UebelAndre** [comment]
> As the repository rules seem to respect the `CARGO_BAZEL_REPIN` envvar, I'm wondering if it would make sense to add an additional `CARGO_BAZEL_REPIN_INDEX` (or `CARGO_BAZEL_REPIN_ONLY`) envvar that could be used to specify the indices to repin?

I think that sounds reasonable. @illicitonion any thoughts?

**Comment by illicitonion** [comment]
Sounds fine to me!

**Comment by UebelAndre** [comment]
@hobofan I’d be happy to review a pull request if you wanted to open one 😄

**Comment by hobofan** [comment]
I'll give it a try :)
