### ISSUE TITLE
Rust toolchain repositories don't warn on missing sha256

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#1825]
Repository rules which use [load_arbitrary_tool](https://github.com/bazelbuild/rules_rust/blob/0.17.0/rust/private/repository_utils.bzl#L679-L706) that don't provide sha256 values currently never inform users about this. This can lead to performance regressions as Bazel is now no longer able to use a cached artifact whenever a download occurs.

This issue happens most commonly when users upgrade the version of `rules_rust` passed the values represented by [known_shas.bzl](https://github.com/bazelbuild/rules_rust/blob/0.17.0/rust/known_shas.bzl) and whenever users introduce the use of a unique platform triple, also not represented by [known_shas.bzl](https://github.com/bazelbuild/rules_rust/blob/0.17.0/rust/known_shas.bzl).

The download wrapper should probably return the sha256 value used and the rules updated to somehow return this in the repository rule to trigger warnings.

**Comment by gferon** [comment]
This would be nice, as it happened to me multiple times (it's easy to forget). As a workaround without refactoring, would you accept a PR for adding a `print()` if `sha256` is `None`?
