### ISSUE TITLE
Crate universe: bug with missing crate_features from adding an unrelated dependency

### ISSUE THREAD

**Issue by ttiurani** [bazelbuild/rules_rust#1850]
I'm migrating from raze to crate universe and I almost got everything to work. The crate universe way of working is so much better, thank you for the awesome work!

I did stumble on a bug though, a reproduction of which can be found here:

https://github.com/ttiurani/rules_rust/tree/main/examples/crate_universe_failure/missing_crate_features

The problem is that without this (totally unrelated) project in the workspace linking to `age`, `crate_features` are correct. After adding `age` to a project in a different crate, two of the three needed `crate_features` disappear, and the compilation fails for the `aead_dep` crate too.

I don't expect this to happen, and Cargo builds this just fine.

What might be the problem?

**Comment by fmorency** [comment]
I stumbled on this bug myself after upgrading from `rules_rust` 0.17.0 to 0.18.0. It looks like a regression since it works fine on 0.17.0.

![2023-02-28_16-16](https://user-images.githubusercontent.com/1102868/221987687-5750d475-8064-47f6-bfb6-ce5ca4e5e6b7.png)

**Comment by UebelAndre** [comment]
This may be a regression from:
- https://github.com/bazelbuild/rules_rust/pull/1710

**Comment by wmatthews-google** [comment]
I can definitely take a look... 
Thanks for the repro & sorry for the regression!

**Comment by gferon** [comment]
Looks like this might fix your problem, can you maybe try it out? https://github.com/bazelbuild/rules_rust/pull/1884

**Comment by ttiurani** [comment]
@gferon Yes, that fixes my issue, in the minimal replication, thanks! (I'm unfortunately unable to test it in my real, because I don't know how to get bootstrapping to work.)

Hopefully your fix can be merged and released soon!

**Comment by ttiurani** [comment]
I verified with 0.19.1 that the problem is gone in my real workspace as well. Thank you!
