### ISSUE TITLE
Make `CrateInfo` provider public

### ISSUE THREAD

**Issue by agluszak** [bazelbuild/rules_rust#1855]
Hi! I work at JetBrains on https://github.com/JetBrains/bazel-bsp/ (@illicitonion  sure remembers what that is ;)) and I'm a mentor for some interns who work on a Rust extension to it and try to integrate it with https://github.com/intellij-rust/intellij-rust. 

We're going to need some info which intellij-rust normally obtains by executing `cargo metadata` and pipe it through BSP. We're still ironing out the details, but for sure for each target we're going to need stuff like edition, enabled features, crate name and some more. 

To get that we need to have access to `CrateInfo` provider (and maybe some other things).

Related: #1578

**Comment by illicitonion** [comment]
Very exciting to hear!! Please let us know what specific things we can do to help when you know them, and we'll see how we can make things work together! :)

**Comment by agluszak** [comment]
*Facepalm*, `CrateInfo` already is public, `BuildInfo` is not. But anyway, thanks for your will to cooperate :)
