### ISSUE TITLE
Add support for Web Assembly

### ISSUE THREAD

**Issue by 0xADD1E** [bazelbuild/rules_rust#186]
The wasm32-unknown-unknown target doesn't really fit in with the current model of physical architectures, but is one of the key selling points for rust to many people

**Comment by mfarrugi** [comment]
What were you trying to do?

I know nothing about wasm. At a glance (reading https://medium.com/@ianjsikes/get-started-with-rust-webassembly-and-webpack-58d28e219635)... getting rustc to emit .wasm shouldn't require too much finagling to the repositories.bzl configurations, but producing something useful requires a bunch of extra steps/tools we would need to teach bazel about as well.

**Comment by 0xADD1E** [comment]
I personally was trying to create a website using yew. For me, the logical division would be rules_rust handling the wasm generation alone, with another set of special rules for taking the place of cargo-web

**Comment by mfarrugi** [comment]
Would that be some rules_wasm, or are there still rust specific things that
need to happen?

**Comment by 0xADD1E** [comment]
In a perfect world, I think this would have rules_rust handling wasm generation alone, and some rules_wasm_shims creating the JS/HTML bindings needed to get a full site from rust sources. That said, wasm-bindgen/cargo-web are highly integrated into the process, and do need access to the source, but also have the ability to generate multiple output files...

**Comment by qzmfranklin** [comment]
@0xADD1E : Agree that the rules_rust should generate .wasm files and leave the rest to other tools and rules.

Looking at the rules_rust repository and the rust-wasm project, I just do not feel that it is ready to start working on it.
