### ISSUE TITLE
Cargo crates generated from git repositories are not reproducible

### ISSUE THREAD

**Issue by cameron-martin** [bazelbuild/rules_rust#1927]
If you have a crate loaded from git in your Cargo.toml, this gets loaded by bazel via git_repository. This leaves the .git directory  [either in the root or in `.tmp_git_root`](https://github.com/bazelbuild/bazel/blob/0d672f3495036ca9e35a8fcd821fd4df6461b7dc/tools/build_defs/repo/git.bzl#L31-L36). The .git directory contains files where the contents is not a function of the input attributes to `git_repository`, so technically this repository rule is not reproducible (see https://github.com/bazelbuild/bazel/issues/18152). Rules_rust [generates globs that depend on these files](https://github.com/bazelbuild/rules_rust/blob/d787525049e4cbaadabb2f531fe86c871a6cf505/examples/crate_universe/vendor_external/crates/BUILD.heck-0.4.0.bazel#L23-L32), making these rules unnecessarily re-run when the repository rule is re-run.

We should probably exclude `.git` from these globs.

**Comment by cameron-martin** [comment]
I've submitted [a PR to bazel](https://github.com/bazelbuild/bazel/pull/18271) that should fix this, although we should probably also exclude `.tmp_git_root` from these globs just to not include unnecesary files. I can't immediately see where these BUILD files are generated though, could somebody point me in the right direction?

**Comment by snowp** [comment]
We've been seeing poor caching related to the use of crate_universe git dependencies - should we expect that the Bazel fix should address this or would we also need the linked PR to change the globs?

**Comment by cameron-martin** [comment]
The Bazel fix will fix it in new versions of Bazel (presumably 7 now), but the fix in rules_rust will fix it for existing versions.
