### ISSUE TITLE
Bump rules_rust

### ISSUE THREAD

**Issue by QuentinPerez** [bazelbuild/rules_rust#1929]
Hi 👋 

 I am currently facing a build issue while using the latest version 0.20 with Linux and Rustix. The error message I am receiving is:
```
error[E0432]: unresolved import `linux_raw_sys::general`
  --> external/crate_index__rustix-0.37.13/src/backend/linux_raw/conv.rs:45:20
   |
45 | use linux_raw_sys::general::__kernel_loff_t;
   |                    ^^^^^^^ could not find `general` in `linux_raw_sys`

```
I have also tried using the master branch and the issue seems to have been fixed. I was wondering if you could please release a new version soon to include this fix?

Thank you 🙏.

**Comment by QuentinPerez** [comment]
It seems that it's another issue, the `cargo-bazel-lock.json` generated by a mac is not the same as linux.

here is the diff,
```diff
      "library_target_name": "linux_raw_sys",
      "common_attrs": {
        "compile_data_glob": [
          "**"
        ],
        +"crate_features": {
        + "common": [
        +  "errno",
        +   "general",
        +   "ioctl",
        +   "no_std"
        +  ],
        +  "selects": {}
        +},
        "edition": "2018",
        "version": "0.3.4"
      },
```

**Comment by UebelAndre** [comment]
https://github.com/bazelbuild/rules_rust/releases/tag/0.23.0 was released!

**Comment by UebelAndre** [comment]
> It seems that it's another issue, the `cargo-bazel-lock.json` generated by a mac is not the same as linux.
> 
> here is the diff,
> 
> ```diff
>       "library_target_name": "linux_raw_sys",
>       "common_attrs": {
>         "compile_data_glob": [
>           "**"
>         ],
>         +"crate_features": {
>         + "common": [
>         +  "errno",
>         +   "general",
>         +   "ioctl",
>         +   "no_std"
>         +  ],
>         +  "selects": {}
>         +},
>         "edition": "2018",
>         "version": "0.3.4"
>       },
> ```

Can you file a separate issue for this?
