### ISSUE TITLE
Windows job failing in CI

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#1965]
https://buildkite.com/bazel/rules-rust-rustlang/builds/8568#0187fca2-d7b3-4f74-8eac-9f214a00a3ac

cc @scentini @meteorcloudy any ideas?

**Comment by meteorcloudy** [comment]
Should be fixed now: https://buildkite.com/bazel/rules-rust-rustlang/builds/8568#018805a0-ce62-46ce-9374-fffbe4706c53

**Comment by UebelAndre** [comment]
That indeed fixed it. Thank you!
