### ISSUE TITLE
Noisy logs from clippy aspect

### ISSUE THREAD

**Issue by robin-wayve** [bazelbuild/rules_rust#1969]
I have no idea whether to point the finger at `rules_rust` or Bazel itself, so please correct me if I should really be raising this against Bazel instead.

After following [the setup instructions for `rust_clippy`](https://bazelbuild.github.io/rules_rust/rust_clippy.html#setup) we get a log like...
```
Aspect @rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //path/to:target up-to-date (nothing to build)
```
on every build/test command, regardless of whether they have any Rust targets involved.

I can [see where it comes from in Bazel's source code](https://github.com/bazelbuild/bazel/blob/release-6.0.0/src/main/java/com/google/devtools/build/lib/buildtool/BuildResultPrinter.java#L202) but I can't figure out where the fault lies on this getting logged so often.

**Comment by UebelAndre** [comment]
This seems like it'd be an issue in Bazel, not `rules_rust`. I don't know of anything in an implementation of an aspect that would log like this.

**Comment by robin-wayve** [comment]
Thanks!
