### ISSUE TITLE
Cant declare inline tests with dependencies

### ISSUE THREAD

**Issue by GregBowyer** [bazelbuild/rules_rust#202]
Sorry if this is already raised

Consider a file like so

```rust
fn some_fn() -> u32 {
    2
}

#[cfg(test)]
mod tests {
    use super::some_fn();
    
    // This following line is not going to work
    use pretty_assertions::assert_eq;
    
    #[test]
    fn test_is_2() {
        assert_eq!(1, some_fn());
    }
}
```

With a build function like so

```python
rust_library(
    name = "example",
    srcs = ["lib.rs"]
)

rust_test(
    name = "example_test",
    deps = [
        ":example",
        "//third_party/rust:pretty_assertion",
    ],
)
```

You will get an error along the lines of 

```
attribute srcs: No lib.rs or example_test.rs source file found.
```

Is there something I am missing?

**Comment by mfarrugi** [comment]
Currently you can only omit sources when deps is exactly 1 crate, otherwise
we can't figure out which depending to build tests for.

**Comment by GregBowyer** [comment]
@mfarrugi I think there are two possible solutions.

One is to allow tests to maybe have a `dev_deps` attribute (see #203).
The other one might be to fiddle about with the notion of `test_only` deps (similar to the `cc_library` rule does).

I think the first is a little more idiomatic to how Rust / Cargo works and is possibly easier for those coming from Cargo to understand, albeit at the cost of being a little none-typical for looking like idiomatic Bazel. With that said language rules can naturally have extensions that are specialised (for instance `crate_type`) so its not impossible to take such an approach.

Thoughts ? ideas?

**Comment by mfarrugi** [comment]
dev_deps looks fine, though I think it might be better to demagic deps with
1 crate (eg. Changing the parameters to (srcs or test_crate) and deps) or
move the dev_deps attribute to the library/binary rules.

I don't see anything about test_only in cc_library, but this seems
reasonable too. I guess the extreme version of this would be a
`cargoish_project` macro that creates a library, binary, test, docs, and
doctest target.

**Comment by bspeice** [comment]
Just got bit by this - for what it's worth, I'd vote having a `dev-deps` in the `rust_library` or `rust_binary` rules since the Cargo `[dev-dependencies]` is [also intended](https://doc.rust-lang.org/rust-by-example/testing/dev_dependencies.html) for use with examples and benchmarks. Happy to take a crack at it if someone can point me where to get started.
