### ISSUE TITLE
Replace SYSROOT env var with --sysroot flag

### ISSUE THREAD

**Issue by daivinhtran** [bazelbuild/rules_rust#2039]
`rust_toolchain` [generates a rust sysroot](https://github.com/bazelbuild/rules_rust/blob/9442aed8ca9e07e024f9daaf06030c968623c9c1/rust/toolchain.bzl#L495) from collection of toolchain components. The sysroot path is then assigned to [`RUST_SYSROOT` make variable](https://github.com/bazelbuild/rules_rust/blob/9442aed8ca9e07e024f9daaf06030c968623c9c1/rust/toolchain.bzl#L545) and [ToolchainInfo.sysroot](https://github.com/bazelbuild/rules_rust/blob/9442aed8ca9e07e024f9daaf06030c968623c9c1/rust/toolchain.bzl#L629). When constructing rustc compile action, we set `ToolchainInfo.sysroot` to [`SYSROOT` env var](https://github.com/bazelbuild/rules_rust/blob/9442aed8ca9e07e024f9daaf06030c968623c9c1/rust/private/rustc.bzl#L1022). 

Apparently, `SYSROOT` env var isn't read by rustc and I suspect it is currently a no-op. To reproduce the no-op of `SYSROOT`, simply change [it](https://github.com/bazelbuild/rules_rust/blob/9442aed8ca9e07e024f9daaf06030c968623c9c1/rust/toolchain.bzl#L545) to any random string and expect the builds to still succeed.

Per [rustc doc](https://doc.rust-lang.org/rustc/command-line-arguments.html#--sysroot-override-the-system-root]), we can set `--sysroot` to override the system sysroot (i.e. `rustc --print sysroot). I believe this is needed to prevent rustc from managing to escape the Bazel sandbox and seeing unspecified inputs.

As a concrete example, say we have a toolchain defined as

```
rust_toolchain(
  name = "foo",
  rustc = "prebuilt/bin/rustc",
  rustc_lib = "sysroot_with_stdlibs", # outside of $WORKSPACE/prebuilt
  rust_std = "stdlibs_built_from_source", # outside of $WORKSPACE/prebuilt
)
```

The system sysroot is
```
$ ~/prebuilt/bin/rustc --print sysroot
~/prebuilt
```

Under `~/prebuilt`, there are prebuilt stdlibs
```
<target-tripple>/
  lib/
    libstd-<hash>.rlib|so
```

So in addition to the system sysroot which always points to prebuilt stdlibs, rustc compile action sets [`-L`](https://doc.rust-lang.org/rustc/command-line-arguments.html#-l-add-a-directory-to-the-library-search-path) to the path of stdlibs built from source. Hence, it fails with
```
error[E0464]: multiple candidates for `rlib` dependency `std` found
 = note: candidate #1 bazel-built libstd-<hash>.rlib
 = note: candidate #1 prebuilt libstd-<hash>.so.  <------- Unspecified in rust_toolchain foo
```

Fortunately, we can fix this by setting `rustc_flags = ["--sysroot=$(RUST_SYSROOT)"]` to the `rust_toolchain`. However, the error with multiple std candidates can be confusing because we don't specify the prebuilt `libstd` in `rust_toolchain` at all. rustc should not be able to escape the Bazel sandbox.

To sort-of fix this issue, one solution is to add `--sysroot` rustc flag to point to the generated sysroot to avoid this issue.

**Comment by UebelAndre** [comment]
I think this would be a great change! Would you be willing to make a pull-request for it where a new build flag is added (`experimental_rustc_sysroot_flag` or something) that can set this flag instead of setting the environment variable?

**Comment by daivinhtran** [comment]
@UebelAndre I'll be more than happy to contribute a PR. I'm not 100% sure but the fix might also remove the need for the custom handling in https://github.com/bazelbuild/rules_rust/pull/1500. I'll verify that.

**Comment by daivinhtran** [comment]
Hi @UebelAndre . I finally got some time to get to this issue now. Please take a look https://github.com/bazelbuild/rules_rust/pull/2223.
