### ISSUE TITLE
Make PR title the commit message for merges

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#2052]
https://github.com/bazelbuild/rules_rust/commit/bf9ddeb7c83a9fe8a7d87c76134cdd8e16131b62 merged with an incorrect commit message. Could an admin of this project update the repo settings to match the following?
<img width="842" alt="image" src="https://github.com/bazelbuild/rules_rust/assets/26427366/cd4f98f7-b675-435f-b681-b086435f4679">

**Comment by UebelAndre** [comment]
cc @scentini @hlopko

**Comment by scentini** [comment]
Done.
