### ISSUE TITLE
Build / Optional Dependency Regression in v0.25.1

### ISSUE THREAD

**Issue by ericmcbride** [bazelbuild/rules_rust#2059]
We currently updated from rules `v0.19` to `v0.25` so we could get the conditional compilation of dependencies based off the architecture platform to work.  While doing that, we noticed that optional dependencies in downstream crates broke.  

I have a small hello world reproduction of this behavior here (We have seen this in the parking_lot crate, and the cucumber crate).  

https://github.com/ericmcbride/bazel-deps-broke

### Steps to Reproduce
1.) In `WORKSPACE.bazel` we have `v0.19` have by default.  If you run `bazel run //test_crate:example` it should compile and will complain about a missing feature file path.     
2.) In `WORKSPACE.bazel` if you change rules rust to the commented out  `urls: v0.25.1` and the coordinated `sha256`, run `CARGO_BAZEL_REPIN=1 bazel sync --only=crate_index`   
3.) `bazel clean --expunge` to bust the local sandbox cache  
4.) then rerun the `bazel run //test_crate::example` command and you will see the following error:  

```
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
error[E0433]: failed to resolve: use of undeclared crate or module `serde`
 --> external/bazel_deps__gherkin-0.13.0/build.rs:6:17
  |
6 | #[derive(Debug, serde::Deserialize)]
  |                 ^^^^^ use of undeclared crate or module `serde`

error: cannot find attribute `serde` in this scope
 --> external/bazel_deps__gherkin-0.13.0/build.rs:7:3
  |
7 | #[serde(rename_all = "camelCase")]
  |   ^^^^^

error[E0277]: the trait bound `Data: serde::de::Deserialize<'_>` is not satisfied
  --> external/bazel_deps__gherkin-0.13.0/build.rs:31:41
   |
31 |     let langs: BTreeMap<String, Data> = serde_json::from_str(&f).unwrap();
   |                                         ^^^^^^^^^^^^^^^^^^^^ the trait `serde::de::Deserialize<'_>` is not implemented for `Data`
   |
   = help: the following other types implement trait `serde::de::Deserialize<'de>`:
             &'a [u8]
             &'a std::path::Path
             &'a str
             ()
             (T0, T1)
             (T0, T1, T2)
             (T0, T1, T2, T3)
             (T0, T1, T2, T3, T4)
           and 129 others
   = note: required for `BTreeMap<std::string::String, Data>` to implement `serde::de::Deserialize<'_>`
note: required by a bound in `serde_json::from_str`
  --> external/bazel_deps__serde_json-1.0.100/src/de.rs:2603:8
   |
   = note: required by this bound in `serde_json::from_str`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0277, E0433.
For more information about an error, try `rustc --explain E0277`.

```

We have also witnessed this behavior with feature flag gated dependencies, in our case, `parking_lot`

While running cargo, everything compiles and works fine.

**Comment by ericmcbride** [comment]
Any update on this?

**Comment by jbmlaird** [comment]
+1 to this. 

Everything works fine when compiling with cargo, but am having to build the entire optional dependency tree for multiple crates in my `WORKSPACE`. I've only just started using `rules_rust` so thought this was a missing feature

**Comment by flyingsilverfin** [comment]
This is the same issue as in https://github.com/bazelbuild/rules_rust/issues/1966
We're also looking forward to a fix :)

**Comment by UebelAndre** [comment]
I’m happy to review a pull request if someone can come up with a fix 😄

**Comment by KoltesDigital** [comment]
Same issue with `gherkin`. To be more accurate, `external/crate_index__gherkin-*/Cargo.toml.orig` contains:

```toml
[dependencies]
serde = { version = "1.0.103", features = ["derive"], optional = true }
...

[build-dependencies]
serde = { version = "1.0", features = ["derive"] }
... (4 other crates)
```

while the generated `BUILD.bazel` contains a `cargo_build_script` where `deps` contains the "4 other crates" but **not** `serde.`

@UebelAndre I'll be happy to submit a PR if you provide some guidance. `cargo metadata` actually states that serde is a build dependency of gherkin. `NodeDep.dep_kinds` isn't assigned anywhere, so I take for granted that it's deserialized and I should check out places which writes `metadata.json` files. Apart from test data, the only such place is `crate_universe/src/cli/splice.rs`. However this seems not to be run! (judging from naive extra `eprintln`, maybe Bazel pipes stderr to a file). Can you please tell me more about the whole process?

**Comment by illicitonion** [comment]
> However this seems not to be run! (judging from naive extra `eprintln`, maybe Bazel pipes stderr to a file). Can you please tell me more about the whole process?

Make sure you set `quiet = False` on your `crate_universe` call in your WORKSPACE file

**Comment by KoltesDigital** [comment]
@illicitonion It wasn't, but it doesn't change anything. I added an `eprintln` just before `write_metadata` near the end of `splice.rs` but it's nowhere to be seen. Here's an extract of terminal output:

```
...
   Compiling git2 v0.16.1
   Compiling crates-index v0.19.13
   Compiling cargo-bazel v0.9.0 (/home/user/.cache/bazel/_bazel_user/80b56b2bd5198fc5c9ac63febd9fb803/external/rules_rust/crate_universe)
    Finished release [optimized] target(s) in 2m 08s
INFO: Analyzed target //rust/features:binary (1 packages loaded, 9 targets configured).
INFO: Found 1 target...
ERROR: /home/user/.cache/bazel/_bazel_user/80b56b2bd5198fc5c9ac63febd9fb803/external/crate_index__gherkin-0.14.0/BUILD.bazel:94:19: Compiling Rust bin gherkin_build_script_ (6 files) [for tool] failed: (Exit 1): process_wrapper failed: error executing command (from target @crate_index__gherkin-0.14.0//:gherkin_build_script_) bazel-out/k8-opt-exec-4AAFB709/bin/external/rules_rust/util/process_wrapper/process_wrapper --arg-file ... (remaining 45 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
error[E0433]: failed to resolve: use of undeclared crate or module `serde`
 --> external/crate_index__gherkin-0.14.0/build.rs:6:17
  |
6 | #[derive(Debug, serde::Deserialize)]
  |                 ^^^^^ use of undeclared crate or module `serde`
...
```

Maybe generations of metadata.json are lightning-fast, but at least it should be written somewhere that the process was launched. Are you sure it is?

FTR here's an extract of WORKSPACE:

```
# TODO http_archive
local_repository(
    name = "rules_rust",
    path = "../rules_rust",
)

load("@rules_rust//rust:repositories.bzl", "rules_rust_dependencies", "rust_register_toolchains")

rules_rust_dependencies()

rust_register_toolchains(
    edition = "2021",
)

load("@rules_rust//crate_universe:repositories.bzl", "crate_universe_dependencies")

crate_universe_dependencies(
    bootstrap = True,
)

load("@rules_rust//crate_universe:defs.bzl", "crates_repository")

crates_repository(
    name = "crate_index",
    cargo_lockfile = "//rust:Cargo.lock",
    generator = "@cargo_bazel_bootstrap//:cargo-bazel",
    lockfile = "//rust:Cargo.bazel.lock",
    manifests = [
        "//rust:Cargo.toml",
        "//rust/features:Cargo.toml",
    ],
    quiet = False,
)

load("@crate_index//:defs.bzl", "crate_repositories")

crate_repositories()
```

**Comment by KoltesDigital** [comment]
@UebelAndre I updated to 0.30.0, ran `bazel clean --expunge`, `bazel sync --only=crate_index`, and `bazel build xyz`, it still fails with the same error message.

**Comment by UebelAndre** [comment]
Don’t you need to repin?

**Comment by flyingsilverfin** [comment]
I believe the fix isn't released yet

**Comment by KoltesDigital** [comment]
Oops I misread the changelog.
