### ISSUE TITLE
crates_repository() doesn't resolve tags to commits when creating the Cargo.Bazel.lock

### ISSUE THREAD

**Issue by gibfahn** [bazelbuild/rules_rust#2073]
When you specify a git tag in your `Cargo.toml`, cargo will resolve it to a commit in the `Cargo.lock`. Bazel on the other hand just specifies the tag in the `Cargo.Bazel.lock`.

This causes:

1. A warning message every time you build
2. Having to fetch the tag every time you build
3. If someone deletes and recreates the tag (bad practice but it happens) then you silently pick up the new commit, so we're not pinning properly.

### Warning

```console
❯ bazel build //...
[...]
Fetching repository @my_project_rust_deps__mydep-1.2.3; Cloning tags/1.2.3 of https://github.com/myorg/mydep.git 10s
[...]
DEBUG: Rule 'my_project_rust_deps__mydep-1.2.3' indicated that a canonical reproducible form can be obtained
       by modifying arguments commit = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" and dropping ["tag"]
DEBUG: Repository my_project_rust_deps__mydep-1.2.3 instantiated at:
  /Users/gib/code/myproj/WORKSPACE:123:31: in <toplevel>
  /private/var/tmp/_bazel_gib/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb/external/my_project_rust_deps/defs.bzl:3928:10: in crate_repositories
  /private/var/tmp/_bazel_gib/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule git_repository defined at:
  /private/var/tmp/_bazel_gib/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb/external/bazel_tools/tools/build_defs/repo/git.bzl:181:33: in <toplevel>
[...]
```

#### `Cargo.toml`

```toml
mydep = { git = "https://github.com/myorg/mydep.git", tag = "1.2.3", features = ["feature-a", "feature-b"] }
```

#### `Cargo.lock`

```toml
source = "git+https://github.com/myorg/mydep.git?tag=1.2.3#aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
```

#### `Cargo.Bazel.lock`

```json
"repository": {
  "Git": {
    "remote": "https://github.com/myorg/mydep.git",
    "commitish": {
      "Tag": "1.2.3"
    }
  }
},
```

#### Generated `defs.bzl`

```python
maybe(
    new_git_repository,
    name = "my_project_rust_deps__mydep-1.2.3",
    tag = "1.2.3",
    init_submodules = True,
    remote = "https://github.com/myorg/mydep.git",
    build_file = Label("//:BUILD.mydep-1.2.3.bazel"),
)
```

**Comment by gibfahn** [comment]
Obvious solutions:

### Fail if the `Cargo.toml` contains a `tag` specifier

This patches the whole, but it means we now have a worse UX than cargo, which is already doing the conversion to a commit (as you can see from the `Cargo.lock` file above).

### Specify the git commit in the `Cargo.Bazel.lock`

Hopefully fairly easy given the information is already directly in the Cargo.lock file.

**Comment by cameron-martin** [comment]
The same thing seems to happen with `branch` too, even if you specify a commit as well in the Cargo.toml.
