### ISSUE TITLE
`data` of proc macros should become compile_data of downstream targets

### ISSUE THREAD

**Issue by dtolnay** [bazelbuild/rules_rust#2074]
The `data` attribute of `rust_proc_macro` (https://bazelbuild.github.io/rules_rust/defs.html#rust_proc_macro-data) is documented as being for files that are _"used by this rule at [...] runtime"_.

"Runtime" for a proc macro occurs during "compile time" of all the other code that invokes those macros. So if crate 𝔸 depends on proc macro **𝔹**, and **𝔹** has `data`, those data need to be available for the macro's code to read during compilation of 𝔸. As far as I could tell by tinkering and skimming the implementation, this is not wired up correctly by rules_rust today.

In the following example arrangement, I believe the correct behavior would be for rules_rust to treat this as if `:main` had been declared with `compile_data = ["data/DATA", "myhelper/DATA"]`.

```starlark
rust_binary(
    name = "main",
    srcs = ["main.rs"],
    proc_macro_deps = [":mymacro"],
)

rust_proc_macro(
    name = "mymacro",
    srcs = ["mymacro/lib.rs"],
    data = ["data/DATA"],
    deps = [":myhelper"],
)

rust_library(
    name = "myhelper",
    srcs = ["myhelper/lib.rs"],
    data = ["myhelper/DATA"],
)
```

I put together a sketch of an implementation here that I think implements the correct semantics: https://github.com/bazelbuild/rules_rust/commit/262387ab39dec01c017ba48d461036081aba8e1d.

I expect this is going to be relevant for solving #2071.

**Comment by UebelAndre** [comment]
This sounds like a good idea!

**Comment by scentini** [comment]
Thanks @dtolnay . I think this is a bug and your solution SGTM. Are you up for converting your implementation to a PR? Alternatively we can look for volunteers to do that.
