### ISSUE TITLE
Libraries not linked by cc_shared_library

### ISSUE THREAD

**Issue by cameron-martin** [bazelbuild/rules_rust#2101]
Since Bazel 6.3.0, the aspect used in `cc_shared_library` only propagates to dependencies that advertise themselves as providing `CcInfo` via the `provides` attribute of the rule constructor. `rust_static_library` does not do this, so these libraries are not linked by `cc_shared_library`.

**Comment by scentini** [comment]
Hey @cameron-martin, you are mentioning `cc_static_library` here; is there a `rules_rust` rule that also suffers from the problem?

**Comment by cameron-martin** [comment]
Sorry it was a typo. I meant `rust_shared_library.`
