### ISSUE TITLE
Automate publishing `cargo-bazel` via github actions

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#2131]
https://crates.io/crates/cargo-bazel was very generously setup by @dtolnay and since then there have been updates folks wanted published there. I'm wondering if we can setup github actions to upload a new release whenever the [crate_universe/version.bzl](https://github.com/bazelbuild/rules_rust/blob/0.26.0/crate_universe/version.bzl) file is updated.

**Comment by UebelAndre** [comment]
@dtolnay do you have any thoughts here? Would this be helpful?

**Comment by dtolnay** [comment]
I forget why I published it. Maybe just preventatively in case a random user ran `cargo publish` in the wrong directory and then went AWOL, forcing you to rename the project if you ever did want to publish it in the future. Obviously I'd be delighted to reassign ownership of the crate to you. I vaguely recall checking your account and you hadn't yet created a crates.io account at the time.

I am not personally using the tool through the published crate -- so far I only use it through `http_archive` of the official rules_rust releases. In terms of use cases, I'd defer to any of the folks who've asked you about getting an update published to crates.io.

**Comment by UebelAndre** [comment]
@scentini since you're an admin, can you add a repository secret `CRATES_TOKEN` that is a crates.io api token for publishing packages?

**Comment by UebelAndre** [comment]
@dtolnay would you be able to grant @scentini access to publish to `cargo-bazel`?

**Comment by dtolnay** [comment]
@scentini needs to register a crates.io account first.

**Comment by illicitonion** [comment]
Can I jump on the owners list? I have a crates.io account :) Thanks!

**Comment by scentini** [comment]
@dtolnay made me an owner of `cargo-bazel`, I added a `CRATES_TOKEN` repository secret. @UebelAndre could you try publishing now?

**Comment by UebelAndre** [comment]
Sweet! https://crates.io/crates/cargo-bazel/0.9.0

Thanks everyone!
