### ISSUE TITLE
Bazel + relative include paths

### ISSUE THREAD

**Issue by martijneken** [bazelbuild/rules_rust#2143]
I have a Rust project that depends on [bumpalo](https://github.com/fitzgen/bumpalo/) via wasm-bindgen (dependency tree below). I'm generating Bazel build files from a Cargo.toml manifest using cargo-raze.

Bumpalo uses include_str() with a relative path to the README: https://github.com/fitzgen/bumpalo/blob/86c63a4a02c52fb79eb8f27fd4d0e5e727cd3116/src/lib.rs#L1

My Cargo builds succeed, but my Bazel builds fail as follows:
```
error: couldn't read external/raze__bumpalo__3_13_0/src/../README.md: No such file or directory (os error 2)
 --> external/raze__bumpalo__3_13_0/src/lib.rs:1:10
  |
1 | #![doc = include_str!("../README.md")]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)
```

Based on some searching, I tried locally patching the bumpalo repo to use CARGO_MANIFEST_DIR, but it didn't work:
```
error: couldn't read <ROOT>/.cache/bazel/_bazel_mstevenson/ec8ecaccd48a2fea3c4104aee5ad7b00/sandbox/linux-sandbox/752/execroot/__main__/external/raze__bumpalo__3_13_0/README.md: No such file or directory (os error 2)
 --> external/raze__bumpalo__3_13_0/src/lib.rs:1:10
  |
1 | #![doc = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/README.md"))]
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Related:
- https://stackoverflow.com/questions/68865499/include-str-set-string-literal-path
- https://groups.google.com/g/bazel-discuss/c/RrubG_YqnDk
- https://github.com/bazelbuild/rules_rust/issues/947

If I take out the two `doc` lines it builds perfectly. What is the right way to fix this?

---
Partial output from `cargo tree`:
```
    └── wasm-bindgen v0.2.87
        ├── cfg-if v1.0.0
        └── wasm-bindgen-macro v0.2.87 (proc-macro)
            ├── quote v1.0.33
            │   └── proc-macro2 v1.0.66
            │       └── unicode-ident v1.0.11
            └── wasm-bindgen-macro-support v0.2.87
                ├── proc-macro2 v1.0.66 (*)
                ├── quote v1.0.33 (*)
                ├── syn v2.0.29
                │   ├── proc-macro2 v1.0.66 (*)
                │   ├── quote v1.0.33 (*)
                │   └── unicode-ident v1.0.11
                ├── wasm-bindgen-backend v0.2.87
                │   ├── bumpalo v3.13.0
                │   ├── log v0.4.20
                │   ├── once_cell v1.18.0
                │   ├── proc-macro2 v1.0.66 (*)
                │   ├── quote v1.0.33 (*)
                │   ├── syn v2.0.29 (*)
                │   └── wasm-bindgen-shared v0.2.87
                └── wasm-bindgen-shared v0.2.87
```

**Comment by UebelAndre** [comment]
`rules_rust` definitely supports uses of `include_str!` I think this bug is specific to [cargo-raze](https://github.com/google/cargo-raze). Perhaps you could try switching to [crates_universe](https://bazelbuild.github.io/rules_rust/crate_universe.html)?

**Comment by martijneken** [comment]
> Perhaps you could try switching to crates_universe?

Thanks for the suggestion! We'll give it a try and report back.

**Comment by martijneken** [comment]
The below works for us, and does not encounter the bug above! FYI @leonm1

```
load("@rules_rust//crate_universe:repositories.bzl", "crate_universe_dependencies")
crate_universe_dependencies(bootstrap = True)

# Regenerate: $ CARGO_BAZEL_REPIN=1 bazelisk sync --only=crate_index
load("@rules_rust//crate_universe:defs.bzl", "crates_repository")
crates_repository(
    name = "crate_index",
    cargo_lockfile = "//:Cargo.lock",
    generator = "@cargo_bazel_bootstrap//:cargo-bazel",
    lockfile = "//:Cargo.Bazel.lock",
    manifests = ["//:Cargo.toml"],
    supported_platform_triples = ["wasm32-wasi"],
)

# Reference: @crate_index//:log (etc)
load("@crate_index//:defs.bzl", "crate_repositories")
crate_repositories()
```

Note: It's quite a bit slower to regen with `CARGO_BAZEL_REPIN=1` rather than `cargo-raze`. I suppose that's because I have `cargo-raze` preinstalled, whereas a REPIN will fetch and compile `cargo-bazel` and all of its dependencies.
