### ISSUE TITLE
v0.27.0 issue — unexpected keyword argument "metadata_files"

### ISSUE THREAD

**Issue by ryanpbrewster** [bazelbuild/rules_rust#2146]
I upgraded a workspace from v0.26.0 to v0.27.0 and got an error:

```
ERROR: /private/var/tmp/_bazel/59027761c515cdd22b50f405ce0ec00f/external/rules_rust_tinyjson/BUILD.bazel:4:37: in rust_library_without_process_wrapper rule @rules_rust_tinyjson//:tinyjson: 
Traceback (most recent call last):
        File "/private/var/tmp/_bazel/59027761c515cdd22b50f405ce0ec00f/external/rules_rust/rust/private/rust.bzl", line 199, column 32, in _rust_library_impl
                return _rust_library_common(ctx, "rlib")
        File "/private/var/tmp/_bazel/59027761c515cdd22b50f405ce0ec00f/external/rules_rust/rust/private/rust.bzl", line 293, column 32, in _rust_library_common
                return rustc_compile_action(
        File "/private/var/tmp/_bazel/59027761c515cdd22b50f405ce0ec00f/external/rules_rust/rust/private/rustc.bzl", line 1417, column 48, in rustc_compile_action
                coverage_common.instrumented_files_info(
Error in instrumented_files_info: instrumented_files_info() got unexpected keyword argument 'metadata_files'
ERROR: /private/var/tmp/_bazel/59027761c515cdd22b50f405ce0ec00f/external/rules_rust_tinyjson/BUILD.bazel:4:37: Analysis of target '@rules_rust_tinyjson//:tinyjson' failed
```

Downgrading back to v0.26.0 fixes the issue. Is it possible that there's been a regression? Or do I need to do something to update my WORKSPACE file?

**Comment by ryanpbrewster** [comment]
Ah, I dug around and saw this PR https://github.com/bazelbuild/rules_rust/pull/2000 which hinted towards
```
--@rules_rust//rust/settings:experimental_use_coverage_metadata_files=false
```
which fixes the issue I'm running into

I have a workaround, but I imagine this will be unexpected for other users. Is there a good way to fix this without explicitly opting out via build settings?

**Comment by UebelAndre** [comment]
There isn't another way to "fix" this without using a flag. The flag exists so users who are updating `rules_rust` but *not* updating Bazel can continue to use the repo as they were before. And at some point in the future, the flag will be removed, thus communicating the newest release of `rules_rust` at that time requires a newer version of Bazel. I can maybe agree flipping the flag was done a bit earlier than needed but I think this is an effective way to provide forward and backward compatibility. Is there another method you would prefer?

**Comment by ryanpbrewster** [comment]
I think an explicit check somewhere that bazel is >= v6.3.0, with an informative error message (like "rules_rust requires bazel to be on at least v6.3.0; if you cannot upgrade, pass in `--@rules_rust//rust/settings:experimental_use_coverage_metadata_files=false` as a flag") would be helpful. This was a fairly mysterious error when I encountered it.

**Comment by ibigbug** [comment]
getting a similar but different error? 

```
Error in instrumented_files_info: private API only for use in builtins
```
