### ISSUE TITLE
Need to add Cargo.toml to compile_data to use proc macros from external crates?

### ISSUE THREAD

**Issue by nanavati** [bazelbuild/rules_rust#2156]
[cargo-toml-bug.tar.gz](https://github.com/bazelbuild/rules_rust/files/12564204/cargo-toml-bug.tar.gz)

I'm using rules_rust with a Cargo workspace and ran into a strange bug when I have a crate that uses a proc macro from an external crate.

When I define the rust_library target for the macro-using crate the way I'd expect (see `cargo-toml-bug/test/BUILD` in the attached tarball) it fails with the following error:

```
ERROR: /home/ravinenator/cargo-toml-bug/test/BUILD:4:13: Compiling Rust rlib test (1 files) failed: (Exit 1): process_wrapper failed: error executing command (from target //test:test) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_rust/util/process_wrapper/process_wrapper --subst 'pwd=${pwd}' -- ... (remaining 20 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
error: could not find root crate for ConstDefault derive: Could not find `Cargo.toml` in manifest dir: `/home/ravinenator/.cache/bazel/_bazel_ravinenator/0a20ff8af59d1be93bab4d8ac215cce7/sandbox/linux-sandbox/47/execroot/__main__/test/Cargo.toml`.
 --> test/src/lib.rs:3:10
  |
3 | #[derive(ConstDefault)]
  |          ^^^^^^^^^^^^
  |
  = note: this error originates in the derive macro `ConstDefault` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error

Target //test:test failed to build
Use --verbose_failures to see the command lines of failed build step
```

I can work around this by adding `compile_data = ["Cargo.toml"]` to the rust_library target, but this feels like a workaround for something the rust rules should be taking care of internally.

**Comment by illicitonion** [comment]
For third-party crates, we automatically add `Cargo.toml` as compile data, but for first-party code we don't assume you have a `Cargo.toml` file at all - many people use rules_rust without `Cargo.toml` files present in their repo. We therefore can't assume one is present.

If you'd like to default to this, I'd recommend defining your own macro in your repo like:

```starlark
load("@rules_rust//rust:defs.bzl", _rust_library = "rust_library")

def rust_library(**kwargs):
    if "compile_data" not in kwargs:
        kwargs["compile_data"] = []
    if "Cargo.toml" not in kwargs["compile_data"]:
        kwargs["compile_data"].append("Cargo.toml")
    _rust_library(**kwargs)
```

And using that instead of the raw rules_rust `rust_library` type in your codebase.
