### ISSUE TITLE
fatal error: 'stdint.h' file not found with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_rust#2207]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3400#018b45b4-c2c2-41de-858e-d02253dab2ba

Platform : MacOS

Logs:
```
ERROR: /Users/buildkite/builds/bk-imacpro-20/bazel-downstream-projects/rules_rust/examples/bindgen/BUILD.bazel:10:21: Generating bindings for bindgen/simple.h.. failed: (Exit 101): bindgen-cli failed: error executing RustBindgen command (from target //bindgen:simple_bindgen__bindgen)
bindgen/simple.h:1:10: fatal error: 'stdint.h' file not found
panicked at external/rules_rust_bindgen__bindgen-cli-0.65.1/main.rs:52:36:
Unable to generate bindings: ClangDiagnostic("bindgen/simple.h:1:10: fatal error: 'stdint.h' file not found\n")

```

Steps:
```
git clone https://github.com/bazelbuild/rules_rust.git
git reset 3a78d01631ea8c2f7b747f6f0e7b4d29c735371d --hard
export USE_BAZEL_VERSION=29985cd45fb843338b312fe0b286553b178fc4c9
cd examples
bazel build  //...
```

CC Greenteam @fweikert

**Comment by sgowroji** [comment]
Hi @UebelAndre, Can you check the above issue? Thanks!

**Comment by Wyverald** [comment]
Culprit finder pins this on https://github.com/bazelbuild/bazel/commit/699e40373f95e42390a85f29dfa1098636336103, which seems to check out as this only fails on macOS.

**Comment by illicitonion** [comment]
The issue here is that `$DEVELOPER_DIR` and `$SDKROOT` are no longer being set for this action.

Investigating how they _should_ be getting set in a new apple_support world...

**Comment by illicitonion** [comment]
https://github.com/bazelbuild/rules_rust/blob/486553fe2945f9f91923675475d5ac0eab0e1735/rust/private/rustc.bzl#L450-L454 isn't returning an `XCODE_VERSION_OVERRIDE` env var, which means the `DarwinSandboxedSpawnRunner` doesn't add the relevant env vars.

AFAICT this feature in apple_support is meant to supply this variable: https://github.com/bazelbuild/apple_support/blob/d87e8b07f3345e750834dbb6ce38c7c7d3b8b44b/crosstool/cc_toolchain_config.bzl#L1403-L1425 but it doesn't seem to be enabled.

**Comment by illicitonion** [comment]
Filed an upstream bug: https://github.com/bazelbuild/bazel/issues/20638
