### ISSUE TITLE
A crate that appears both as a build and a normal dependency is not handled correctly

### ISSUE THREAD

**Issue by ulan** [bazelbuild/rules_rust#2210]
The [wasmtime-runtime](https://github.com/bytecodealliance/wasmtime/tree/main/crates/runtime) depends on [wasmtime-versioned-export-macros](https://github.com/bytecodealliance/wasmtime/tree/main/crates/versioned-export-macros) both as a build and a normal dependency.

Here is an excerpt from `cargo metadata`:
```
          {
            "name": "wasmtime_versioned_export_macros",
            "pkg": "wasmtime-versioned-export-macros 15.0.0 ...",
            "dep_kinds": [
              {
                "kind": null,
                "target": null
              },
              {
                "kind": "build",
                "target": null
              }
            ]
          }
```

The problem is that `wasmtime-versioned-export-macros` appears in the final lock file only in `build_script_attrs` and doesn't appear in `common_attrs`, which leads to a build error:
```
error[E0432]: unresolved import wasmtime_versioned_export_macros
```

I think the bug is in this line:
https://github.com/bazelbuild/rules_rust/blob/cd3e53e9b8555543071ea109218baf41fc4b88f7/crate_universe/src/metadata/dependency.rs#L62

That line should instead be
```
.filter(|dep| is_dev_dependency(dep) || is_normal_dependency(dep))
```

That is because `!is_build_dependency(dep)` is not equivalent to `is_dev_dependency(dep) || is_normal_dependency(dep)` since a dependency can be both a build and a normal dependency.

**Comment by UebelAndre** [comment]
I’d be happy to review a PR 😄

**Comment by ulan** [comment]
@UebelAndre: Do you know approximately when the next version that includes this fix will be released?

**Comment by UebelAndre** [comment]
https://github.com/bazelbuild/rules_rust/releases/tag/0.30.0 should have your change in it. Closing this out since I think that addresses everything, let me know if I missed something!

**Comment by ulan** [comment]
Thanks a lot @UebelAndre!
