### ISSUE TITLE
[crate_universe] Templates in `BUILD` with `crates_vendor`/`crates_repositories`?

### ISSUE THREAD

**Issue by auguwu** [bazelbuild/rules_rust#2233]
This issue presents an issue that I have with a Rust codebase I am working on. I want to allow a constraint to use a different `openssl-sys` package than the pre-compiled one, and it achives using a `config_constraint`, which why I used this patch:

```patch
diff --git a/thirdparty/crates/BUILD.openssl-sys-0.9.93.bazel b/thirdparty/crates/BUILD.openssl-sys-0.9.93.bazel
index b3dfcb6..02349de 100644
--- a/thirdparty/crates/BUILD.openssl-sys-0.9.93.bazel
+++ b/thirdparty/crates/BUILD.openssl-sys-0.9.93.bazel
@@ -30,8 +30,20 @@ rust_library(
         ],
     ),
     crate_root = "src/lib.rs",
+    data = select({
+        "@org_noelware_charted_server//build/settings:nixos": [
+            "@openssl-static//:lib",
+        ],
+        "//conditions:default": [],
+    }),
     edition = "2018",
-    rustc_flags = ["--cap-lints=allow"],
+    rustc_flags = select({
+        "@org_noelware_charted_server//build/settings:nixos": [
+            "-Lexternal/openssl-static/lib",
+            "--cap-lints=allow",
+        ],
+        "//conditions:default": ["--cap-lints=allow"],
+    }),
     tags = [
         "cargo-bazel",
         "crate-name=openssl-sys",
@@ -49,6 +61,14 @@ rust_library(
 cargo_build_script(
     name = "openssl-sys_build_script",
     srcs = glob(["**/*.rs"]),
+    build_script_env = select({
+        "@org_noelware_charted_server//build/settings:nixos": {
+            "OPENSSL_INCLUDE_DIR": "../openssl-static/include",
+            "OPENSSL_LIB_DIR": "../openssl-static/lib",
+            "OPENSSL_STATIC": "1",
+        },
+        "//conditions:default": {},
+    }),
     crate_name = "build_script_main",
     crate_root = "build/main.rs",
     data = glob(
@@ -61,7 +81,13 @@ cargo_build_script(
             "WORKSPACE",
             "WORKSPACE.bazel",
         ],
-    ),
+    ) + select({
+        "@org_noelware_charted_server//build/settings:nixos": [
+            "@openssl-static//:include",
+            "@openssl-static//:lib",
+        ],
+        "//conditions:default": [],
+    }),
     edition = "2018",
     links = "openssl",
     rustc_flags = [
```

Could there be any way to override the `BUILD` contents as a template instead of doing manual patching each time a new release of `openssl`/`openssl-sys` is released?

**Comment by illicitonion** [comment]
If I understand your request correctly, this is what [the `annotations` attribute](https://bazelbuild.github.io/rules_rust/crate_universe.html#crates_repository-annotations) of those rules is for, it lets you customise these attributes of the generated BUILD files: https://bazelbuild.github.io/rules_rust/crate_universe.html#crateannotation - does that meet your needs?

**Comment by auguwu** [comment]
I have tried that but I wanted to insert config flags (like //build/settings:nixos in this case) using a select instead of keeping two versions of itself with or without the flag being available.

**Comment by auguwu** [comment]
My suggestion was to use `crate.annotation` with an `build_file_content_tmpl` attribute

**Comment by illicitonion** [comment]
The annotation allows you to write selects as dictionaries, e.g. you can write:
```starlark
    annotations = { 
        "boring-sys": [
            crate.annotation(
                build_script_env = { 
                    "BORING_BSSL_PATH": "$(execpath @//third_party/rust/boringssl:gen_dir)",
                    "LIBCLANG_PATH": {
                        "x86_64-unknown-linux-gnu": "$(execpath @//tools/build/cc:libclang.so)",
                    },      
                },      
```

This unconditionally sets `BORING_BSSL_PATH` but only sets `BORING_BSSL_PATH` on Linux x86-64.

If the support we currently have doesn't let you be expressive enough in what you can use as keys in this dictionary, I'd happily review a PR to make it more flexible - https://github.com/bazelbuild/rules_rust/pull/2139 should show roughly the areas of code you'd need to touch :)

**Comment by auguwu** [comment]
> The annotation allows you to write selects as dictionaries, e.g. you can write:
> 
> ```python
>     annotations = { 
>         "boring-sys": [
>             crate.annotation(
>                 build_script_env = { 
>                     "BORING_BSSL_PATH": "$(execpath @//third_party/rust/boringssl:gen_dir)",
>                     "LIBCLANG_PATH": {
>                         "x86_64-unknown-linux-gnu": "$(execpath @//tools/build/cc:libclang.so)",
>                     },      
>                 },      
> ```
> 
> This unconditionally sets `BORING_BSSL_PATH` but only sets `BORING_BSSL_PATH` on Linux x86-64.
> 
> If the support we currently have doesn't let you be expressive enough in what you can use as keys in this dictionary, I'd happily review a PR to make it more flexible - #2139 should show roughly the areas of code you'd need to touch :)

That seems like a good compromise for my use-case, yeah! Thanks for the help!~ :3

**Comment by auguwu** [comment]
Using a custom config attribute other than a Rust platform results in:

```python
    build_script_env = selects.with_unmapped({
        "//conditions:default": {},
        selects.NO_MATCHING_PLATFORM_TRIPLES: {
            "DEP_OPENSSL_INCLUDE": "../openssl-static/include",  # @org_noelware_charted_server//build/settings:nixos
        },
    }),
```

and how would I do it with `build_script_data` since that expects a list?

**Comment by illicitonion** [comment]
I suspect what you'd need to do is add the ability to pass-through existing selects as-is. [This code](https://github.com/bazelbuild/rules_rust/blob/d680d8100bfbe7121512d6410bfbe25cc1d0451e/crate_universe/src/utils/starlark/select.rs#L165-L173) (and an equivalent for `SelectDict` take a select-key which isn't known and translate it into `selects.NO_MATCHING_PLATFORM_TRIPLES`. Instead, you'd want to add some logic to do something like: "if original_configuration parses as a label, insert it to the remapped map under the key for that label rather than as unmapped".

**Comment by auguwu** [comment]
I'm sorry for asking this, but can you provide an example? I'm not really too familiar with the Rust code-base for `rules_rust` so I can't really tell what is going on and trying to see what is going on, I can't really wrap my head around it...

**Comment by illicitonion** [comment]
https://github.com/bazelbuild/rules_rust/pull/2239 << when this PR merges, the code you originally wrote should work :)
