### ISSUE TITLE
Optional and unused dependencies that are renamed are pulled

### ISSUE THREAD

**Issue by pamaury** [bazelbuild/rules_rust#2263]
Whenever a crate specified in `Cargo.toml` specifies an optional dependency that is not used but whose name does not match the original name of the crate, rules_rust still generates a dependency on that crate due to an alias. This can cause rules_rust to pull many unneeded dependencies. One such example is `serde_with` with `indexmap`:
```toml
indexmap_1 = {package = "indexmap", version = "1.8", optional = true, default-features = false, features = ["serde-1"]}
```
Even though serde_with does not require this dependency by default, it is still used in the generated BUILD file in aliases (not in the deps):
```python
rust_library(
    name = "serde_with",
    srcs = glob(["**/*.rs"]),
    aliases = {
        "@crate_index__indexmap-1.9.3//:indexmap": "indexmap_1",
    },
   ...
)
```

I have a minimal reproduction of the problem [here](https://github.com/pamaury/bugs/tree/main/rules_rust_bug#optional-and-unused-dependencies-that-are-renamed-are-pulled) using rules_rust 0.30.0.

**Comment by nbdd0121** [comment]
This is likely caused by use of weak feature dependencies, and cargo still have disabled optional dependency that have weak feature dependencies in Cargo.lock file (https://github.com/rust-lang/cargo/issues/10801)
