### ISSUE TITLE
Support local repo relative paths for dependency resolution

### ISSUE THREAD

**Issue by CinchBlue** [bazelbuild/rules_rust#2273]
If i'm not mistaken, the current dependency functions completely ignore relative path dependencies from the `Cargo.toml`. Is this true?

**Comment by ttiurani** [comment]
I stumbled onto this myself just now.

Relative paths used to work with crate universe in older versions of rules_rust, but with the latest version, I just get "failed to load" with "No such file or directory".

This is a big problem for development where you want to temporarily use a local clone of dependencies.

**Comment by sthornington** [comment]
I'm struggling with this, for crates which are part of the dependencies in a `crate_universe` - I need to iterate on the crate as well as the bazel native rust, and I can't figure out how to refer to a local path crate in a way that doesn't break repin splicing.

**Comment by illicitonion** [comment]
Fixed by #3025

There are a few follow-ups coming to fix up a few edge-cases, but this should work now.
