### ISSUE TITLE
deps/rdeps broken in rust_rules using workspace

### ISSUE THREAD

**Issue by rbtcollins** [bazelbuild/rules_rust#2300]
I wanted to see what the deps are for sqlx in Bazel.

```
bazel query 'deps(@crate_index//:sqlx)'efined
```

This fails :

```
`ERROR: Evaluation of query "deps(@crate_index//:sqlx)" failed: preloading transitive closure failed: no such package '@@rules_rust_util_import__quote-1.0.10//': The repository '@@rules_rust_util_import__quote-1.0.10' could not be resolved: Repository '@@rules_rust_util_import__quote-1.0.10' is not defined`
```

That seems to be a reference through [rules_rust](https://github.com/bazelbuild/rules_rust/tree/acb15135fa555fdb92e69e613079eb178090afcf)/[util](https://github.com/bazelbuild/rules_rust/tree/acb15135fa555fdb92e69e613079eb178090afcf/util)/[import](https://github.com/bazelbuild/rules_rust/tree/acb15135fa555fdb92e69e613079eb178090afcf/util/import) - so I'm assuming that there are repo definitions not included in the _dependencies() calls  the docs recommend?

**Comment by aran** [comment]
I see a similar error, but only on Bazel 7. Bazel 6.x unaffected.

**Comment by cab** [comment]
As a workaround, you can add this to your `WORKSPACE`:

```starlark
load("@rules_rust//util/import:deps.bzl", "import_deps")

import_deps()
```

**Comment by krrg** [comment]
Did https://github.com/bazelbuild/rules_rust/pull/2411 fix this?

**Comment by aran** [comment]
> Did #2411 fix this?

Yes, I was able to remove the workaround with 0.38.
