### ISSUE TITLE
Bazel 7.0.0 breaks presubmits

### ISSUE THREAD

**Issue by matts1** [bazelbuild/rules_rust#2317]
See #2316 (an empty PR that  presubmits fail on).

We implicitly use the latest released version of bazel, and that breaks the presubmits. I tried investigating the rustfmt negative fail case, and bazelisk bisect gave some very unclear results. I think it's the version number bump that broke it, because it also fails on [7.0.0-pre.20231011.2](https://github.com/bazelbuild/bazel/releases/tag/7.0.0-pre.20231011.2), but not the commit before the revbump, and the only thing that changed was the version number. I assume there was some flag flip, but I couldn't work out why.

To repro, remove the `rm -rf` in the rustfmt_failure_test.sh, and then you can just cd into the directory. FYI, you'll need to do bazel clean before each invocation, because if you manage to get it to  succeed it'll just cache hit instead.

I think this might be a bug with bazel itself, because the error looks really wierd - the file it claims not to exist does exist, but it's a symlink (though it's still a symlink in 6.4.0, which it works on).

**Comment by matts1** [comment]
FYI, I think the rustdoc failure is caused by the flag flip of `--enable_bzlmod` by default. Didn't dig deeply though because I never got past the other issue

**Comment by illicitonion** [comment]
I worked around this by pinning our CI to Bazel 6.4.0.

I tried and couldn't repro the rustfmt test failure - @matts1 it sounds like you could? Do you have precise repro instructions? What kind of machine were you running on?

The docs test should be fixed just by re-generating the docs when we update to 7.0.0.

**Comment by matts1** [comment]
Found the culprit - bazel is creating broken symlinks in the sandbox environment when the flag `--incompatible_sandbox_hermetic_tmp` is enabled.

**Comment by matts1** [comment]
Ok, I found the root cause. The rustfmt_failure_test writes a workspace to `/tmp/ci-GcVGix7LLp/rules_rust_test_rustfmt`.

When you attempt to `bazel build` in that workspace, it creates `bazel-out` symlinks to the real source files (eg. `/tmp/ci-GcVGix7LLp/rules_rust_test_rustfmt/.../lib.rs`).

According to the documentation of that flag, `If set to true, each Linux sandbox will have its own dedicated empty directory mounted as /tmp rather than sharing /tmp with the host filesystem`. So the sandbox hides the real /tmp, thus breaking the symlink.
