### ISSUE TITLE
Using MacOS client/worker RBE fails to find rustc lib

### ISSUE THREAD

**Issue by adam-singer** [bazelbuild/rules_rust#2331]
Description
========

While using the following remote execution platforms https://github.com/TraceMachina/nativelink and https://github.com/bazelbuild/bazel-buildfarm where clients and workers are running MacOS, when rustc tries to find the rustc libs it will bail with a message signaling unable to find dyld files. 

[Example](https://gist.github.com/adam-singer/454091259e457f9db22a1555491afee1)

```
dyld[74634]: Library not loaded: @rpath/librustc_driver-ba55eb73d0d2fe7a.dylib
  Referenced from: <080C89ED-5CD0-3BBD-963A-99DE33427000> /private/tmp/native_link/data-worker-test/content_path-cas/a6f9972ab9d6efd03fc293adb878ba230450e4577644d0d3dc24310080d668e5-643048
  Reason: tried: '/private/tmp/native_link/data-worker-test/content_path-cas/../lib/librustc_driver-ba55eb73d0d2fe7a.dylib' (no such file), '/private/tmp/native_link/data-worker-test/content_path-cas/../lib/librustc_driver-ba55eb73d0d2fe7a.dylib' (no such file), '/usr/local/lib/librustc_driver-ba55eb73d0d2fe7a.dylib' (no such file), '/usr/lib/librustc_driver-ba55eb73d0d2fe7a.dylib' (no such file, not in dyld cache)
```

Digging deeper it seems that neither sysroot flag/property or passing explicit [`-L` in rustc.bzl](https://github.com/bazelbuild/rules_rust/blob/bf0413086ef22bcbf54093c3377564f89ca65d2f/rust/private/rustc.bzl#L973) does the trick. It does find the standard libraries  located in `lib/rustlib/<arch>-<os>/lib/`, just not the rust core libraries which contain the code needed to run the rust compiler. Have also confirmed that remote worker nodes do have the expected [toolchain file layout](https://gist.github.com/adam-singer/1f4cff04263bba686d9665eec1777f42#file-gistfile0-txt-L31). 

AFAICT this is not a problem when running without RBE, rust seems to find its toolchain core libraries without issue, this only happens in the RBE environments. 

Setup
====

Using the rules_rust/examples as the baseline of what is expected to build with remote execution on MacOS. 

Native link 

https://github.com/TraceMachina/nativelink?tab=readme-ov-file#-building-with-cargo

```
$ cd rules_rust/examples
$ bazel test //...  --remote_instance_name=main   --remote_cache=grpc://127.0.0.1:50051   --remote_executor=grpc://127.0.0.1:50051   --remote_default_exec_properties=cpu_count=1 --verbose_failures --experimental_remote_execution_keepalive --sandbox_debug -s
```

Bazel Buildfarm

https://github.com/bazelbuild/bazel-buildfarm?tab=readme-ov-file#usage

```
$ cd rules_rust/examples
$ bazel test --remote_executor=grpc://localhost:8980 --experimental_remote_execution_keepalive --verbose_failures --sandbox_debug -s -- //...
```

Example Solution
=============

https://github.com/bazelbuild/rules_rust/compare/main...adam-singer:rules_rust:adams-singer/dyld-lib-path has an example solution where exporting to the environment `DYLD_LIBRARY_PATH`. This does solve the problem in a crude way, looking to discuss with rules_rust owners / maintainers on best approach to fixing this issue via supplied patches or change in settings. 

What is also curious is why [toolchain.rustc_lib](https://github.com/bazelbuild/rules_rust/blob/bf0413086ef22bcbf54093c3377564f89ca65d2f/rust/toolchain.bzl#L451) is not used in [rustc.bzl](https://github.com/bazelbuild/rules_rust/blob/bf0413086ef22bcbf54093c3377564f89ca65d2f/rust/private/rustc.bzl), is there any explicit reasons why we wouldn't want to inform the process-wrapper/rustc compiler about the whereabouts of the `rustc_lib`?

**Comment by illicitonion** [comment]
I'm suspicious of paths like `/private/tmp/native_link/data-worker-test/content_path-cas/../lib/librustc_driver-ba55eb73d0d2fe7a.dylib` - I don't know the technologies in use, but what files are actually in `/private/tmp/native_link/data-worker-test/content_path-cas`? Is it a bunch of content-addressed files? If so, my guess is something is resolving symlinks which point at a CAS directory, and either you'll need to stop using symlinks or stop whatever it is from resolving symlinks...

**Comment by adam-singer** [comment]
@illicitonion agree I was also suspicious of that, so tried the same setup on [bazel-buildfarm](https://github.com/bazelbuild/bazel-buildfarm) and error is the same, I think how rustc print it out looks bit misleading. 

https://gist.github.com/adam-singer/ae148c904e74a1969a2cf952beeae2bc#file-gistfile0-txt-L23 

```
dyld[78283]: Library not loaded: @rpath/librustc_driver-ba55eb73d0d2fe7a.dylib
  Referenced from: <080C89ED-5CD0-3BBD-963A-99DE33427000> /private/tmp/worker/cache/a6f9972ab9d6efd03fc293adb878ba230450e4577644d0d3dc24310080d668e5_exec
  Reason: tried: '/private/tmp/worker/cache/../lib/librustc_driver-ba55eb73d0d2fe7a.dylib' (no such file), '/private/tmp/worker/cache/../lib/librustc_driver-ba55eb73d0d2fe7a.dylib' (no such file), '/usr/local/lib/librustc_driver-ba55eb73d0d2fe7a.dylib' (no such file), '/usr/lib/librustc_driver-ba55eb73d0d2fe7a.dylib' (no such file, not in dyld cache)
```
Dumping the environment to stdout and some print statements littered inside seemed to show the toolchain is at the right paths, sysroot seems correct, but rustc doesn't have enough information to pass to the linker on where to discover the rustc libs.

**Comment by illicitonion** [comment]
I can repro this outside of Bazel only when using a symlinking CAS directory.

This script fails as above:

```bash
#!/bin/bash -eu

[[ -e /tmp/rustc-1.74.0-x86_64-apple-darwin.tar.gz ]] || curl --fail -L -o /tmp/rustc-1.74.0-x86_64-apple-darwin.tar.gz https://static.rust-lang.org/dist/rustc-1.74.0-x86_64-apple-darwin.tar.gz

rm -rf original linked tmpcas
mkdir original
(cd original && tar xzf /tmp/rustc-1.74.0-x86_64-apple-darwin.tar.gz)

mkdir tmpcas
for original in $(find original -type f); do
  cas="$(pwd)/tmpcas/$(sha256sum "${original}" | awk '{print $1}')"
  cp "${original}" "${cas}"

  linked="linked/${original#original/}"

  mkdir -p "$(dirname "${linked}")"
  # Remove the -s and things will work.
  ln -s "${cas}" "${linked}"
done

linked/rustc-1.74.0-x86_64-apple-darwin/rustc/bin/rustc --print=cfg --target=x86_64-apple-darwin
```

If you remove the `-s` from the `ln` call to hardlink instead of symlink, things start to work again.

This suggests there's arguably a `dyld` bug around symlink handling (in the case of symlinks, maybe it should add both the resolved and unresolved paths to its search path), but that the resolution here is that rules_rust is not compatible with symlinking CAS implementations due to rustc itself not being compatible with a symlinking CAS.
