### ISSUE TITLE
rand 0.7.0 doesn't build

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/rules_rust#238]
It doesn't look like rules_rust supports the dependency syntax in this crate.

https://github.com/rust-random/rand/blob/84d9be45f082dba41bf3ad22c20eb5e573a3ccaa/Cargo.toml#L59

**Comment by kornholi** [comment]
Builds fine for me with cargo-raze 0.2.9:

```
$ bazel build @third_party__rand__0_7_2//:rand
INFO: Invocation ID: 9a5415b1-a5f1-41e7-b426-164f29d30b77
INFO: Analyzed target @third_party__rand__0_7_2//:rand (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target @third_party__rand__0_7_2//:rand up-to-date:
  bazel-bin/external/third_party__rand__0_7_2/librand--2018866632.rlib
```

**Comment by hlopko** [comment]
Yup I was able to build rand as well, I'll close this issue now assuming its fixed. Please complain if you can still reproduce the failure (and please provide repro instructions and error output).

Thanks!
