### ISSUE TITLE
Building rust_binary for android

### ISSUE THREAD

**Issue by geaden** [bazelbuild/rules_rust#2390]
I have a simple `rust_binary` and `platform` defined like this:

```python
rust_binary(
    name = "hello",
    srcs = ["src/main.rs"],
)

platform(
   name = "android_arm64",
   constraint_values = [
        "@platforms//cpu:arm64",
        "@platforms//os:android",
   ],
)
```

Running

```bash
bazel build :hello --platforms=//:android_arm64
```

results in 

```
 No matching toolchains found for types @@rules_rust//rust:toolchain_type.
```

Exactly the same command with `cc_binary` works fine and I can execute result binary on android phone.

Any clues on how to compile `rust_binary` for android?

I'm using bazel 7.0.0.

Thanks

**Comment by geaden** [comment]
Similar question of stackoverflow https://stackoverflow.com/q/77741832/981937

**Comment by UebelAndre** [comment]
Hopefully it’s helpful but there are some examples for building Android here: https://github.com/bazelbuild/rules_rust/tree/0.36.2/examples/android

**Comment by UebelAndre** [comment]
I see there’s no use of rust_binary in the examples though. I’m not really familiar with Android so that’s all I can do to help :(

Maybe @keith can advise?

**Comment by gferon** [comment]
@geaden did you maybe miss adding `extra_target_triples = ["aarch64-linux-android"]` when declaring the rust toolchain?

If you're using `WORKSPACE` it looks like:

```starlark
rust_register_toolchains(
    edition = RUST_EDITION,
    extra_target_triples = ["aarch64-linux-android"],
    rustfmt_version = RUST_VERSION,
    versions = [RUST_VERSION],
)
```

or with `bzlmod` and `MODULE.bazel` (although I would not recommend it for the time being as `rules_rust` support is being finalized as I write this comment):

```
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(edition = "2021", extra_target_triples = ["aarch64-linux-android"])
```

I was able to build the binary with `bazel build //... --platforms=//:android_arm64`, it should also work for you!

Note: you'll also need to load the Android NDK, but from your error message, it looks like you're already doing that.


My complete `MODULE.bazel` to build a simple `rust_binary` looks like this:

```starlark
module(name = "rules_rust_android_binary")

bazel_dep(name = "rules_rust", version = "0.36.2")
bazel_dep(name = "rules_android_ndk")
git_override(
    module_name = "rules_android_ndk",
    remote = "https://github.com/bazelbuild/rules_android_ndk",
    commit = "877c68ef34c9f3353028bf490d269230c1990483",
)

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(edition = "2021", extra_target_triples = [
    "aarch64-linux-android",
], versions = ["1.75.0"])
use_repo(
    rust,
    "rust_toolchains",
)

register_toolchains("@rust_toolchains//:all")

crate = use_extension(
    "@rules_rust//crate_universe:extension.bzl",
    "crate",
)
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//third-party:Cargo.lock",
    manifests = ["//third-party:Cargo.toml"],
)
use_repo(crate, "crates")
```

**Comment by geaden** [comment]
@gferon Thanks! After adding 

```
extra_target_triples = ["aarch64-linux-android"],
```

it works now! Closing the issue
