### ISSUE TITLE
Bzlmod crate.from_cargo() annotations and packages

### ISSUE THREAD

**Issue by mering** [bazelbuild/rules_rust#2391]
I want to migrate the following from `WORKSPACE` to `MODULE.bazel`:

```
load("@rules_rust//crate_universe:defs.bzl", "crate", "crates_repository")
crates_repository(
    name = "zenohd_deps",
    annotations = {
        "zenoh": [crate.annotation(
            crate_features = ["transport_tcp"],
        )],
        "zenoh-link": [crate.annotation(
            crate_features = ["transport_tcp"],
            deps = ["@zenohd_deps__zenoh-link-tcp-0.7.0-rc//:zenoh_link_tcp"],
        )],
    },
    cargo_lockfile = "//third_party/zenoh:zenohd.Cargo.lock",
    lockfile = "//third_party/zenoh:zenohd.Cargo-bazel.lock",
    manifests = ["@zenohd//:Cargo.toml"],
    packages = {
        "zenoh-link-tcp": crate.spec(
            version = "0.7.0-rc",
        ),
    },
)
```

but I don't see `annotations` or `packages` available. Any idea on how I can migrate this repo?

**Comment by illicitonion** [comment]
The bzlmod-ification of these rules is currently in progress - https://github.com/bazelbuild/rules_rust/pull/2392 adds annotations support, packages is still to come.

I don't know if @matts1 is planning on adding `packages` support, but if not, I'd gladly review a PR that adds support for it, which I imagine would look pretty similar to the annotations PR :)

**Comment by matts1** [comment]
I don't have any intention to add it myself, but If anyone does create a PR, I'd definitely like to review it.

Simplest solution for now would probably to be to manage it via Cargo.toml and Cargo.lock with transient crates once my annotations work is completed (though the features shouldn't need to be an annotation when using Cargo.toml).

**Comment by mmorel-35** [comment]
I'm trying to translate the crates_repository in protobuf to bzlmod but couldn't find the converstion documentation  to proceed 

https://github.com/protocolbuffers/protobuf/blob/fe6edca15b2d80df79ab31117dc49621ef461202/WORKSPACE#L207-L219

I believe that cargo.annotation can help on this but a nice example would help. Now that #2392 is merged, is it possible to address this ?

**Comment by mering** [comment]
@mmorel-35 `packages` is not yet supported: https://github.com/bazelbuild/rules_rust/issues/2391#issuecomment-1876983655

**Comment by dzbarsky** [comment]
https://github.com/bazelbuild/rules_rust/pull/2565

**Comment by dzbarsky** [comment]
@illicitonion @UebelAndre shall we close this issue?

**Comment by UebelAndre** [comment]
> @illicitonion @UebelAndre shall we close this issue?

Seams reasonable, thanks for the ping!
