### ISSUE TITLE
Error in new_executable_binary_provider: Key 'objc' no longer needed in AppleExecutableBinaryInfo.


### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/rules_rust#2401]
CI: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3575#018ce73b-3e56-422e-9c16-9cc95d841d10

Platform: MacOS

 Logs: 
``` ERROR: /Users/buildkite/builds/bk-imacpro-14/bazel-org-repo-root/rules_rust/examples/ios/BUILD.bazel:27:16: in ios_application rule //:ios_app:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_buildkite/39c780fe1ff5114aafdfff786ba27513/external/build_bazel_rules_apple/apple/internal/ios_rules.bzl", line 497, column 52, in _ios_application_impl
		apple_common.new_executable_binary_provider(
Error in new_executable_binary_provider: Key 'objc' no longer needed in AppleExecutableBinaryInfo.```
```

 Steps:
```
git clone https://github.com/bazelbuild/rules_rust.git
git reset df73e91dee261ba91057ac390ebaf9501e6dbfd1 --hard
export USE_BAZEL_VERSION=8e8ddaba0e90c280bfd85644d6ccd91df5b6d353
examples/ios
bazel build //... 
```

Culprit : https://github.com/bazelbuild/bazel/commit/67c5c0fbf99c80aeb17073c79e8017bde443fd4b

 CC Greenteam @fweikert

**Comment by sgowroji** [comment]
CC @UebelAndre , @illicitonion

**Comment by illicitonion** [comment]
This is due to using `rules_apple` - I tried with the latest rules_apple release and saw the same issue.

@keith is there a plan to remove https://github.com/bazelbuild/rules_apple/blob/d5d6d58af8b96365e9b9a9d093d4fb4b2f4dd912/apple/internal/macos_rules.bzl#L441?

**Comment by keith** [comment]
actually fixed in https://github.com/bazelbuild/rules_apple/pull/2356/ but I need to make a release
