### ISSUE TITLE
Bzlmod setup does not use CARGO_BAZEL_URLS for crates universe

### ISSUE THREAD

**Issue by csmulhern** [bazelbuild/rules_rust#2442]
The bzlmod extension appears to rely on `@cargo_bazel_bootstrap` directly, rather than relying on `CARGO_BAZEL_URLS` to skip bootstrapping, as the repository rule does.

See:

https://github.com/bazelbuild/rules_rust/blob/fe610dab73c3c61560a547bc661177dd5115fed7/crate_universe/private/module_extensions/cargo_bazel_bootstrap.bzl#L28

https://github.com/bazelbuild/rules_rust/blob/fe610dab73c3c61560a547bc661177dd5115fed7/crate_universe/private/crates_repository.bzl#L244-L249

**Comment by criemen** [comment]
Is there any progress on this issue? This is preventing us from switching `rules_rust` to `bzlmod` (and in turn, due to complicated dependency issues, blocks our entire project from switching).

**Comment by cameron-martin** [comment]
This should be fixed by #2570.

**Comment by csmulhern** [comment]
Yes, thank you.
