### ISSUE TITLE
MODULE..bazel.lock has ` \"*.bzl\",\n` added to it when it doesnt need it

### ISSUE THREAD

**Issue by flynneva** [bazelbuild/rules_rust#2460]
I've noticed when using bzlmods here sometimes ` \"*.bzl\",\n ` is added to the buildfile contents of some crates when it doesnt need it. If a `.bzl` file doesnt exist for that crate then the build fails since the `glob` cant find a corresponding `.bzl` file.

Removing this ` \"*.bzl\",\n` from the lock file manually fixes the issue....so I'm guessing the template that generates it might need to be udpated to check if .bzl files exist first before adding it to the glob.

Note: I'm using the latest version of this repo 0.38.0 + rust 1.75.0 + Bazel 7.0.2

**Comment by illicitonion** [comment]
Can you share a repo we can reproduce this in?

**Comment by flynneva** [comment]
@illicitonion this is the repo that im seeing the issue in: https://gitlab.com/flynneva/flynn_labs  (its just my personal website).

Anytime I change a version in the Cargo.toml file, run `cargo update` and then run `bazel build //...` it has the issue I describe above.

**Comment by illicitonion** [comment]
That link appears to take me to an auth screen - can you share something public?

**Comment by flynneva** [comment]
@scentini oops! I'm sorry I thought it was public already 😅  it should be now. Let me know if you have any questions!

**Comment by flynneva** [comment]
@illicitonion looks like CI is actually reproducing the error I was seeing locally as well: https://gitlab.com/flynneva/flynn_labs/-/jobs/6200358840 even though the committed lock file I have already removed the extra `*.bzl` string so it _should_ build ok 🤷🏼

**Comment by illicitonion** [comment]
Aha - it looks like you've opted into this here: https://gitlab.com/flynneva/flynn_labs/-/blob/main/.bazelrc?ref_type=heads#L54

I'll send out a PR making crate_universe properly set `allow_empty`, but if you remove that line things should start working for you.

**Comment by illicitonion** [comment]
https://github.com/bazelbuild/rules_rust/pull/2509 should also fix this.
