### ISSUE TITLE
Enable Github merge-queue

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#2494]
@scentini can we get merge-queue support enabled for the repo so we don't need to babysit rebases anymore?

https://github.blog/2023-07-12-github-merge-queue-is-generally-available/

**Comment by scentini** [comment]
Enabled. Trying out in https://github.com/bazelbuild/rules_rust/pull/2493

**Comment by UebelAndre** [comment]
Seems to have worked, thanks!
