### ISSUE TITLE
`cargo-bazel` always recompiling with Bzlmod

### ISSUE THREAD

**Issue by ar3s3ru** [bazelbuild/rules_rust#2531]
After introducing a Rust app on my project using Bzlmod's `rules_rust`, I noticed that the build times have worsened by ~3x.

Further investigation is pointing to `cargo-bazel` always compiling for each `bazel test` or `bazel build`. That seems to be responsible for at least 50% of my build times on Github Actions + Buildbuddy RBE.

**Comment by cameron-martin** [comment]
Does anyone know how the downloading of a prebuilt cargo-bazel works for non-bzlmod builds?

**Comment by cameron-martin** [comment]
Ah so it relies on a build step that modifies a source file to add these URLs and shas (see [here](https://github.com/bazelbuild/rules_rust/blob/5d4dc3f3bf247a2ef0a42ae954444c9e4bc1351a/crate_universe/private/urls.bzl#L1-L13)). Do we have a similar way of modifying the source code before it gets uploaded to BCR?

**Comment by cameron-martin** [comment]
It looks like `crates_repository` calls into [`get_generator`](https://github.com/bazelbuild/rules_rust/blob/5d4dc3f3bf247a2ef0a42ae954444c9e4bc1351a/crate_universe/private/generate_utils.bzl#L19) in the non-bzlmod case, which handles using the precompiled version of cargo-bazel. The bzlmod implementation does not do this, and always uses `cargo-bazel` from `@cargo-bazel-bootstrap`.

**Comment by illicitonion** [comment]
FWIW this is not intended - contributions are welcome to the release process to make bzlmod use the pre-compiled URLs too.

**Comment by cameron-martin** [comment]
Looks like this was fixed by #2570.
