### ISSUE TITLE
gen_rust_project doesn't work with bzlmod

### ISSUE THREAD

**Issue by granaghan** [bazelbuild/rules_rust#2615]
https://github.com/bazelbuild/rules_rust/blob/a58d9524255877e134a99ab7ceeaba1fab363e31/tools/rust_analyzer/lib.rs#L69

The "\~" added to modules causes a failure here when it looks for "rules_rust~/rust/private/rust_analyzer_detect_sysroot.rust_analyzer_toolchain.json" in runfiles. Hacking it up to remove the "~" seemed to fix it.

**Comment by dzbarsky** [comment]
Fixing this depends on https://github.com/bazelbuild/rules_rust/pull/2566. Hardcoding rules_rust is not correct in the face of repo remapping.
