### ISSUE TITLE
Support incompatible_enable_proto_toolchain_resolution

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/rules_rust#2627]
Currently rules_rust requires the user to override the protoc compiler
https://github.com/bazelbuild/rules_rust/blob/df7a6555de52d093183ba03694632fff400c106c/proto/protobuf/toolchain.bzl#L174
with a fixed label to replace it.

However Bazel 7 introduced `--incompatible_enable_proto_toolchain_resolution` and rules_proto 6.0 allows users to register a toolchain for protoc. The `toolchain_type` is `@rules_proto//proto:toolchain_type`: https://github.com/bazelbuild/rules_proto/blob/6.0.0-rc3/proto/BUILD#L57-L60

https://registry.bazel.build/modules/toolchains_protoc is a reference implementation and has [examples](https://github.com/alexeagle/toolchains_protoc/tree/main/examples)

Similar change in other language rules:
- python: https://github.com/bazelbuild/rules_python/pull/1577
- go: https://github.com/bazelbuild/rules_go/issues/3895

**Comment by aran** [comment]
@UebelAndre maybe? Is this something that would be welcome in rules_rust to help avoid protoc compilation times for rust users?

**Comment by illicitonion** [comment]
I would happily review a PR adding this support :)

**Comment by aaylward** [comment]
Is there anything left to do on this after https://github.com/bazelbuild/rules_rust/pull/2741 ?
