### ISSUE TITLE
rust_test does not propagate data files from the crate

### ISSUE THREAD

**Issue by kornholi** [bazelbuild/rules_rust#266]
Data files from the target crate are not collected as part of the test, e.g. with
```bzl
rust_binary(
    name = "foo",
    srcs = ["main.rs"],
    data = ["bar.txt"],
)

rust_test(
    name = "tests",
    crate = ":foo",
)
```

`bar.txt` is not available at either compile or runtime time for the tests.

There are two parts to this:
- `rustc_compile_action` only includes `data` files from the current rule as part of the compilation. Adding a `data = ["bar.txt"]` to the test fixes this as expected.
- `ctx.runfiles(collect_data=True)` does not know about the `crate` attr, and won't use it to collect transitive runfiles. Adding a `deps = [":foo"]` to the test fixes this as expected.

Somewhat related to #222.

**Comment by djmarcin** [comment]
rustc_env is another that does not propagate from rust_library -> rust_test and requires duplication if the env vars affect compilation (e.g. `env!` macros)
