### ISSUE TITLE
Bzlmod has no support for strip_level or opt_level

### ISSUE THREAD

**Issue by chrisstaite-menlo** [bazelbuild/rules_rust#2701]
There's currently no way to pass the strip_level or opt_level to rust_toolchain using Bzlmod.

**Comment by marvin-hansen** [comment]
You can do this with manual compiler option pass through in 3 steps

1) In your root folder BUILD.bazel, add the following entry:

```Starlark
config_setting(
    name = "release",
    values = {
        "compilation_mode": "opt",
    },
)
```

This maps Rusts release mode to Bazel's -c opt.

2) In your binary, add the opt flags & strip settings: 

```Starlark 
# Build binary
rust_binary(
    name = "bin",
    crate_root = "src/main.rs",
    srcs = glob([
        "src/*/*.rs",
        "src/*.rs",
    ]),
    # Compiler optimization
    rustc_flags = select({
       "//:release": [
            "-Clto",
            "-Ccodegen-units=1",
            "-Cpanic=abort",
            "-Copt-level=3",
            "-Cstrip=symbols",
            ],
        "//conditions:default":
        [
           "-Copt-level=0",
        ],
    }),

    deps = [   ],
    visibility = ["//visibility:public"],
)
```

3) Run bazel build with optimization

``bazel build -c opt //...`

Example code:
https://github.com/marvin-hansen/bazel_rust_example

Hope that helps.

**Comment by chrisstaite-menlo** [comment]
Oh, that's great, thank you!

**Comment by marvin-hansen** [comment]
I'm drafting currently the new Bazelmod documentation that should get upstreamed hopefully soon. Do you think this issue can be closed given this will be documented?
