### ISSUE TITLE
rules_rust broken by remapping of the main repository

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/rules_rust#271]
In https://github.com/bazelbuild/bazel/commit/81b57d605de823f8e6f846a06d8e50d9a00041e3, bazel has flipped the flag `--incompatible_remap_main_repo` (https://github.com/bazelbuild/bazel/issues/7130) and thus getting rid of the logical duplication of the main repository that lead to various problems (https://github.com/bazelbuild/bazel/issues/3115, https://github.com/bazelbuild/bazel/issues/7180). This, however, has lead to a breakage of `rules_rust`, see https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1281#51ec78cf-a45e-4c14-9ab3-4f212aeaa2f2; the bazel tracking issue is https://github.com/bazelbuild/bazel/issues/10246.

The relevant error message is `ERROR: While resolving toolchains for target @examples//hello_world_wasm:hello_world_wasm: no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type`. While this might be an error in bazel or in cpp toolchain detection (cc @hlopko) it might also be that `rules_rust` somewhere assumes that the name of its own repository can never be `@`. Givem the complicated definition structure of ` ERROR: While resolving toolchains for target @examples//hello_world_wasm:hello_world_wasm: no matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type` some help from the maintainers of `rules_rust` is needed to either fix `rules_rust` or precisely point to a bug in bazel.

**Comment by m3rcuriel** [comment]
```
INFO: ToolchainResolution:     Toolchain constraint @platforms//cpu:cpu has value @platforms//cpu:x86_64, which does not match value //rust/platform:wasm32 from the target platform @io_bazel_rules_rust//rust/platform:wasm
```

From --toolchain_resolution_debug on Bazel HEAD. Note that with `--noincompatible_remap_main_repo`, it successfully decides this matches.

The build error vanishes with the following patch:

```
diff --git a/rust/private/dummy_cc_toolchain/BUILD b/rust/private/dummy_cc_toolchain/BUILD
index 7e2127d..67af831 100644
--- a/rust/private/dummy_cc_toolchain/BUILD
+++ b/rust/private/dummy_cc_toolchain/BUILD
@@ -7,7 +7,7 @@ dummy_cc_toolchain(name = "dummy_cc_wasm32")
 # TODO(jedmonds@spotify.com): Need to support linking C code to rust code when compiling for wasm32.
 toolchain(
     name = "dummy_cc_wasm32_toolchain",
-    target_compatible_with = ["//rust/platform:wasm32"],
+    target_compatible_with = ["@//rust/platform:wasm32"],
     toolchain = ":dummy_cc_wasm32",
     toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
 )
```

which strongly implies to me this is either a bug in remapping logic or in toolchain resolution (unless I am misunderstanding the remap).

**Comment by aehlig** [comment]
> The build error vanishes with the following patch: [...]

Indeed. As does the following which is in line with the naming conventions in this repository
in general.

```
diff --git a/rust/private/dummy_cc_toolchain/BUILD b/rust/private/dummy_cc_toolchain/BUILD
index 7e2127d..4df7345 100644
--- a/rust/private/dummy_cc_toolchain/BUILD
+++ b/rust/private/dummy_cc_toolchain/BUILD
@@ -7,7 +7,7 @@ dummy_cc_toolchain(name = "dummy_cc_wasm32")
 # TODO(jedmonds@spotify.com): Need to support linking C code to rust code when compiling for wasm32.
 toolchain(
     name = "dummy_cc_wasm32_toolchain",
-    target_compatible_with = ["//rust/platform:wasm32"],
+    target_compatible_with = ["@io_bazel_rules_rust//rust/platform:wasm32"],
     toolchain = ":dummy_cc_wasm32",
     toolchain_type = "@bazel_tools//tools/cpp:toolchain_type",
 )
```

So, while it would be desirable in general that also for tool chains '//' is implicitly
recognised at the repository the definition is in and then consistently renamed, it seems
there is an easy work around by being explicit about the repository referred to.


-- 
Klaus Aehlig
Google Germany GmbH, Erika-Mann-Str. 33, 80636 Muenchen
Registergericht und -nummer: Hamburg, HRB 86891
Sitz der Gesellschaft: Hamburg
Geschaeftsfuehrer: Paul Terence Manicle, Halimah DeLaine Prado

**Comment by laszlocsomor** [comment]
This issue makes `rules_rust` broken on Bazel CI in the `Bazel@HEAD + Downstream` pipeline.
