### ISSUE TITLE
Dependency vendoring broken in 0.49.1

### ISSUE THREAD

**Issue by mortenmj** [bazelbuild/rules_rust#2777]
0.49.0 included https://github.com/bazelbuild/rules_rust/pull/2749 which introduced the error

```
INFO: Running command line: bazel-bin/third-party/rust/crates_vendor.sh

error: failed to parse manifest at `/tmp/.tmpqANJaE/Cargo.toml`

Caused by:
  this virtual manifest specifies a `dependencies` section, which is not allowed

Error: Failed to run cargo tree: exit status: 101
```

this has, seemingly, been fixed in 0.49.1 by https://github.com/bazelbuild/rules_rust/pull/2775, but a new error is introduced instead:

```
INFO: Running command line: bazel-bin/third-party/rust/crates_vendor.sh

    Updating crates.io index
error: no matching package named `cognite_async_closure` found
location searched: registry `crates-io`
required by package `rules_rust_fake_proc_macro_root v0.0.0 (/tmp/.tmpXwBHRP)`

Error: Failed to run cargo tree: exit status: 101
```

where `cognite_async_closure` is an internal crate defined in the same repository.

**Comment by mortenmj** [comment]
cc: @illicitonion

**Comment by illicitonion** [comment]
This was fixed in 0.49.1 - sorry for the issue!

**Comment by illicitonion** [comment]
Oh sorry, I didn't see the second half! Will take a look when I have a moment

**Comment by goniz** [comment]
We're hitting this as well on 0.49.1 !
