### ISSUE TITLE
New wasi targets are invalid

### ISSUE THREAD

**Issue by keithmattix** [bazelbuild/rules_rust#2782]
Rust announced in 1.78 that there are new wasi targets coming to replace wasm32-wasi: https://blog.rust-lang.org/2024/04/09/updates-to-rusts-wasi-targets.html. As of 0.49.1 wasm32-wasip1 is blocked by the triple validation: https://github.com/bazelbuild/rules_rust/blob/0e1297d31e2140c5b97d44cb292f135b64944355/rust/platform/triple.bzl#L24

**Comment by UebelAndre** [comment]
I'd be happy to review a PR that added support for the new targets 😄
