### ISSUE TITLE
Locked In protobuf crate version?

### ISSUE THREAD

**Issue by dayfine** [bazelbuild/rules_rust#288]
Re: the proto rules, I noticed the [Cargo.toml for the raze directory](https://github.com/bazelbuild/rules_rust/blob/master/proto/raze/Cargo.toml) has the `protobuf crate` at version 1.6.0. I wonder if this can be updated at all (the crate is in late 2.x).

Because the `protobuf` crate does control what code is generated, I suppose it would involve some sense of breaking changes. I came here to file this issue because I realized I can not use code in the `protobuf 2.x` crate to work with the generated codes produced by `rust_proto_library` rule, i.e. `protobuf 1.x` crate, as even the trait of `protobuf::Message` has been updated.

Still, I wonder if it would make sense to try to update the crate version here (to allow a `rust_proto_library` rule that works with the `protobuf 2.x` crate)

**Comment by damienmg** [comment]
Hi

There is nothing that prevent rust_proto_library with working with protobuf 2, the reason it is using 1.6.0 was it was developed with it at the time. Could be a good idea to bump it.

**Comment by dfreese** [comment]
@dayfine rust_proto_library been updated to protobuf 2.x

**Comment by dayfine** [comment]
Thanks!
