### ISSUE TITLE
Cannot use `crate.select` inside certain crate.annotations (e.g. build_script_data)

### ISSUE THREAD

**Issue by tshaynik** [bazelbuild/rules_rust#2940]
It seems like `crate.select` can't be used in a variety of `crate.annotation`s, including `build_script_data`.

There is this example in the [rules_rust](https://github.com/bazelbuild/rules_rust/blame/9594fa70b5b6f556a7b4f57ca0ac7c48149bf280/examples/nix_cross_compiling/bazel/cargo/crates/libc.bzl#L6) repo of using the results of a crate.select in a list for rustc_flags, it is out of date. 
To reproduce:
```
  crates_repository(
    name = "rust_crates",
    annotations = {
      "zstd-sys": [ 
                 crate.annotation(
                       build_script_data = crate.select(
                            selects = {
                                    "@rules_rust//rust/platform:myplatform": [
                                           "//:mytarget",
                                ],
                        },
                        common = [],
                    ),
                    build_script_env = crate.select(
                        selects = {
                                "@rules_rust//rust/platform:myplatform": {
                                        "ZSTD_SYS_USE_PKG_CONFIG": "1",
                                },
                        },
                        common = {},
                    ),
                ),
        ],
    })
```
The `build_script_env` annotation works, but the addition of the `crate.select` in `build_script_data` causes the following error. 

```
	File "/home/ubuntu/.bazel-output-cache/0f174b5402e5e096a67deb6762266f43/external/rules_rust/crate_universe/private/crate.bzl", line 188, column 48, in _annotation
		build_script_data = _stringify_list(build_script_data),
	File "/home/ubuntu/.bazel-output-cache/0f174b5402e5e096a67deb6762266f43/external/rules_rust/crate_universe/private/crate.bzl", line 230, column 29, in _stringify_list
		return [str(x) for x in values]
Error: type 'struct' is not iterable
```

The issue seems to be [here](https://github.com/bazelbuild/rules_rust/blob/9594fa70b5b6f556a7b4f57ca0ac7c48149bf280/crate_universe/private/crate.bzl#L191) in the rules_rust codebase. The call to `_stringify_list` in `crate.bzl` breaks on a `crate.build_script_data`, since the result of `crate.select` is a struct.

Is it possible to remove or rework the invocation of `_stringify_list` there, so that the select struct can be passed along?

[Relevant post in Bazel Slack](https://bazelbuild.slack.com/archives/CSV56UT0F/p1727873536250659)

**Comment by nmattia** [comment]
@tshaynik can you see if #2981 fixes the issue for you?
