### ISSUE TITLE
crates_vendor performance regression in 0.51.0

### ISSUE THREAD

**Issue by HackAttack** [bazelbuild/rules_rust#2951]
`crates_vendor.sh` takes about four times as long to run in my project on 0.51.0 as it does in 0.50.1 (12 minutes vs. 3). I haven’t bisected further than that because I don’t recall the trick to running against a source distribution vs. a release archive, but wanted to post the issue in case it’s obvious what the culprit could be (looks like there are only a few changes to this code in the [changelist](https://github.com/bazelbuild/rules_rust/compare/0.50.1...0.51.0)).

**Comment by UebelAndre** [comment]
Howdy! The performance regression came from https://github.com/bazelbuild/rules_rust/pull/2877 but at the time the trade was considered worth it for the improvements to feature detection accuracy. My suggestion to avoid the slow generations is to set [crates_vendor.supported_platform_triples](https://bazelbuild.github.io/rules_rust/crate_universe.html#crates_vendor-supported_platform_triples) to only the host and target platforms you need (which for most folks is a fraction of everything that's being defined). Can you try that and see if things improve?

**Comment by HackAttack** [comment]
Perfect, that works (and it’s actually faster now than it was before)!
