### ISSUE TITLE
make `data` runtime-only to align with ecosystem norms

### ISSUE THREAD

**Issue by ajwerner** [bazelbuild/rules_rust#2977]
In the current rules_rust rules, the `data` attribute is available both at compile time and at runtime whereas the `compile_data` is just available at runtime. There is no attribute that describes runtime-only dependencies. This is unfortunate; changing runtime dependencies shouldn't force a recompilation and relinking of an executable.

In order to align with the rest of the bazel ecosystem, we should change `data` to not be available at compile time. This will be a breaking change, but it's worth it.

**Comment by illicitonion** [comment]
I think this makes sense to do - it was a mistake that we used `data` for both back in the past.

Ideally we should introduce a flag to control this behaviour to make migration easier. Introduce the flag (I don't really mind what default we use), and delete the flag a release or two later when people have had an opportunity to migrate.

Happy to review a PR doing this!

**Comment by dzbarsky** [comment]
I can send a PR but I may not get to it for a few weeks. If anyone else is motivated in the meantime, go for it

**Comment by ajwerner** [comment]
@dzbarsky I got motivated: https://github.com/bazelbuild/rules_rust/pull/3005

**Comment by sthornington** [comment]
The fix for this has broken the build for `cxxbridge-cmd`:

```
error: couldn't read `external/cxxbridge-cmd/src/gen/include/cxx.h`: No such file or directory (os error 2)
 --> external/cxxbridge-cmd/src/gen/include.rs:6:27
  |
6 | pub static HEADER: &str = include_str!("include/cxx.h");
  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `include_str` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 1 previous error
```

Doing the build with `--@rules_rust//rust/settings:incompatible_do_not_include_data_in_compile_data=False` works.  Is this the intended effect of this work, and CXX just needs to be updated, or was this not the intent?

**Comment by illicitonion** [comment]
@sthornington How are you making your `cxxbridge-cmd` targets? It looks like it's not being generated using crates_repository... If you're not sure, `bazel query --output=build //external:cxxbridge-cmd` should output a useful stack trace of calls.

**Comment by sthornington** [comment]
Aha yes, after reviewing the contents of that, I see I was following a recipe from the rules_rust examples which downloaded it via http_archive and generated a BUILD file which passed it as `data`, which having seen the above PR, I changed to `compile_data` and everything worked again! I see now this was changed also in the examples directory as a part of this PR, so all good.

**Comment by sthornington** [comment]
Still a little curious (to me) that it worked in `--spawn-strategy=standalone` but not the default sandboxes.
