### ISSUE TITLE
ci.bazel.io job fails with latest build

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_rust#3]
Due to some problems in rust:
http://ci.bazel.io/job/rules_rust/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/36/console

```
 LD_LIBRARY_PATH=external/rust_linux_x86_64/rustc/lib DYLD_LIBRARY_PATH=external/rust_linux_x86_64/rustc/lib external/rust_linux_x86_64/rustc/bin/rustc examples/fibonacci/benches/fibonacci_bench.rs --crate-name fibonacci_bench_bin --crate-type lib -C opt-level=3 --codegen ar=/usr/bin/ar --codegen linker=/usr/bin/gcc --codegen link-args='\'''\'' -L all=external/rust_linux_x86_64/rust-std-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib --out-dir bazel-out/local-fastbuild/bin/examples/fibonacci --emit=dep-info,link --test -L dependency=bazel-out/local-fastbuild/bin/examples/fibonacci/fibonacci_bench.deps --extern fibonacci=bazel-out/local-fastbuild/bin/examples/fibonacci/fibonacci_bench.deps/libfibonacci.rlib').
examples/fibonacci/benches/fibonacci_bench.rs:15:1: 15:18 error: #[feature] may not be used on the stable release channel
examples/fibonacci/benches/fibonacci_bench.rs:15 #![feature(test)]
```

**Comment by damienmg** [comment]
@davidzchen ping?

**Comment by davidzchen** [comment]
We will need to remove `//examples/fibonacci:fibonacci_bench` from the `bazel test` invocation since benchmark tests use unstable Rust features that are not supported by stable releases.

**Comment by damienmg** [comment]
That is not enough, you also have 2 other tests that fails. Maybe mark them as manual?

**Comment by davidzchen** [comment]
Which other two? The logs only indicate one:

```
Executed 0 out of 10 tests: 9 tests pass and 1 fails to build.
```

The failing test `//examples/fibonacci:fibonacci_bench` is already marked as manual but the CI appears to explicitly specify the test targets. I was not able to find the string "fibonacci_bench" searching in the continuous-integration repository. Where is this configured?

**Comment by damienmg** [comment]
//examples/hello_lib:hello_lib_doc_test                                  PASSED in 0.2s
//examples/fibonacci:fibonacci_doc_test                                  FAILED in 0.2s
  /home/ci/.cache/bazel/_bazel_ci/33aa7a941782d739810f630222db203d/linux-x86_64/bazel-out/local-fastbuild/testlogs/examples/fibonacci/fibonacci_doc_test/test.log

Executed 2 out of 10 tests: 8 tests pass, 1 fails to build and 1 fails locally.


http://ci.bazel.io/job/rules_rust/56/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console

The other two might be flaky

**Comment by damienmg** [comment]
Oh sorry, use the tags "noci" should exclude it.

**Comment by damienmg** [comment]
It's blue now :)

**Comment by davidzchen** [comment]
Thanks!
