### ISSUE TITLE
Multiple proto generation/linking causing compilation issue

### ISSUE THREAD

**Issue by dfreese** [bazelbuild/rules_rust#300]
I've tried to put a minimally reproducible example of the problem I was running into [here](https://github.com/dfreese/rust_bazel_proto_example)

When going from [commit 5c0e90a](https://github.com/bazelbuild/rules_rust/commit/5c0e90a24e9b9e8ab81b183de4d14eb95fb86747) to [commit 7cde1e46](https://github.com/bazelbuild/rules_rust/commit/7cde1e46e9e5a97eb2650ee70a81ec8f9578e3e7), via  #240, I was getting compilation errors, of
```
the trait bound `server::EchoImpl: echo_rust_grpc_proto::Echo` is not satisfied
```
when importing a server implementation from another file that's trying to create a gRPC/protobuf server.  This is using the rust_library, rust_executable, proto_library, and rust_grpc_library rules. 

The compilation between those two different commits seems nearly identical, but in the failing case, the `SUBCOMMAND: # //proto:echo_proto` seems to be run twice, and then linked into the executable twice.

I'm new to rust. Is this something incorrect in that workspace setup, or is something else going wrong?

**Comment by dfreese** [comment]
And I should note that I see this same issue at master as well, the commits are the result of a bisect.

**Comment by fzy1995** [comment]
+1, seeing the same issue when building in bin/ directory using commit 7cde1e46

**Comment by dfreese** [comment]
Following up with this, commenting out [these](https://github.com/bazelbuild/rules_rust/commit/7cde1e46e9e5a97eb2650ee70a81ec8f9578e3e7#diff-9a42a2c125ed40c511198be1665d0faeR346) [two](https://github.com/bazelbuild/rules_rust/commit/7cde1e46e9e5a97eb2650ee70a81ec8f9578e3e7#diff-9a42a2c125ed40c511198be1665d0faeR323-R325) sections in //rust/private/rust.bzl removes the problem.  A similar strategy of commenting out [this section](https://github.com/bazelbuild/rules_rust/blob/master/rust/private/rust.bzl#L336-L338) and [this line](https://github.com/bazelbuild/rules_rust/blob/master/rust/private/rust.bzl#L359) works on master.

**Comment by colinmerkel-th** [comment]
Seems like the same problem described in https://github.com/bazelbuild/rules_rust/pull/294

**Comment by dfreese** [comment]
@colinmerkel-th thanks for pointing that out.  I didn't think to look into PRs.  That's a much cleaner example.
