### ISSUE TITLE
crate_universe patches cannot affect "additive_build_file_contents" sections of Cargo.toml files of external dependencies?

### ISSUE THREAD

**Issue by sthornington** [bazelbuild/rules_rust#3004]
Just want to check my work here -- I'm trying to patch the `Cargo.toml` of https://github.com/dtolnay/cxx so that the `additive_build_file_contents` section generates a `cc_library` section with some additional `copts` in it (specifically, `-fPIC`), to test a theory about why it cannot build properly with clang.

However, nothing I seem to do seems to affect what ends up getting done.  I think that maybe the additive* section is getting added to cargo-bazel-lock before patches are applied or something?  Is that possible?

**Comment by illicitonion** [comment]
How are you patching?

I believe our intention is that setting this explicitly [via annotation](https://bazelbuild.github.io/rules_rust/crate_universe.html#crate.annotation-additive_build_file) should override whatever is in the upstream repo's Cargo.toml file metadata. This is [what we document as the intent](https://github.com/bazelbuild/rules_rust/blob/d9bbb1d57bef05b3a38a08310bd3760a0e413835/crate_universe/src/config.rs#L435-L437), at least, it's possible we have bugs.

**Comment by sthornington** [comment]
Eventually I worked around this issue by adding -fPIC to our bazelrc so no urgency on my end anymore.

But for posterity, I made a patch section in the crates_universe annotations for the cxx dependency to try to add copts = ["-fPIC"] to his additive string literal for the bazel cc_library cxx_cc (or something). 

My patch was being processed sometime, since it complained if it was wrong, but I suspect the original had already been memorialized in the cargo-bazel-lock file, and that that version was what was applied to the generated BUILD file of the dependency.

**Comment by sthornington** [comment]
I just read your links and I understand - instead of doing a literal patch to the cxx Cargo.toml I should have just supplied my own additive_build_file_contents parameter directly in the annotations for cxx. Yes I can see how that would work better, and be easier too.
