### ISSUE TITLE
Clippy Integration

### ISSUE THREAD

**Issue by smklein** [bazelbuild/rules_rust#304]
Hey all, this is more of a feature request than a bug. If discussion would be better served outside a Github issue, lemme know, happy to relocate the conversation.

TL;DR: I have a project depending on rules_rust, and I'd like to be able to use [clippy](https://github.com/rust-lang/rust-clippy) for linting produced libraries, binaries and tests.

It isn't immediately clear what would be the best way to go about doing this integration.

- Given the precedent set by `rust_doc`, would clippy targets be best implemented as a `rust_lint` target, listing all crates as dependencies?
- "clippy-driver" appears to be a non-Cargo mechanism for invoking clippy. Is there a similar target already ya'll would recommend taking a look at for "taking a Cargo command, and running it without Cargo"?

Happy to help contribute here, but I wanted to be oriented correctly before trying anything out :P

**Comment by mfarrugi** [comment]
This is probably most similar to an integration for rust-language-server,
discussed in #71 or an aspect implementation of rustdoc (#152). For clippy
in particular, I think it could also make sense as an optional action
builtin to the crate rules (at the toolchain or crate level).. though I'm
not sure if this is mutually exclusive.

The last time I looked at aspect business was a while ago, and it was bit
complicated.. but the idea is that there is enough information in the
existing crate targets to be able to invoke clippy as an aspect without
adding a bunch of extra `rust_lint` targets (and ostensibly the same would
be possibly for rust_doc etc).

@damienmg I think you know the most about this sort of thing.. any thoughts?

**Comment by damienmg** [comment]
Implementing it as a rule seems to me like a better approach. The rule itself might use some aspect to collect the sources but this does not seems correct for me to call Bazel with a special command-line for doing those clippy test, although this is more a UI question than an implementation one.

**Comment by smklein** [comment]
as of #339 , this is done!
