### ISSUE TITLE
Version 0.55.0 and 0.55.1 is missing from bazel central registry

### ISSUE THREAD

**Issue by ptxmac** [bazelbuild/rules_rust#3061]
the two latest github releases are not present in the central repository: https://registry.bazel.build/modules/rules_rust

**Comment by UebelAndre** [comment]
There are pull-requests pending for this but there are complications publishing the new extension modules

- https://github.com/bazelbuild/bazel-central-registry/pull/3343
- https://github.com/bazelbuild/bazel-central-registry/pull/3331

**Comment by marvin-hansen** [comment]
I tried the latest version (0.55.2) via Git override and encountered an error. Might be something or nothing, but I stick to the previous release for the time being. 

@ptxmac I think its best to wait a few days until BCR publishes an official release.

**Comment by UebelAndre** [comment]
`0.55.0`-`0.55.5` are not going to be added to the bazel-central-registry. But `0.55.6` was (https://github.com/bazelbuild/bazel-central-registry/pull/3399) and future versions should have no problems being added. Closing this out now that that PR has merged.
