### ISSUE TITLE
Transitions assume host platform == platform where bazel is executing

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/rules_rust#327]
This code: https://github.com/bazelbuild/rules_rust/blob/6e5fa2c570ac2f17ac1df840d060fc8aab521a07/rust/private/transitions.bzl#L3

Attempts to transition proc-macros from the target configuration to the host configuration.

Unfortunately, the configuration it transitions _to_ isn't the host configuration (which would be the customisable value of the `--host_platform` flag), but is the platform which Bazel happens to be running on.

I have a set-up where I run Bazel on a Mac, but use a Linux remote execution cluster. I set both the `--platforms` and the `--host_platform` flags to my remote execution platform, because I want all compilations to happen remotely.

Out of the box, if I try to build my code, it tries to invoke a linker locally on my OSX machine, which fails. If I hard-code setting the value of this transition to my host_platform target, it works fine. But this isn't something I can upstream, because it's specific to my execution environment.

Unfortunately, I'm not sure what value this _should_ have. Ideally I think it would be something like `//command_line_option:host_platform`, but that doesn't appear to be supported (I get an error: com.google.devtools.build.lib.packages.BuildFileNotFoundException: no such package 'command_line_option'`).

Is there a meta-value that can be used here for "Whatever the current host platform is"? That's what we should be probably using...

**Comment by damienmg** [comment]
I would guess a select on some configuration values might help. /cc @katre too.

**Comment by katre** [comment]
If you really want a host transition, use `cfg = 'host'` in the attribute declaration. But I want to ask, why specifically the host configuration? I would think you want, instead, the execution configuration, ie using the selected execution platform as the target for the dependency. In that case, you would want to use `cfg = 'exec'`.

**Comment by damienmg** [comment]
@katre  I believe the author just got that part wrong and did not considered the difference between host and execution platform. I think the execution transition should be used there.

**Comment by illicitonion** [comment]
@katre Thanks for the pointer! You're right that `exec` is probably the configuration we want to transition to.

However, with how the code is structured, we need to _conditionally_ transition to the `cfg = "exec"` based on some other attribute of the target, which is why this is hidden behind a full `transition` rather than just a `cfg` value. Is there a way to do that?

**Comment by katre** [comment]
There's not currently a way to do that. We've discussed ways to more fully expose the execution transition, but right now we don't have any plans.

Why do you need to conditionally transition? What things would make that decision? One option is to have two attributes, one for each possible transition, and choose between them in the rule implementation, but this obviously causes extra dependency edges and wasted analysis work (although, if the outputs aren't used, they won't actually be build).

**Comment by illicitonion** [comment]
Thanks for the information, that's really useful to know :)

(Caveat: I'm a newcomer to these rules, so don't have much context or history).

The way the rules are structured right now, everything is a `rust_library`, and libraries which are entry-points to code generators (and similar) which should be complied in the `exec` cfg have an attribute `crate-type = "proc-macro"` set. From the sounds of things, we may need to restructure that so that these code generators are their own `rule` type, rather than sharing a `rule` type with other libraries, so that we can unconditionally transition them?

That shouldn't be too hard to do implementation-wise, but is a non-trivial change API-wise. @damienmg @acmcarther @davidzchen how would y'all fee about introducing a top-level `rust_proc_macro_library` `rule` instead of `rust_library(crate_type = "proc-macro")`?

**Comment by damienmg** [comment]
David is no longer working on those rules. @dfreese update that code last. Also pulling @mfarrugi .

rust_proc_macro_library sounds reasonable to me but I am generally not a big fan of have lots of different rules so that's not a clear cut. Let's hear the others.

**Comment by dfreese** [comment]
Taking a look at it, pretty much all mentions of "host" should probably be replaced with "exec".  I didn't see one that stuck out as actually needing to be "host".  Thanks for pointing this out @illicitonion.

I wouldn't be opposed to rust_proc_macro_library necessarily.  It does remove some of the symmetry between these rules and cargo, though, since [crate_type](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-crate-type-field) can be proc-macro there.

On the other hand crate_type there can also be "bin", and we special case that into rust_binary, so that might not be an incredibly strong argument.

A nice perk of getting rid of the transition would be simplifying some of the paths in the bazel-out directory.

If we could:
 1. Fix references to "host" that should be "exec"
 2. Add the rust_proc_macro_library rule
 3. Add support for it in cargo raze
 4. Deprecate crate_type = "proc-macro"
 5. Remove support for proc-macro in rust_library and the transition

I'd be okay with it.  I'm not sure reasonable step 5 is, though.

FYI: @smklein

**Comment by illicitonion** [comment]
Unfortunately we'd still need _a_ transition, it would just be an unconditional one rather than a conditional one, so I suspect we wouldn't get the simplification of bazel-out...

**Comment by illicitonion** [comment]
Actually, looking at implementation here, it's not a `rust_proc_macro_library` we need, it's that dependencies which are proc_macros need to be in their own attribute. i.e.

```python
rust_library(
    name = "mine",
    deps = ["//cargo:clap"],
    proc_macro_deps = ["//serde:derive"],
)
```

Because as @katre described above, the transition needs to be on the edge, not the target being depended on.

I will give implementing this a go and see how gnarly it ends up looking :)
