### ISSUE TITLE
rust_library should produce non-rlib crates with correct file extensions

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/rules_rust#36]
Currently, the `rust_library` rule only outputs rlibs regardless of the value of `crate_type`. In order to correctly support all the different [crate types](https://doc.rust-lang.org/reference.html#linkage), `rust_library should produce the crates with the correct file extensions.

### Proposal

* Make the `rust_library` **rule** internal by renaming it to `_rust_library`
* Add a new `outs` attribute to the `_rust_library` rule to support [custom outputs](https://bazel.build/versions/master/docs/skylark/cookbook.html#outputs-custom)
* Add a `rust_library` macro that wraps the `_rust_library` rule. Based on the value of `crate_type`, it adds a `_rust_library` rule with `outs` set with the name of the output library with the correct file extensions according to the [Rust documentation](https://doc.rust-lang.org/reference.html#linkage)

**Comment by davidzchen** [comment]
+cc @dslomov @laurentlb @acmcarther @mattmoor @damienmg

**Comment by damienmg** [comment]
SGTM

**Comment by acmcarther** [comment]
This was fixed in:
https://github.com/bazelbuild/rules_rust/pull/38

... which produces outputs with the right file extension for the toolchain and crate_type.
