### ISSUE TITLE
Support generating rust-analyzer rust-project.json

### ISSUE THREAD

**Issue by aignas** [bazelbuild/rules_rust#378]
A duplicate of https://github.com/google/cargo-raze/issues/186.

Rust-analyzer supports non-cargo based projects.

It would be interesting to do the generation of the `rust-project.json` at the root of the repository, such that `rust-analyzer` could refer to dependencies managed by bazel and refer to the toolchain managed by `rules_rust`.

Raising the request here as well to raise awareness and as suggested on cargo-raze issue tracker by @GregBowyer , this project may be a better fit.

> Humm interesting, this might be better on rules_rust as a target or aspect

Docs: https://rust-analyzer.github.io/manual.html#non-cargo-based-projects

**Comment by benbrittain** [comment]
This is actually really well timed :laughing: I started playing around with generating this for Bazel last night. I should have a shareable prototype soon.

(I implemented support for rust-project.json in GN (chrome's build system) already, so I'm somewhat familiar with it)

**Comment by m3rcuriel** [comment]
Ok @benbrittain I'll leave it to you haha. Let me know if you need any help or want someone to to test it out.

Side note do you know if it is impossible to support multiple crates in the same folder in rust-analyzer? I don’t think it should be impossible but it might require upstream changes.

**Comment by benbrittain** [comment]
you can indeed support multiple crates in the same folder! All that logic is derived from the `crate_root`

I'll wrap up the first pass of this tonight. Testing will definitely be appreciated

**Comment by benbrittain** [comment]
I came upon an impasse while trying to finish off the sysroot information. rust-analyzer needs the source files for the stdlib to properly do analysis. The vendored rust seems to only have rlibs, not the actual source files. 

Any recommendations?

**Comment by benbrittain** [comment]
context for how we solved this with GN:
https://gn.googlesource.com/gn/+/a3b7eb088362eae99f396717930c1f0bf61a19a2/src/gn/rust_project_writer.cc#165

**Comment by mfarrugi** [comment]
Grabbing a rustup component (in this case rust-src) maps roughly to load_arbitrary_tool https://github.com/bazelbuild/rules_rust/blob/8f31b7bc26acdfd11fb046337073840ce50eaeab/rust/repositories.bzl#L390

eg. you want to grab https://static.rust-lang.org/dist/rustc-1.45.0-src.tar.gz

**Comment by benbrittain** [comment]
That information was very helpful @mfarrugi! Thank you :D

**Comment by UebelAndre** [comment]
I believe this can be closed now that https://github.com/bazelbuild/rules_rust/pull/505 is merged.

**Comment by hlopko** [comment]
I agree. Please complain if you don't :)
