### ISSUE TITLE
Custom proto toolchain ignored

### ISSUE THREAD

**Issue by epigramengineer** [bazelbuild/rules_rust#395]
I'm trying to write a [custom protobuf toolchain](https://bazelbuild.github.io/rules_rust/rust_proto.html#rust_proto_toolchain) to use [prost](https://crates.io/crates/prost) instead of [grpc-rust](https://crates.io/crates/grpc).

I've followed the [guide](https://github.com/bazelbuild/rules_rust/blob/master/proto/README.md#customizing-dependencies) and it seems like this should work:

``` # src/BUILD
load("@io_bazel_rules_rust//proto:toolchain.bzl", "rust_proto_toolchain")
rust_proto_toolchain(
    name = "proto-toolchain-impl",
    protoc = "@com_google_protobuf//:protoc",
    grpc_plugin = "//3rdparty/cargo:prost",
    proto_plugin = "//3rdparty/cargo:prost",
)
toolchain(
    name = "proto-toolchain",
    toolchain = ":proto-toolchain-impl",
    toolchain_type = "@io_bazel_rules_rust//proto:toolchain",
)
```

```
# WORKSPACE
register_toolchains("//src:proto-toolchain")
```

but building my rust_proto_library produces the same binary output as without the toolchain definition; it doesn't even error or produce a message. Is there a step I'm missing?

```
proto_library(
    name = "echo_pb",
    srcs = ["echo.proto"]
)

rust_proto_library(
    name = "echo_pb_rs",
    deps = [":echo_pb"],
)
```

**Comment by damienmg** [comment]
Hi you also needs to remove the rust_proto_repositories() call from you workspace file.

**Comment by epigramengineer** [comment]
Thanks!

**Comment by rdelfin** [comment]
@epigramengineer do you happen to have a sample repo with this issue resolved around? I'm trying to do the exact same thing and I can't get it to work (due to dependency and other issues)
