### ISSUE TITLE
Add rust_plugin rule to support Rust compiler plugins

### ISSUE THREAD

**Issue by davidzchen** [bazelbuild/rules_rust#40]
Add support for using Rust [compiler plugins](https://doc.rust-lang.org/book/compiler-plugins.html).

Because plugins are an unstable feature, #14 would also make this easier to use for developers.

**Comment by acmcarther** [comment]
Does this issue also track proc-macro dependencies? Those have been stabilized (as of 1.15 IIRC). 

Based off of `rustc --version` and https://github.com/rust-lang/rfcs/blob/master/text/1566-proc-macros.md, I think they're basically just another kind of rust_library, and can be specified with `--crate-type`. We'll need special handling if one of these is received as a dependency though.

**Comment by acmcarther** [comment]
Update on this: 

This is actually supported trivially, and rustc links these identically to any other kind of dependency. Support for general crate types (https://github.com/bazelbuild/rules_rust/pull/38 extended with "proc-macro" mapping to rlib, blocked on me), is all that is necessary.

**Comment by acmcarther** [comment]
This issue is obsolete:

As detailed in the prior comment, no special rule variant is required to support compiler plugins -- just a crate type. Likewise, compiler plugins can be included directly as normal dependencies and used (e.g. for custom derive).
