### ISSUE TITLE
Dependency crate trying to run `pkg-config` during build?

### ISSUE THREAD

**Issue by epigramengineer** [bazelbuild/rules_rust#401]
It looks like I'm trying to depend on a crate which is trying to call pkg-config during it's build phase, and I'm unsure how to navigate that with rules_rust. Is this something that rules_rust can support? Do I need to provide that in some sort of toolchain (and the thing it's looking for; alsa)?

```
amethyst = "=0.15.3"
```

```
rust_binary(
    name = "hello",
    srcs = ["hello.rs"],
    deps = [
        "//3rdparty/cargo:amethyst",
    ],
)
```

```
ERROR: ~/projects/core/3rdparty/cargo/vendor/alsa-sys-0.1.2/BUILD:31:19: CargoBuildScriptRun 3rdparty/cargo/vendor/alsa-sys-0.1.2/alsa_sys_build_script.out_dir failed (Exit 1) cargo_build_script_runner failed: error executing command bazel-out/host/bin/external/io_bazel_rules_rust/cargo/cargo_build_script_runner/cargo_build_script_runner bazel-out/host/bin/3rdparty/cargo/vendor/alsa-sys-0.1.2/alsa_sys_build_script_script_ alsa-sys ... (remaining 5 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"alsa\"`: No such file or directory (os error 2)"', src/libcore/result.rs:1188:5
```

**Comment by UebelAndre** [comment]
Can you also share your `Cargo.toml` file? I'm assuming you're using `cargo raze` to generate `//3rdparty/cargo:amathyst` and there's likely some settings you apply to avoid this error.

**Comment by epigramengineer** [comment]
I'm new to rust in general so not sure what I'm looking for, but the only seemingly related setting would be `default_gen_buildrs`? What else would I be looking for and how should I diagnose similar problems in the future?

```
# To Regenerate the dependencies in bazel:
# cd 3rdparty/cargo && cargo generate-lockfile && cargo vendor --versioned-dirs --locked && cargo raze && cd  

[package]
name = "compile_with_bazel"
version = "0.0.0"

# Mandatory (or Cargo tooling is unhappy)
[lib]
path = "fake_lib.rs"

[dependencies]
amethyst = "=0.15.3"
ggez = "=0.5.1"
piston = "=0.52.0"
piston-shaders = "=0.3.1"
piston_window = "=0.112.0"
prost = "=0.6.1"
prost-types = "=0.6.1"
tokio = { version = "=0.2.22", features = ["macros"] }
tonic = "=0.3.0"

[raze]
# The WORKSPACE relative path to the Cargo.toml working directory.
workspace_path = "//3rdparty/cargo"
default_gen_buildrs = true

# The target to generate BUILD rules for.
target = "x86_64-unknown-linux-gnu"
```

**Comment by epigramengineer** [comment]
Do you have a recommendation on how to go about finding the libraries that need specific flags or `gen_buildrs = true`? Looking at https://github.com/google/cargo-raze/issues/41 it seems like they're recommending setting `default_gen_buildrs = true`

**Comment by UebelAndre** [comment]
I unfortunately don't have a great recommendation. I've had success in leaving `default_gen_buildrs` set to false and figuring out what library was producing issues. In most cases you'll probably wanna go read the `build.rs` file for the problem library and try to understand if it's `build.rs` is hermetic and makes sense to run with Bazel. Then either enable `gen_buildrs` or set the required feature flags.

**Comment by epigramengineer** [comment]
Thanks for the help and advice. I think this more belongs in cargo raze.
