### ISSUE TITLE
Run individual tests

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#417]
Is there a way to run individual tests within a `rust_test` target?

For example, the equivalent Cargo command to test `planning::tests::test_plan_build_minimum_workspace` would look like:
```command
 cargo test --package cargo-raze --lib -- planning::tests::test_plan_build_minimum_workspace
```

And the matching Bazel command would look like:
```command
bazel test //impl:cargo_raze_tests --test_arg planning::tests::test_plan_build_minimum_workspace
```

**Comment by mfarrugi** [comment]
I don't think bazel test propagates args, but I know `bazel run` does.

**Comment by UebelAndre** [comment]
You can use `--test_arg`. I'll update the description.
https://docs.bazel.build/versions/master/user-manual.html#flag--test_arg

**Comment by UebelAndre** [comment]
This is still an unanswered question. I think the earlier comments made that a bit unclear.

**Comment by UebelAndre** [comment]
Turns out this **was** possible using the `--test_arg` attribute. I've opened https://github.com/bazelbuild/rules_rust/pull/1098 to address this by documenting the functionality.
