### ISSUE TITLE
Feature Request: Dark theme for docs

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#470]
Would be greatly appreciated. Is this possible with stardoc?

**Comment by dfreese** [comment]
I imagine it's possible, because there's a CSS file included with the generated docs.  Open to changing it, or making it optional, if someone figures out how.

**Comment by UebelAndre** [comment]
How does one build and render docs locally?

**Comment by UebelAndre** [comment]
It would be awesome if someone could add a script similar to `docs/update_docs.sh` for rendering the docs locally.

**Comment by UebelAndre** [comment]
Pinging this again. After some reflection, I feel it'd be better to update these docs to match the official Bazel docs theme to be more consistent with the tool. I opened https://github.com/bazelbuild/rules_nodejs/issues/2105 some time ago and think the way the docs are now is WAY better. I'd love to see the same effort put into the rust docs.

**Comment by UebelAndre** [comment]
I suspect that CSV file is unused
