### ISSUE TITLE
Protobuf rules using Tonic

### ISSUE THREAD

**Issue by tvolk131** [bazelbuild/rules_rust#478]
I'm looking into porting one of my Rust projects over to Bazel. It uses Protobuf/gRPC, however it is built on [Tonic](https://crates.io/crates/tonic) rather than stepancheg's Protobuf/gRPC libraries which are used in the existing proto rules. I've used both and I personally much prefer Tonic, as it generates cleaner and simpler Protobuf objects, the gRPC stubs use async/await, and the whole library is an integrated part of the [Tokio stack](https://tokio.rs/#tk-lib-tonic). It'd be really nice to have separate rules for Tonic. Something like `rust_tonic_library`.

**Comment by dfreese** [comment]
I put up an very WIP attempt to integrate what my team uses into rules_rust here:  https://github.com/bazelbuild/rules_rust/pull/479

I, unfortunately haven't had the time to knock out the details on that.

**Comment by UebelAndre** [comment]
There's another (updated) PR for https://github.com/bazelbuild/rules_rust/pull/595

**Comment by simonfong6** [comment]
I'm trying to port a Tonic/Tokio project from crates to Bazel as well
