### ISSUE TITLE
The example about rust_test doesn't seem correct

### ISSUE THREAD

**Issue by diohabara** [bazelbuild/rules_rust#482]
## WHAT

[The example about rust_test](https://bazelbuild.github.io/rules_rust/rust.html#rust_test) doesn't seem correct.

## WHY

`greeting` is not a method, but this example uses it as if it were a method. I am wondering this test is intended to test `greet` method.

## FYI

If this is a mistake, let me fix that. 

If this is my misunderstanding, I'm sorry.

**Comment by illicitonion** [comment]
I think this you're completely right - can I tempt you to send a PR to fix it up? :)

Sorry for the delay in getting back to you!
