### ISSUE TITLE
Reintroduce proto_compile_deps and grpc_compile_deps to rust_proto_toolchain

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#483]
@damienmg There is a `TODO` in [proto/toolcahin.bzl](https://github.com/bazelbuild/rules_rust/blob/master/proto/toolchain.bzl#L124-L127)
```python
# TODO(damienmg): Once bazelbuild/bazel#6889 is fixed, reintroduce
# proto_compile_deps and grpc_compile_deps and remove them from the
# rust_proto_library and grpc_proto_library.
rust_proto_toolchain = rule(
```

The issue (https://github.com/bazelbuild/bazel/issues/6889) looks closed now so is this something that should be done still?

**Comment by damienmg** [comment]
Probably yes.
