### ISSUE TITLE
Allow specifying a target for a given rule

### ISSUE THREAD

**Issue by duarten** [bazelbuild/rules_rust#489]
It should be possible to override the current target on a per-rule basis, as some rules compile binaries to run on specific platforms. For example, I want to compile AWS Lambda functions targeting x86_64-unknown-linux-musl on a Mac. The rust_binary adds a `--target=x86_64-apple-darwin` arg to rustc, which I can't override.

**Comment by duarten** [comment]
It seems I can't specify `target_compatible_with` on `rust_binary` rules, although the Bazel documentation [says](https://docs.bazel.build/versions/master/be/common-definitions.html#common.target_compatible_with) it should be defined for all build rules.

**Comment by UebelAndre** [comment]
I believe this is a Bazel 4.0 feature. That documentation isn't in the [3.7](https://docs.bazel.build/versions/3.7.0/be/common-definitions.html#common.target_compatible_with) version, only [master](https://docs.bazel.build/versions/master/be/common-definitions.html#common.target_compatible_with).

https://github.com/bazelbuild/bazel/issues/12455

**Comment by duarten** [comment]
Oh :)
