### ISSUE TITLE
Cannot build with external crates dependencies

### ISSUE THREAD

**Issue by atilag** [bazelbuild/rules_rust#49]
If I understood correctly, external crates referenced in the Cargo.toml files are still not supported, right? So there's no way at the moment to build something that depends on external crates, am I right?

**Comment by acmcarther** [comment]
There's not really a way currently .... or at least not one that has feature parity with Cargo itself. I've been making efforts to [facilitate automatic BUILD generation from Cargo.toml](https://github.com/acmcarther/cargo-raze) -- but I'm doubtful that there will ever be the sort of "drop a Cargo.toml here and get going" experience that you might be imagining.

The above hacky project doesn't support many usecases, one of which is anything that depends on a pkg-config dependency. That includes openssl, and half of crates.io that depends on it, so don't get too excited yet.

Still, I'm working on it!

**Comment by acmcarther** [comment]
A "drop and go" sort of workflow is supported with [google/cargo-raze](https://github.com/google/cargo-raze] if you use the `remote` mode.

Toml would need to add a snippet like this:
```toml
[raze]
genmode = "Remote"
```

This has some deficiencies. For now, I'll close this issue as "not actionable". Feel free to reopen (or file a new issue here or @ cargo-raze) if you have any more specific issues.
