### ISSUE TITLE
Who use Cargo.toml?

### ISSUE THREAD

**Issue by inevity** [bazelbuild/rules_rust#495]
Hi, when use raze and pyo3 build an extension,  I found that the target do not depend the Cargo.toml of the extension source code, so who use it?
I guest when build the target in bazel, they will find the toolchain, then call cargo build or something equllably (which will found the cargo.toml) in the source dir.  Is there anyone can point where the involved code is?

**Comment by illicitonion** [comment]
When using rules_rust, the Cargo.toml is not used at all.

What cargo raze does is read all of the information needed from your Cargo.toml and translates it into BUILD file concepts that rules_rust understands. So after you run cargo raze, the Cargo.toml file is completely unused.
