### ISSUE TITLE
RFC: Rename workspace from `io_bazel_rules_rust` to `rules_rust`

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#499]
According to https://docs.bazel.build/versions/master/skylark/deploying.html#workspace these rules should be named `rules_rust`. I think they should be renamed. Maybe for backwards compatibility the `rust_workspace` macro could define a [bind](https://docs.bazel.build/versions/master/be/workspace.html#bind) for users to ease the transition but I'd definitely like to see this changed. 

What are the concerns in doing this?

**Comment by mfarrugi** [comment]
+1

I imagine for most cases a `sd 'io_bazel_rules_rust' 'rules_rust'  **/*` would suffice.

**Comment by UebelAndre** [comment]
I've opened https://github.com/bazelbuild/rules_rust/pull/500 for the conversion. Given that there are no releases (which I think there should be, per https://github.com/bazelbuild/rules_rust/issues/415) I'm unsure how the transition should be communicated. I did the same thing `rules_python` did in https://github.com/bazelbuild/rules_python/pull/212 by in the way of messaging for users within the code.

**Comment by acmcarther** [comment]
This should probably not be merged. This ruleset is named "io_bazel" to be consistent with the other rules defined in the bazelbuild org.

See rules go: https://github.com/bazelbuild/rules_go. Their workspace is named "io_bazel_rules_go". I don't know the history behind this naming scheme, but I do know that rules_go has "high-tier" support internally, so we should follow their lead on things.

I'm going to mirror this into the issue.

**Comment by UebelAndre** [comment]
> This should probably not be merged. This ruleset is named "io_bazel" to be consistent with the other rules defined in the bazelbuild org.
> 
> See rules go: https://github.com/bazelbuild/rules_go. Their workspace is named "io_bazel_rules_go". I don't know the history behind this naming scheme, but I do know that rules_go has "high-tier" support internally, so we should follow their lead on things.
> 
> I'm going to mirror this into the issue.

This is in direct violation of the documentation in https://docs.bazel.build/versions/master/skylark/deploying.html#workspace

I would assert either that documentation needs to change or this PR should be merged in a reasonable time.

**Comment by damienmg** [comment]
Yep this documentation is pretty recent and I found some more context in bazel-dev@. Historically we took the decision to recommend reverse qualified domain name as naming convention (like Go) but it seems they prefer shorter name and use github orgs for rules.

Bazel initial domain was bazel.io. A few month after new TLD appeared and .build was a natural home for a build system.

**Comment by vincent-herlemont** [comment]
I have this error and there is no occurrences of io_bazel_rules_rust in all my project. An idea of investigation ?
``` 
ERROR: Failed to load Starlark extension '@io_bazel_rules_rust//rust:rust.bzl'.
Cycle in the workspace file detected. This indicates that a repository is used prior to being defined.
The following chain of repository dependencies lead to the missing definition.
 - @io_bazel_rules_rust
This could either mean you have to add the '@io_bazel_rules_rust' repository with a statement like `http_archive` in your WORKSPACE file (note that transitive dependencies are not added automatically), or move an existing definition earlier in your WORKSPACE file.
```

**Comment by UebelAndre** [comment]
Perhaps you're loading a some file from something that expects the old name? Does Bazel not tell you where that load is happening?
