### ISSUE TITLE
Cannot reference non-rust files in source tree at compile time

### ISSUE THREAD

**Issue by djmarcin** [bazelbuild/rules_rust#502]
I've run into the following problems trying to convert an existing codebase to bazel. I think they have the same root cause, which is that it's not possible (or at least I can't figure out how) to reference non-rust files at compile time in a static way.

Example 1, RustEmbed
```
#[derive(rust_embed::RustEmbed)]
#[folder = "../web/public/"]
struct Bundle;
```
The effect of this attribute is to embed the contents of the `../web/public/` folder from the source tree in the binary and make it available via functions on the Bundle struct. My first thought at how to solve this was to add a filegroup on `../web/public` and add it to srcs; however, rust_library targets only allow `*.rs` files as sources, so this doesn't work. Next, I tried adding the filegroup to the `cargo_build_script` rule and copying the files to OUT_DIR. However the `#[folder = ]` attribute must take a literal, so I cannot do something like `#[folder = concat!(env!("OUT_DIR"), "/web/public")]` even though it's a compile-time constant. Luckily, rust-embed offers a way to interpolate env vars in this string, but this is not standard. Additionally, the need to manually copy the incoming filegroup to `OUT_DIR` in `build.rs` in order to make this work is awkward. Is there a nicer way?

Example 2, sqlx::migrate
```
sqlx::migrate!("db/migrations").run(&pool).await?;
```
Much like the RustEmbed example, this example reads the contents of the `db/migrations` directory at compile time and stores them as embedded objects in the binary, which run the migrations when the binary executes. Unlike RustEmbed, sqlx offers no way to interpolate an env var into this string, and must take a string literal. Nothing I have tried allows me to successfully use this macro in library code. Is there a solution to this I'm missing?

I am able to use this macro in build.rs since the path to data dependencies is static so I can write a string literal that works, but that reveals a further problem with the sqlx macro. It checks that the detected `*.sql` files are regular files. For some reason, when bazel symlinks the files into the sandbox directory for build.rs, even though sqlx uses the symlink-following [std::fs::metadata](https://doc.rust-lang.org/std/fs/fn.metadata.html) method, these are not detected as [is_file](https://doc.rust-lang.org/std/fs/struct.Metadata.html#method.is_file). Is there something about how the sandbox works that would prevent std::fs::metadata from working correctly?

**Comment by djmarcin** [comment]
Most of the solution here came after carefully rereading the docs on rust_library, which say that the data attribute can be used when files are needed at compile-time, e.g. for include_str!

I did not manage to resolve the symlink problem with `std::fs::metadata` in `sqlx::migrate!`, so I ended up patching out that code with this patch (in case anyone else needs it):
```
--- a/src/migrate.rs
+++ b/src/migrate.rs
@@ -45,9 +45,4 @@ pub(crate) fn expand_migrator_from_dir(dir: LitStr) -> crate::Result<proc_macro2
     while let Some(entry) = s.next() {
         let entry = entry?;
-        if !entry.metadata()?.is_file() {
-            // not a file; ignore
-            continue;
-        }
-
         let file_name = entry.file_name();
         let file_name = file_name.to_string_lossy();
```

**Comment by illicitonion** [comment]
I'm glad a `data` dep worked for you!

Would it be possible to put together a minimal repro case I can try running for the symlink thing? It sounds weird and interesting :)

**Comment by djmarcin** [comment]
Upon further investigation, in both cases this is because the library uses a method that refuses to follow symlinks. In the RustEmbed case it uses [WalkDir](https://docs.rs/walkdir/2.3.1/walkdir/) which does not follow symlinks by default, and for sqlx it uses [fs::read_dir](https://doc.rust-lang.org/std/fs/fn.read_dir.html) which yields `DirEntry`s which also do not follow symlinks.

It was pretty confusing because `std::fs::DirEntry::metadata` does _not_ follow symlinks, while `std::fs::metadata` does. 🤦 

I've chosen to patch these libraries via `cargo-raze` for now, but it seems like upstreaming a fix to follow symlinks might be worthwhile.
