### ISSUE TITLE
Support Request: expand location in `rustc_flags`

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#507]
I'm trying to build [rusty_v8](https://crates.io/crates/rusty_v8) and am trying to circumvent it's complicated [build.rs](https://github.com/denoland/rusty_v8/blob/master/build.rs) file which only appears to be trying to provide some binary. I've created a small example project of what I've got so far.
https://github.com/UebelAndre/bazel_rusty_v8_example

I want to be able to pass something from [http_file](https://docs.bazel.build/versions/master/repo/http.html#http_file) to the compile/linker step of a particular crate. The generated file [BUILD.rusty_v8-0.13.0.bazel](https://github.com/UebelAndre/bazel_rusty_v8_example/blob/main/third_party/cargo/remote/BUILD.rusty_v8-0.13.0.bazel) contains the following snippet:
```python
rust_library(
    name = "rusty_v8",
    srcs = glob(["**/*.rs"]),
    crate_features = [
    ],
    crate_root = "src/lib.rs",
    crate_type = "lib",
    data = ["@bazel_rusty_v8_example//third_party/rusty_v8:rusty_v8_lib"],
    edition = "2018",
    rustc_flags = [
        "--cap-lints=allow",
        "-lstatic=rusty_v8",
        "-Ldependency=$(rootpath @bazel_rusty_v8_example//third_party/rusty_v8:rusty_v8_lib)",    # <--- Note this line
    ],
    tags = [
        "cargo-raze",
        "manual",
    ],
    version = "0.13.0",
    # buildifier: leave-alone
    deps = [
        "@raze__bitflags__1_2_1//:bitflags",
        "@raze__lazy_static__1_4_0//:lazy_static",
        "@raze__libc__0_2_80//:libc",
    ],
)
```

What do I have to do to correctly pass the directory of `@bazel_rusty_v8_example//third_party/rusty_v8:rusty_v8_lib` to the build action (presumably via the `-L` flag)? Am I just messing up some syntax here or how do I perform that expansion there? Or what other options do I have available to me?

**Comment by UebelAndre** [comment]
I was able to get the `//:rusty_v8_example` target to run
```command
bazel run :rusty_v8_example
```
```output
INFO: Invocation ID: 0109b53a-0f11-4d14-9475-9f6a29cfb8ea
INFO: Analyzed target //:rusty_v8_example (3 packages loaded, 126 targets configured).
INFO: Found 1 target...
Target //:rusty_v8_example up-to-date:
  bazel-bin/rusty_v8_example
INFO: Elapsed time: 1.951s, Critical Path: 0.08s
INFO: 15 processes: 14 remote cache hit, 1 internal.
INFO: Build completed successfully, 15 total actions
INFO: Build completed successfully, 15 total actions
javascript code: 'Hello' + ' World!'
result: Hello World!
```

The trick was to instead create a [cc_import](https://docs.bazel.build/versions/master/be/c-cpp.html#cc_import) target and pass it to the rust rule as a `dep` and not as `data`. I've updated the repo above to reflect that state. Feels a bit heavy handed but does feel correct.

I'm still curious about whether or not I can use some expansions in `rustc_flags`.

**Comment by dae** [comment]
I'm not sure you could do it with rustc_flags, as rootpath likely won't work on generated files, and an absolute path (#503) may run into issues with the sandbox disappearing before the final link.

**Comment by dae** [comment]
Do we even do location expansion for flags? I think it only applies to env at the moment.

**Comment by UebelAndre** [comment]
I'm finding that to be the case. But Is that something that makes sense to support?

**Comment by dae** [comment]
As mentioned above, I'm not sure that would work with link flags. I'd suggest it be left until a concrete use case arises :-)

**Comment by UebelAndre** [comment]
Yeah, I wasn't referring to linker flags [here](https://github.com/bazelbuild/rules_rust/issues/507#issuecomment-734510970) but I suppose if there were to be support for it then it'd lead to bad situations where users could use it for that. Better to leave it for now, I agree. Thanks @dae 🙏

**Comment by bazaglia** [comment]
Hey @dae, the repository @UebelAndre linked above isn't available anymore. Do you happen to still have a snippet I could try? I'm running into the same problem and couldn't fix it even when trying to use `cc_import`. It seems to just don't add anything to the `rust_binary`

**Comment by dae** [comment]
Sorry, I have no experience with cc_import.

**Comment by UebelAndre** [comment]
For anyone looking to build `rusty_v8`, https://github.com/bazelbuild/rules_rust/issues/1668 shows a working example since the example in the original post was lost.
