### ISSUE TITLE
Pass extra flags to clippy

### ISSUE THREAD

**Issue by djmarcin** [bazelbuild/rules_rust#514]
Is there a way to override the default clippy configuration? For example, if I wanted to set `-Dwarnings`, it does not appear possible to do so because the `rust_clippy` rule does not accept `rustc_flags`.

**Comment by dae** [comment]
Related to #456

**Comment by djmarcin** [comment]
Related, but ideally I would be able to override the setting without forking the repo.

**Comment by dae** [comment]
Are there instances in your code where the proposed change to -Dwarnings would not be what you want?

**Comment by smklein** [comment]
From my limited understanding, aspects are also fairly picky with what runtime arguments may be supplied (typically via `attrs`):

https://docs.bazel.build/versions/master/skylark/lib/globals.html#aspect

```
attrs	... dict; or None; default = None

A dictionary declaring all the attributes of the aspect. It maps from an attribute name to an attribute object, like `attr.label` or `attr.string` (see attr module). Aspect attributes are available to implementation function as fields of ctx parameter.
Implicit attributes starting with _ must have default values, and have type label or label_list.

Explicit attributes must have type string, and must use the values restriction. Explicit attributes restrict the aspect to only be used with rules that have attributes of the same name, type, and valid values according to the restriction.
```

That `Explicit attributes must have type string, and must use the values restriction` makes this particularly a pain. 

I can see how one would implement toggles between sets of well-defined flags, but this makes passing arbitrary flags via the aspect more of a challenge. If ya'll see something more viable, suggestions are welcome.

**Comment by smklein** [comment]
And from https://docs.bazel.build/versions/master/skylark/aspects.html#aspect-definition-1

`Aspects with parameters cannot be used via the command line because there is no syntax to define the parameters.`

(Which, to be frank, I find a bummer)

There exists a Bazel rule which is currently tightly coupled to the aspect for executing clippy - @djmarcin , is your use-case for clippy from command line, or would the flags toggle in rule-only form be sufficient?

**Comment by djmarcin** [comment]
My use case is setting a repo-wide lint configuration, so flags on individual rules does not sound like what I want. I also don't want to have to rely on folks remembering to update a central clippy rule in order to have lint standards applied (additionally such a solution would require public visibility for all rules so the clippy rule could depend on them).

Perhaps there could be a solution around a config file at the root (e.g. something like `.clippy.toml` https://github.com/rust-lang/rust-clippy, but I don't think that allows configuring everything unfortunately)
