### ISSUE TITLE
RFC: First class support for external crates

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#530]
In working on https://github.com/bazelbuild/rules_rust/pull/392 I found https://github.com/dtolnay/cxx which is a crate that could potentially satisfy the need for both `bindgen` and `cbindgen`. The interesting bit is that `cxx` provides Bazel rules for use with `rules_cc` and `rules_rust`. This stands out to me as the ideal location for such rules. However, the primary Rust rules for Bazel include `proto`/`grpc`, `bindgen`, and `wasm-bindgen` rules which are all based on external crates. There's even talk of adding additional rules for external crates (https://github.com/bazelbuild/rules_rust/pull/479 https://github.com/bazelbuild/rules_rust/pull/392).

My questions are, is this the ideal future? Should `rules_rust` have first class rules for these crates? Or should we be striving add these rules to the relevant crates? Where should the line be drawn on what gets added to the rules and what doesn't?

@damienmg @illicitonion @mfarrugi @smklein @dfreese

**Comment by mfarrugi** [comment]
If there was One True Build system, then sure it would make sense for all
those random tools to provide their corresponding .bzl files. As it stands,
only by chance does cxx have direct support for bazel. Maybe `bzlmod` will
change this and supplant Cargo et al, but I suspect that is a long
way away. I think it makes perfect sense for these plugins to continue to
accumulate in rules_rust as needed.

**Comment by UebelAndre** [comment]
What is `bzlmod`? 

And I don't feel like it makes "perfect" sense. The thing I'd like to take a crack at is a rule (likely backed by `cargo-raze`) which lives in `rules_rust` could be used to build a crate given it's Cargo.toml and Cargo.lock files and be used in a small `.bzl` file committed to that repo. I would imagine if the footprint is small enough and it didn't conflict with design choices of that crate, that it could be added once and go untouched for quite some time. 

I think even if `rules_rust` continues to have first class rules for these external crates, that this is functionality that would be extremely beneficial.

**Comment by mfarrugi** [comment]
bzlmod is https://github.com/bazelbuild/bzlmod

**Comment by UebelAndre** [comment]
Closing this since there doesn't appear to be much interest and the focus has sorta shifted. Maybe my original hopes for this RFC can be solved in the future with better ways to interact with external crates
