### ISSUE TITLE
Update documentation to the latest commit

### ISSUE THREAD

**Issue by chandlerc** [bazelbuild/rules_rust#539]
Currently the docs suggest pulling an archive from November 10th. Using this with `cargo raze`, I couldn't get anything to work due to the Bazel version checks being broken somehow.

To fix this, I just pulled a more recent version. Filing this issue to nudge towards updating the documentation.

Given that there has not yet been a release, maybe it makes sense to switch the documentation to recommend a `git_repository` fetch instead of a pinned archive of a particular commit? That would at least allow `bazel sync` to update to the latest...

**Comment by UebelAndre** [comment]
Somewhat related to this, there's an ongoing (dead?) conversation about the state of releases for these rules in https://github.com/bazelbuild/rules_rust/issues/415

In general I think it's better to adopt releases vs using `git_repository` to prevent unexpected breakages for end users. That said, updating documentation to communicate the state of releases or how to use the rules in your project would definitely improve things.

**Comment by sigmaxipi** [comment]
For those who were having trouble getting started, this is the minimal WORKSPACE file I used to get past the version issues:

```
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")                                                                                                           
git_repository(                                                                                                                                                                 
    name = "io_bazel_rules_rust",                                                                                                                                               
    remote = "https://github.com/bazelbuild/rules_rust/",                                                                                                                       
    commit = "c7a408a8c58c6dde73a552d6f78f90c7ef96b513",                                                                                                                        
)                                                                                                                                                                               
                                                                                                                                                                                
load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")                                                                                                        
rust_repositories()
```

**Comment by UebelAndre** [comment]
I would recommend using `http_archive` if you're going to be pinning to a commit. Downloading the repository will be faster.
```python 
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_rust",
    sha256 = "bbebfd5b292fa8567fa012b3d1056f2e51611fe8ac898860323b6b4d763a4efd",
    strip_prefix = "rules_rust-c7a408a8c58c6dde73a552d6f78f90c7ef96b513",
    urls = [
        # Master branch as of 2020-12-22
        "https://github.com/bazelbuild/rules_rust/archive/c7a408a8c58c6dde73a552d6f78f90c7ef96b513.tar.gz",
    ],
)

load("@io_bazel_rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()
```

If someone were to want to simply stay on `master`, then I think `git_repository` makes sense:
```python
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "io_bazel_rules_rust",
    remote = "https://github.com/bazelbuild/rules_rust/",
    branch = "master",
)
```

**Comment by UebelAndre** [comment]
Now that `rules_rust` does releases, documentation on how to get the latest release of the rules can be found in the notes for each release: https://github.com/bazelbuild/rules_rust/releases
