### ISSUE TITLE
make sure to review a new RFC

### ISSUE THREAD

**Issue by johnynek** [bazelbuild/rules_rust#54]
https://github.com/rust-lang/rfcs/pull/2136

This explicitly mentions bazel. Someone from this project should review that RFC and make sure any obvious points are missed.

**Comment by acmcarther** [comment]
Back when that RFC was active, I dropped my two cents in there. It happens that I took quite a lot of what was suggested (specifically specifying customizations in the Cargo.toml) and implemented these into [google/cargo-raze](https://github.com/google/cargo-raze#generate-a-cargotoml) as a `[raze]` section.

That said, I didn't really fulfill the _spirit_ of that RFC -- good interaction with the standard tools. There are some discussions happening to claw some of that back (https://github.com/bazelbuild/rules_rust/issues/71 comes to mind), but I harbor a huge amount of pessimism that we can (or should!) impose our constraints on the Rust ecosystem as a whole.

With that said, I'm going to close this for now as I don't see any next steps for this issue. I'm definitely going to keep an eye on how this moves forward Rust-side though. Please reopen if I missed anything!
