### ISSUE TITLE
allow for project specific rust file server mirrors

### ISSUE THREAD

**Issue by dirkboye** [bazelbuild/rules_rust#550]
We mirror all external dependencies to our local network so that we do not need any internet access for building our software.
Using environment variable `STATIC_RUST_URL` is good for our CI but it's cumbersome for developers who need
to have the environment variable set as well.

A better solution can be seen in `go_rules` method `go_download_sdk` ( see https://github.com/bazelbuild/rules_go/blob/master/go/toolchains.rst#go-download-sdk ) where you can set the mirror urls.

I'd like to propose to add something similar to `rust_toolchain_repository` which would make it possible to
have project-specific rust mirrors.

**Comment by dirkboye** [comment]
PR was merged!

**Comment by UebelAndre** [comment]
Oh, one other thing I *just* came accross this morning. You might have been able to add a `.bazelrc` file to your projects and specify a [repo_env](https://docs.bazel.build/versions/master/command-line-reference.html#flag--repo_env). Would that have also worked for you?

**Comment by dirkboye** [comment]
@UebelAndre unfortunately that doesn't work so well and increases build times for our CI as we use `bazel query` in our scripts.

`bazel query` does not support `--repo_env` or `--action_env`

running `bazel build` with repo_env will then result in

```
INFO: Build option --repo_env has changed, discarding analysis cache.
```

**Comment by UebelAndre** [comment]
Oh wow, really good to know. That seems like a bug on Bazel's side though 😞 I otherwise don't understand why `--repo_env` shouldn't be supported by all commands

**Comment by dirkboye** [comment]
@UebelAndre here's an open issue on the bazel side for that:
https://github.com/bazelbuild/bazel/issues/11943

**Comment by UebelAndre** [comment]
@dirkboye Oh wow, you're a hero! Thank you 🙏 😄
