### ISSUE TITLE
sqlx query checker + bazel immutable OUT_DIR fails

### ISSUE THREAD

**Issue by djmarcin** [bazelbuild/rules_rust#552]
I'm not entirely sure what broke things, but the symptoms are that the sqlx query checker fails with a message like this:
```
error returned from database: attempt to write a readonly database
```

sqlx provides compile time query correctness checking by using a database generated from your schema to test queries. I'm using a sqlite database that was written during a `build.rs` into the `OUT_DIR`. Apparently this checking sometimes causes sqlite to check if it is readonly, and it seems that the `OUT_DIR` and files inside it are marked read-only, so this error makes sense.

Looking for suggestions on a solution here. I already tried marking both the sqlite database file as well as the `OUT_DIR` as read-write during the `build.rs` but this did not work (presumably because the files are being copied out of the sandbox and being marked readonly after the build script runs? but I'm not sure). A solution would preferably:
- Allow the file to be found during subsequent compilation of the crate (currently I use `println!("cargo:rustc-env=DATABASE_URL={}", database_url);` from the `build.rs`)
- Resist collision if multiple compilations were happening at the same time on the same machine (so simply writing to `/tmp/query_checker.db` is out).
- Resist compilation errors resulting from normal user behavior (so again, a file in /tmp is at risk of being deleted without triggering a rerun of `build.rs`)

**Comment by UebelAndre** [comment]
How big are the databases? Can they be dumped in the `build.rs` and rebuilt when needed in downstream targets? It seems odd to me that someone would create a mutable database as an output for virtually any Bazel target.

**Comment by djmarcin** [comment]
The way the sqlx proc macros work is they use the database pointed to by `DATABASE_URL` to get the schema and probably to parse the queries (I don't know exactly, I'm just guessing). There's no actual data in the database to dump.

I agree it's potentially non-hermetic to have this be writable, but there's not much I could really do about it without deep changes to the proc macro, which I'm not really familiar with.

**Comment by djmarcin** [comment]
One possible fix would be for the `rust_library` rule to copy the sqlite db input file so that it could modify it. This seems like a pretty niche thing to do, though.

Unfortunately writing the file outside `OUT_DIR` from the `build.rs` is really broken because it doesn't get recreated even after `bazel clean` if the build script is cached.

I can look a little further into if there's a way to avoid needing this file to be writable.

**Comment by djmarcin** [comment]
I was able to work around this by setting the `immutable=true` property on the sqlite database I am using (plus a patch for sqlx to support it). It looks like the problem is actually that sqlite needed to be told not to try to write things like the WAL or a lock file into the directory.
