### ISSUE TITLE
Cargo requires that rustc is installed locally as well

### ISSUE THREAD

**Issue by iffyio** [bazelbuild/rules_rust#584]
Hi! I have e.g the following trying to run cargo via bazel:

```python
sh_binary(
  name="cargo",
  srcs=["@rust_linux_x86_64//:cargo"],
)
```

Running a command like build or fmt that shells out to rustc fails

```sh
bazel run cargo -- fmt
error: no such subcommand: `fmt`

        Did you mean `fix`?
```
However this issue only shows up because rust isn't installed on the machine outside bazel (installed via e.g rustup, the bazel target runs) which isn't ideal since a primary reason to wrap cargo in bazel would be to ignore any local installation and have it run on machines that don't have one.
Is this an issue with toolchain setup in rules_rust or maybe there's some extra setup needed to have cargo find the toolchain's rustc?

**Comment by dae** [comment]
You may be able to adapt the following to your needs: https://github.com/bazelbuild/rules_rust/blob/16b3e6dc9c46457bdf29358feb389445cc7d3025/worker/bootstrap.bzl

**Comment by iffyio** [comment]
Will try that out, thanks!

**Comment by UebelAndre** [comment]
@iffyio Did the link in https://github.com/bazelbuild/rules_rust/issues/584#issuecomment-777294398 solve the issue for you?

**Comment by iffyio** [comment]
Yes, this solved what I was looking to do! Thanks!
