### ISSUE TITLE
Split rust_library into smaller rules

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/rules_rust#591]
As socialized on https://groups.google.com/g/rules_rust/c/kGMg6haEF44, we're going to split `rust_library` into smaller rules. This is the tracking issue for the effort.

Steps:

- [x] Submit defs.bzl with rules in the desired end state
- [x] Regenerate docs
- [x] Provide buildozer migration script
- [x] Migrate all uses of `@rules_rust//rust:rust.bzl` in the repository to `@rules_rust//rust:defs.bzl`
- [x] Update raze and other closely related projects
- [x] Wait for the community to migrate
- [ ] Remove the deprecated rust.bzl file. Currently planned for 2021-10-26.

**Comment by hlopko** [comment]
Buildozer migration scripts:

```bash
buildozer 'fix movePackageToTop' //...:__pkg__
buildozer 'substitute_load //rust:rust.bzl$ //rust:defs.bzl' //...:__pkg__

buildozer 'set kind rust_proc_macro' $(bazel query 'attr(crate_type, proc-macro, (//...))')
buildozer 'new_load @rules_rust//rust:defs.bzl rust_proc_macro' $(bazel query 'attr(crate_type, proc-macro, (//...))')

buildozer 'set kind rust_static_library' $(bazel query 'attr(crate_type, staticlib, (//...))')
buildozer 'new_load @rules_rust//rust:defs.bzl rust_static_library' $(bazel query 'attr(crate_type, staticlib, (//...))')

buildozer 'set kind rust_shared_library' $(bazel query 'attr(crate_type, cdylib, (//...))')
buildozer 'new_load @rules_rust//rust:defs.bzl rust_shared_library' $(bazel query 'attr(crate_type, cdylib, (//...))')

buildozer 'remove crate_type' $(bazel query 'attr(crate_type, .*, (//...))')

buildozer 'fix unusedLoads' //...:__pkg__
```

**Comment by dae** [comment]
> FYI: Cargo-raze v0.13 is released and it produces BUILD files that are compatible with this breaking change.

Are you sure? I'm still seeing rust_library() in output build files, and can't find references to things like 'rust_static_library' in the cargo-raze sources. I see no associated PR, and only an open issue: https://github.com/google/cargo-raze/issues/398
