### ISSUE TITLE
What is rust_binary::out_binary?

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#604]
https://bazelbuild.github.io/rules_rust/defs.html#rust_binary-out_binary

And what's the status of the deprecated attributes on the rule?

**Comment by hlopko** [comment]
I just saw we have this attribute 5 minutes ago :)

**Comment by dfreese** [comment]
It's a wasm related thing. I can try dig up the initial issue.

**Comment by UebelAndre** [comment]
@dfreese Can I instead ask that you add documentation for that attribute? Instead of writing anything here? 🙏

**Comment by UebelAndre** [comment]
related https://github.com/bazelbuild/rules_rust/pull/312
