### ISSUE TITLE
Enable //bindgen on the Windows CI

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/rules_rust#617]
Since https://github.com/bazelbuild/rules_rust/pull/612 we test more stuff on Windows, we don't test everything though. //bindgen is currently disabled in .bazelci/presubmit.yml.

Feel free to comment on this issue if you want to know more or you want to give it a shot. We are happy to talk or help :)

How to fix when you don't have a Windows machine:
1) delete the line with `    - "-//bindgen/..."`
2) upload a draft PR
3) see the CI failure
4) try to fix it

How to fix when you do have a Windows machine:
1) Try to repro the failure localy
2) Fix it
3) upload the PR :)

**Comment by UebelAndre** [comment]
This was enabled by https://github.com/bazelbuild/rules_rust/pull/1998
