### ISSUE TITLE
Can't build a rust_library as wasm -- output path incorrect with crate_type cdylib

### ISSUE THREAD

**Issue by shortenda** [bazelbuild/rules_rust#627]
Hello,

I wanted to have a single library file used by both Javascript and rust code so I tried using a rust_library rule wrapped by a rust_wasm_bindgen rule. However, the rust_library with crate_type cdylib doesn't generate the expected output file. It seems this is because rustc does not prefix the file with 'lib' in this case. Altering the code with a hack to set prefix to '' when crate type is cdylib and target arch is wasm32 resolves this issue. E.g., in private/rust.bzl _determine_lib_name():
    if toolchain.target_arch == "wasm32" and crate_type in ("cdylib"):
        prefix = ""

For the rule to succeed it is also necessary to skip the output of the CcInfo, since it won't be generated. This issue also shows up and is resolved when trying to build a rust_library with crate_type=cdylib and --platforms=@rules_rust//rust/platform:wasm.

With these changes you can have a rust_library wrapped by a rust_wasm_bindgen rule and it works as expected. Is this something that could be resolved (perhaps in a different manner) for all? The alternative would seem to be using a rust_binary rule, but for that I believe my wasm code would need to be in the main.rs file to be built, which doesn't work well when using it as a rust library from rust code.

Am I missing an existing way of accomplishing this neatly?

**Comment by titanous** [comment]
Please try out #715, it should fix all of the mentioned issues and you shouldn't need to specify `--platforms` when building (this is handled automatically by a config transition).
