### ISSUE TITLE
rust_fmt

### ISSUE THREAD

**Issue by tschuett** [bazelbuild/rules_rust#634]
Are there any plans to add a rust_fmt rule?

```python
rust_fmt(
  name = "format_library",
  deps = [
    ":bar",
    ":foo",
    ],
)
```

There is a basic example:
https://github.com/bazelbuild/rules_rust/tree/main/test/rustfmt

**Comment by UebelAndre** [comment]
https://github.com/bazelbuild/rules_rust/issues/87 sounds relevant to this request

**Comment by tschuett** [comment]
After reading the other issues, I like the idea of modelling it as test:
```Python
rust_test_fmt(
  name = "test_format",
  deps = [
    ":bar",
    ":foo",
   ]
)
```

**Comment by hlopko** [comment]
I haven't looked into other issues (is it just https://github.com/bazelbuild/rules_rust/issues/87 or others as well?), and I only skimmed through the implementation, but my knee jerk proposal would be to implement the rust_fmt as an aspect and then it would be used by for example running `bazel build --aspects @rules_rust//rust:defs.bzl%rust_fmt_aspect` //foo/bar (there will need to be `--experimental_run_validations` also but that's only until Bazel stabilizes that feature).

If the source file is not formatted correctly, the build would fail. Advantage over `deps` approach in my perspective is that you don't have to specify which libraries to cover (which people can forget to do), you just enable the aspect on the CI for the regular test suite run (which usually has //... so it automatically covers everything).

Pardon my ignorance, but does rust-analyzer use rustfmt, or it implements formatting by itself? If it has its own implementation then there will be differences, and that will cause trouble. In that case I'd vote for using rust-analyzer for formatting (if it can be done), not rustfmt (I'm a big fan of rust-analyzer as you can tell :).

**Comment by tschuett** [comment]
There was also: https://github.com/bazelbuild/rules_rust/issues/388.

I use the following to assert that nothing changed
```bash
git diff --exit-code --summary --stat
```
