### ISSUE TITLE
Documentation for rust-analyzer rule

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#636]
There should be some documentation for how to setup rust-analyzer in Bazel and what the recommended workflows/tools are to getting it setup for things like vscode or vim. I think making this more discoverable will help everyone tremendously and inspire people to make future improvements.

**Comment by UebelAndre** [comment]
cc @djmarcin

**Comment by hlopko** [comment]
+1. https://github.com/bazelbuild/rules_rust/pull/505#issuecomment-780066923 is a good starting point, but it would be great to have a easily discoverable docs for this (I had to look up that comment 3 times in last 2 weeks :)

**Comment by UebelAndre** [comment]
I believe this is addressed by https://github.com/bazelbuild/rules_rust/pull/711. If anyone feels the docs are still lacking, I think we should track more specific problems in new issues.
