### ISSUE TITLE
Surfacing `rust_analyzer` usage documentation

### ISSUE THREAD

**Issue by yagehu** [bazelbuild/rules_rust#648]
I'm new to using Bazel. It took me quite a while to find the instruction for using the `rust_analyzer` rules [here](https://github.com/bazelbuild/rules_rust/pull/505#issuecomment-780066923). I would like to contribute by surfacing that knowledge and adding it to the main [manual page](https://bazelbuild.github.io/rules_rust/). I've reviewed the contributing guidelines, and I'll sign the CLA.

**Comment by UebelAndre** [comment]
That would be wonderful! I've also expressed desire to see docs for it in https://github.com/bazelbuild/rules_rust/issues/636 so am clearly already a fan of the idea 😀

**Comment by yagehu** [comment]
Great. I've created #649.
