### ISSUE TITLE
external/examples/hello_runfiles/hello_runfiles_test failing in Bazel release 0.11.0rc3

### ISSUE THREAD

**Issue by katre** [bazelbuild/rules_rust#68]
https://ci.bazel.build/blue/organizations/jenkins/Global%2Frules_rust/detail/rules_rust/412/tests

Platforms:
- darwin-x86_64

**Comment by katre** [comment]
Blocking release https://github.com/bazelbuild/bazel/issues/3959

**Comment by acmcarther** [comment]
https://github.com/bazelbuild/rules_rust/pull/66 fixes. I was waiting on review, but I'll push now to unblock Bazel release.

**Comment by katre** [comment]
Thank you! I believe there is work on a platform-independent runfiles library for Java, possibly the same concepts could be ported to Rust to handle this more generically.

**Comment by mfarrugi** [comment]
@katre Is there a doc on the public api for runfiles? `bazel test` uses the exec root binary on linux but the runfiles' binary under osx, which is a bit surprising.

**Comment by katre** [comment]
@laszlocsomor has been making the runfiles changes in Java, I think.

**Comment by laszlocsomor** [comment]
@mfarrugi :
> Is there a doc on the public api for runfiles?

Not at the moment.

> `bazel test` uses the exec root binary on linux but the runfiles' binary under osx, which is a bit surprising.

I wasn't aware, but yes, any code trying to find the runfiles has to handle both cases. The Java launcher describes the cases nicely: https://github.com/bazelbuild/bazel/blob/04757dba0174d22c0a695a7ed5fe511fd13df008/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt#L110-L118

> I believe there is work on a platform-independent runfiles library for Java

Yes, I'm working on that, follow along on https://github.com/bazelbuild/bazel/issues/4460. Bazel 0.11.0 will release the Java-specific runfiles library, watch out for these release notes:

> ### New features:
>
> * java,runfiles: You can now depend on `@bazel_tools//tools/runfiles:java-runfiles` to get a platform-independent runfiles library for Java. See JavaDoc of https://github.com/bazelbuild/bazel/blob/master/src/tools/runfiles/java/com/google/devtools/build/runfiles/Runfiles.java for usage information.

(https://releases.bazel.build/0.11.0/rc3/index.html)

**Comment by katre** [comment]
Fixed in 0.11.0rc4.
