### ISSUE TITLE
Cleanup old branches

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#688]
I suspect there's nothing of value in any of the old branches and they should be deleted. I would also assert that no maintainer should be creating development branches on the upstream repo. Any objection to me deleting these?

@hlopko @acmcarther

**Comment by UebelAndre** [comment]
The branches have been removed. Any branch that looks like it had work on them have already been merged or addressed in some other way.

**Comment by dfreese** [comment]
Given that these have been around for a while, and not hurting anyone, would have like to see more affirmative consent here before this was done.

**Comment by UebelAndre** [comment]
Sorry about that. It won't happen again 😓
