### ISSUE TITLE
Add co-maintainers to the repo?

### ISSUE THREAD

**Issue by SirVer** [bazelbuild/rules_rust#69]
@damienmg @ulfjack Is there a possibility to hand out write rights for this repository? For example @acmcarther  is a Googler that has an interest in improving these rules. We from Lyft Germany also need these rules to be polished before they fulfil our needs. Right now there are forks floating around which is never ideal. 

I understand that this repo is not a high priority for core bazel atm. However, there are pull requests sitting unanswered and most of them could be easily resolved without the core bazel team needing to look at. Could you turn maintenance of these rules over to the community by handing out write bits?

**Comment by acmcarther** [comment]
We actually added maintainers very recently (including myself).

The hold up on a lot of this is partially me. I'll polish up these outstanding features and get them merged, as well as ping the other maintainers and see if we can get eyes on PRs

**Comment by SirVer** [comment]
My bad, I misunderstood this in our conversation. Sorry for the noise, bazel team.
