### ISSUE TITLE
Support cargo environment variables

### ISSUE THREAD

**Issue by mfarrugi** [bazelbuild/rules_rust#70]
Cargo passes a variety of environment variables to crates at compile time. We should pass (some of?) those variables to more easily build crates.io packages.

 https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

**Comment by acmcarther** [comment]
Its possible to sidestep this issue in some cases by specifying the environment variables in a bazel.rc

*//tools/bazel.rc*
```
build --action_env=CARGO_PKG_NAME=mock --action_env=CARGO_PKG_VERSION_PATCH=mock --action_env=CARGO_PKG_VERSION_MAJOR=mock --action_env=CARGO_PKG_VERSION_MINOR=mock --action_env=CARGO_PKG_VERSION=mock2 --action_env=CARGO_PKG_AUTHORS=mock2
run --action_env=CARGO_PKG_NAME=mock --action_env=CARGO_PKG_VERSION_PATCH=mock --action_env=CARGO_PKG_VERSION_MAJOR=mock --action_env=CARGO_PKG_VERSION_MINOR=mock --action_env=CARGO_PKG_VERSION=mock2 --action_env=CARGO_PKG_AUTHORS=mock2
test --action_env=CARGO_PKG_NAME=mock --action_env=CARGO_PKG_VERSION_PATCH=mock --action_env=CARGO_PKG_VERSION_MAJOR=mock --action_env=CARGO_PKG_VERSION_MINOR=mock --action_env=CARGO_PKG_VERSION=mock2 --action_env=CARGO_PKG_AUTHORS=mock2
```
If we want to actually pass useful information, we'll need to make a more substantial change to the common_attrs. Perhaps the CARGO_PKG fields could be bundled into an optional struct?

I'm really uneasy about the MANIFEST_DIR  (and of course, the CARGO) vars though.
