### ISSUE TITLE
Unify crate_universe `_deps` and `crates_from` functions

### ISSUE THREAD

**Issue by illicitonion** [bazelbuild/rules_rust#700]
Right now we separately generate these functions in the generated workspace:
`all_deps`, `all_proc_macro_deps`, `crates_from`, `dev_crates_from`, `build_crates_from`, `proc_macro_crates_from`.

Ideally we'd generate one function along the lines of:

```python
def crates(default=True, dev=False, build=False, proc_macro=False, from=None):
```

where `default`, `dev`, `build`, `proc_macro` enable/disable the relevant dep kinds, and `from` accepts a string/label to subset down to just the deps declared in a particular `Cargo.toml`.

**Comment by UebelAndre** [comment]
If there is a `from` parameter then does that mean we're open to having an `all_crates` macro too?

Also, `cargo-raze` uses `crate_deps` and `all_crate_deps` which we could also use to make transitioning to using `crate_universe` easier.

**Comment by illicitonion** [comment]
What would `all_crates` do distinct from `crates` described above? (I am not at all attached to specific naming, by the way)

For this rule:
```python
crate_universe(
    name = "rust_deps",
    cargo_toml_files = [
        "//project1:Cargo.toml", # Contains lazy_static
        "//project2:Cargo.toml", # Contains tokio
    ],
)
```

I'm imagining:
* `crates()` would map to `[crate("lazy_static"), crate("tokio")]`
* `crates(from="//project1:Cargo.toml")` would map to `[crate("lazy_static")]`

**Comment by UebelAndre** [comment]
Ah, I misunderstood `from`. I don't think I'm the biggest fan of having `from` refer to a `Cargo.toml`. I'm interested in composable `crate_universe` repositories where there's colocated sets of dependencies per package. All that's to say, I'd like `from` to work in cases where I'm not using `Cargo.toml` files but am definitely a fan of something like this.

Also for reference: https://github.com/google/cargo-raze/blob/main/impl/src/rendering/templates/partials/crates_macro.template

**Comment by illicitonion** [comment]
In keeping with the existing functions, I was imagining `crates()` as a symbol defined by the specific `crate_universe` repository. So if you have multiple `crate_universe` rules, you could do something like:

```python
load("@rust_deps_one//:defs.bzl", crates_one = "crates")
load("@rust_deps_two//:defs.bzl", crates_two = "crates")

rust_library(
    deps = crates_one() + crates_two(),
)
```

With the caveat that this is a bad idea, because the independent resolves are likely to have conflicting transitive deps. In general, if you want stuff to interplay, you should put them in the same `crate_universe`, if you want them to function independently, you should have multiple `crate_universe`s, but you probably don't want a half-way mix of the two...

**Comment by UebelAndre** [comment]
I don't think combining universes like that ends up working out. There may be incompatible dependencies between the two which would otherwise have been expected to be resolved if the dependencies were generated using the same configuration. This is one of the things [cargo workspaces](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) solves for. I think a better approach would be to do something where we update `cargo_toml_files` to `manifests` or something which takes `Cargo.toml` files and `Bazel.toml` (or some other name) files and the resolver has the ability to parse dependencies and appropriately generate everything as part of the same workspace. If this were the case, then I think `files` would work out perfectly and makes `crate_universe` composable and potentially sharable across repository boundaries (just as `Cargo.toml` files are sharable, this new `Bazel.toml` file would be too).

**Comment by illicitonion** [comment]
I agree that workspaces are useful here - what we're effectively doing at the moment is artificially constructing a workspace out of the Cargo.toml files passed, and I can see wanting a non-Cargo way of defining additional deps in a file (your mooted `Bazel.toml`, or possibly a `.bzl` file of some kind).

But concretely, in terms of _consuming_ deps, rather than specifying them to the `crate_universe` rule, what are you proposing changing from what's outlined above?

It's useful to have the `from` attribute so that targets which work in both Bazel and Cargo can closely wrap their particular `Cargo.toml` file while benefiting from interop and shared cache hits with other targets which use other `Cargo.toml` files when using Bazel, so I wouldn't want to remove it without a replacement that meets those needs.

**Comment by UebelAndre** [comment]
I'm not considering changing anything anymore. I think we're on the same page. My initial read of the proposal was very Cargo specific which I'd have concerns about, but if we're happy with adding some kind of `Bazel.toml` or `.bzl` file to define dependencies in a similar fashion to `Cargo.toml` files, then I'm totally on board 😄

**Comment by illicitonion** [comment]
This got done as part of the cargo-bazel migration :)
