### ISSUE TITLE
Compilation errors hidden on Linux/MacOS

### ISSUE THREAD

**Issue by Ubehebe** [bazelbuild/rules_rust#708]
Consider the following malformed `main.rs`:

```rust
fn main() {
  println!("ok"
}
```

and the corresponding BUILD file:

```py
load("@rules_rust//rust:rust.bzl", "rust_binary")

rust_binary(
    name = "main",
    srcs = [
        "main.rs",
    ],
)
```

I expect `bazel build //:main` to fail with an error pointing out the missing closing paren. Instead, on Linux/MacOS, all I see is this:

```
$ bazel build //:main 
ERROR: BUILD:3:12: output 'main' was not created
ERROR: BUILD:3:12: Compiling Rust bin main (1 files) failed: not all outputs were created or valid
Target //main:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
FAILED: Build did NOT complete successfully
```

The action correctly fails, but the `rustc` stdout/stderr containing the compilation errors is not printed to the console.

This is a severe usability problem: it means no compiler errors are ever shown to users on Linux/MacOS.

After some debugging, I believe the issue lies in how `system_posix.cc` handles the `rustc` exit status:

https://github.com/bazelbuild/rules_rust/blob/main/util/process_wrapper/system_posix.cc#L177-L182

This code uses `waitpid` incorrectly. The value placed in the `exit_status` variable by `waitpid` is not actually the child's exit status. It is an opaque integer from which the actual exit status can be extracted via the `WEXITSTATUS` macro ([documentation](https://linux.die.net/man/2/waitpid)). As a result, I believe Bazel gets confused about the exit status of the action as a whole, and does not print its stdout/stderr.

When I replace `return exit_status` by `return WEXITSTATUS(exit_status)`, Bazel prints the compilation error to the console as expected.

**Comment by Ubehebe** [comment]
The process wrapper shipped in Bazel does exactly `WEXITSTATUS(exit_status)`: https://github.com/bazelbuild/bazel/blob/master/src/main/tools/process-wrapper-legacy.cc#L163-L164.

Given the severe failure mode (no compiler errors surfaced to Bazel on MacOS/Linux), I'm confused how anyone has been using rules_rust on those OSes for the last 9 months. Are the maintainers of rules_rust developing on Windows exclusively?

**Comment by UebelAndre** [comment]
I'm not sure how this went unnoticed. But I think it'd be great to get a fix up in a PR 😅

**Comment by Ubehebe** [comment]
> I'm not sure how this went unnoticed

Me either. Before #709 is merged, can someone repro the reported bug? I reproed it on my Linux and MacOS machines, but it still feels like something isn't adding up: it feels like ~everyone on those OSes would have had this problem.

**Comment by UebelAndre** [comment]
I'm able to see compiler errors locally using the following diff
```diff
diff --git a/test/rust_test_suite/src/lib.rs b/test/rust_test_suite/src/lib.rs
index 05a141c..c79a9b8 100644
--- a/test/rust_test_suite/src/lib.rs
+++ b/test/rust_test_suite/src/lib.rs
@@ -10,5 +10,5 @@ pub fn fibonacci(n: i32) -> i32 {
         0 => 1,
         1 => 1,
         _ => fibonacci(n - 1) + fibonacci(n - 2),
-    }
+
 }
```

```
INFO: Invocation ID: 76e2279b-1cb1-4f27-87e2-d4c39319f53e
DEBUG: /private/var/tmp/_bazel_user/76282c66b0dfe3c5cb9a230bdc913a52/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:14: buildkite_config not using checked in configs; Bazel version 4.0.0 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", "9.0.0"], "0.23.1": ["8.0.0", "9.0.0"], "0.23.2": ["9.0.0"], "0.24.0": ["9.0.0"], "0.24.1": ["9.0.0"], "0.25.0": ["9.0.0"], "0.25.1": ["9.0.0"], "0.25.2": ["9.0.0"], "0.26.0": ["9.0.0"], "0.26.1": ["9.0.0"], "0.27.0": ["9.0.0"], "0.27.1": ["9.0.0"], "0.28.0": ["9.0.0"], "0.28.1": ["9.0.0"]}
INFO: Analyzed target //test/rust_test_suite:math_lib (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From Compiling Rust rlib math_lib (1 files):
error: this file contains an unclosed delimiter
  --> test/rust_test_suite/src/lib.rs:14:3
   |
8  | pub fn fibonacci(n: i32) -> i32 {
   |                                 - unclosed delimiter
9  |     match n {
   |             - this delimiter might not be properly closed...
...
14 | }
   | - ^
   | |
   | ...as it matches this but it has different indentation

error: aborting due to previous error

ERROR: /Users/user/Code/rules_rust/test/rust_test_suite/BUILD.bazel:3:13: output 'test/rust_test_suite/libmath_lib-1239279067.rlib' was not created
ERROR: /Users/user/Code/rules_rust/test/rust_test_suite/BUILD.bazel:3:13: Compiling Rust rlib math_lib (1 files) failed: not all outputs were created or valid
Target //test/rust_test_suite:math_lib failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.410s, Critical Path: 0.02s
INFO: 2 processes: 1 remote cache hit, 1 internal.
FAILED: Build did NOT complete successfully
```

**Comment by UebelAndre** [comment]
Could you maybe send a repro so I can test the same thing you are?

**Comment by Ubehebe** [comment]
Interestingly, the compilation errors only seem to be dropped when using rules_rust from a downstream repo. When I change a target in the rules_rust repo, as you did, I see the compilation errors.

I have no idea why Bazel would surface action stdout/stderr differently based on what repo the target lives in, but that's what I observe. If you create a new repo that brings in rules_rust in its WORKSPACE and defines the `rust_binary` target I described [above](https://github.com/bazelbuild/rules_rust/issues/708#issue-866768759), you should hopefully be able to repro the bug.

**Comment by UebelAndre** [comment]
So I used the workspace below but was still able to get errors
```
user@MacBook-Pro rust % bazel build ...
INFO: Invocation ID: 08989dd4-ad9f-4322-b725-6d9d58160149
INFO: Analyzed target //:main (28 packages loaded, 30020 targets configured).
INFO: Found 1 target...
INFO: From Compiling Rust bin main (1 files):
error: mismatched closing delimiter: `}`
 --> main.rs:3:1
  |
1 | fn main() {
  |           - closing delimiter possibly meant for this
2 |     println!("ok"
  |             - unclosed delimiter
3 | }
  | ^ mismatched closing delimiter

error: aborting due to previous error

ERROR: /Users/user/Code/test/rust/BUILD.bazel:3:12: output 'main' was not created
ERROR: /Users/user/Code/test/rust/BUILD.bazel:3:12: Compiling Rust bin main (1 files) failed: not all outputs were created or valid
Target //:main failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 54.405s, Critical Path: 1.68s
INFO: 11 processes: 4 remote cache hit, 6 internal, 1 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

## BUILD.bazel
```python
load("@rules_rust//rust:rust.bzl", "rust_binary")

rust_binary(
    name = "main",
    srcs = [
        "main.rs",
    ],
)
```

## WORKSPACE.bazel
```python
workspace(name = "output")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_rust",
    sha256 = "18c0a02a007cd26c3f5b4d21dc26a80af776ef755460028a796bc61c649fdf3f",
    strip_prefix = "rules_rust-467a301fd665db344803c1d8a2401ec2bf8c74ce",
    urls = [
        "https://github.com/bazelbuild/rules_rust/archive/467a301fd665db344803c1d8a2401ec2bf8c74ce.tar.gz",
    ],
)

load("@rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories()
```

## main.rs
```rust
fn main() {
    println!("ok"
}
```

**Comment by Ubehebe** [comment]
Update: I think this has something to do with `--ui_event_filters`, which I set in my downstream repo's .bazelrc:

```
build --ui_event_filters=-DEBUG,-INFO
```

I notice that the error message you reported [above](https://github.com/bazelbuild/rules_rust/issues/708#issuecomment-826376762) is at level INFO, which seems inappropriate (why not ERROR?). I think Bazel may try to surface the rustc stdout/stderr at the INFO level based on the erroneous exit status reported by the process wrapper.

If true, this would explain why no one else has reported missing compilation errors: no one else sets `--ui_event_filters`. The PR should still be merged in this case, since it will allow me to use rules_rust productively while still turning off INFO messages.

**Comment by UebelAndre** [comment]
I think that'd explain it. I haven't set `--ui_event_filters` on my project before. Then that being said, I think the PR makes sense.

**Comment by hlopko** [comment]
Great investigation and PR! Thank you!
