### ISSUE TITLE
`@rules_rust//tools/rustfmt` only runs on built targets

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#749]
I noticed if I run `bazel clean`, then intentionally ruin formatting in a source file for one of my rust targets, then run `bazel run @rules_rust//tools/rustfmt`, that my target isn't formatted. In fact, no target is formatted. Under the hood, that binary is running a bazel build command with the following arguments:
https://github.com/bazelbuild/rules_rust/blob/d6cf2ec939c1eff9f6601588468146cf72c97e5b/tools/rustfmt/srcs/main.rs#L78-L80

My thought was `--output_groups=rustfmt_manifest` would tell bazel that this is the only target that needs to be produced and only do work to generate that. But alas, no manifest is generated. Is there something I'm missing about the use of [output_groups](https://docs.bazel.build/versions/master/command-line-reference.html#flag--output_groups)? I thought this would work

**Comment by UebelAndre** [comment]
@hlopko do you have any thoughts on why this might be the case? 😅

**Comment by hlopko** [comment]
1) Can you share a reproduction repository if you have one, and share the exact bazel invocations that lead to the bug?
2) My guess would be that `query_rustfmt_targets` returns empty list or something in that direction.
3) Am I understanding you correctly that if you do `bazel build //:some_rust_binary && bazel run @rules_rust//tools/rustfmt`, files are reformatted, but when you stick `bazel clean between those (`bazel build //:some_rust_binary && bazel clean && bazel run @rules_rust//tools/rustfmt`) files are no longer reformatted?

**Comment by hlopko** [comment]
> There is a difference between CrateInfo coming from @rules_rust and //

What kind of difference? Targets coming from `@rules_rust` don't have `CrateInfo` and targets coming from `//` do? Or something else? Both are surprising to me.

**Comment by UebelAndre** [comment]
Sorry for the delay here.

With this diff, if you `bazel build --config=rustfmt //...` from the root of the repo, you'll run into an error
```diff
diff --git a/.bazelrc b/.bazelrc
index db9695b..a61cbe3 100644
--- a/.bazelrc
+++ b/.bazelrc
@@ -2,5 +2,5 @@
 # https://docs.bazel.build/versions/master/best-practices.html#using-the-bazelrc-file

 # Enable rustfmt for all targets in the workspace
-build:rustfmt --aspects=//rust:defs.bzl%rustfmt_aspect
+build:rustfmt --aspects=@rules_rust//rust:defs.bzl%rustfmt_aspect
 build:rustfmt --output_groups=+rustfmt_checks
diff --git a/rust/private/rustfmt.bzl b/rust/private/rustfmt.bzl
index 9c59f48..789791a 100644
--- a/rust/private/rustfmt.bzl
+++ b/rust/private/rustfmt.bzl
@@ -13,6 +13,11 @@ def _find_rustfmtable_srcs(target, aspect_ctx = None):
     Returns:
         list: A list of formattable sources (`File`).
     """
+
+    if aspect_ctx and aspect_ctx.rule.kind in ["rust_library", "rust_binary", "rust_test"]:
+        print(target)
+        crate_info = target[rust_common.crate_info]
+
     if rust_common.crate_info not in target:
         return []
```

This is that error
```
DEBUG: /Users/user/Code/rules_rust/rust/private/rustfmt.bzl:18:14: <target //tools/runfiles:runfiles, keys:[CrateInfo, DepInfo, CcInfo, OutputGroupInfo]>
ERROR: /Users/user/Code/rules_rust/tools/runfiles/BUILD.bazel:8:13: in @rules_rust//rust/private:rustfmt.bzl%rustfmt_aspect aspect on rust_library rule //tools/runfiles:runfiles:
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_user/76282c66b0dfe3c5cb9a230bdc913a52/external/rules_rust/rust/private/rustfmt.bzl", line 83, column 34, in _rustfmt_aspect_impl
		srcs = _find_rustfmtable_srcs(target, ctx)
	File "/private/var/tmp/_bazel_user/76282c66b0dfe3c5cb9a230bdc913a52/external/rules_rust/rust/private/rustfmt.bzl", line 19, column 28, in _find_rustfmtable_srcs
		crate_info = target[rust_common.crate_info]
Error: <target //tools/runfiles:runfiles> (rule 'rust_library') doesn't contain declared provider 'CrateInfo'
ERROR: Analysis of aspect '@rules_rust//rust:defs.bzl%rustfmt_aspect of //tools/runfiles:runfiles' failed; build aborted: Analysis of target '//tools/runfiles:runfiles' failed
```

I forget what the failure mode was that lead me to an error message that lead me to find this works from the repo root if `@rules_rust` is omitted but I think that's a straight forward enough reproduction of the issue. I think I should be able to use the following diff and have everything continue to work.
```diff
diff --git a/.bazelrc b/.bazelrc
index db9695b..a61cbe3 100644
--- a/.bazelrc
+++ b/.bazelrc
@@ -2,5 +2,5 @@
 # https://docs.bazel.build/versions/master/best-practices.html#using-the-bazelrc-file

 # Enable rustfmt for all targets in the workspace
-build:rustfmt --aspects=//rust:defs.bzl%rustfmt_aspect
+build:rustfmt --aspects=@rules_rust//rust:defs.bzl%rustfmt_aspect
 build:rustfmt --output_groups=+rustfmt_checks
```
Unfortunately, it doesn't and `@rules_rust` must be dropped to get the aspect to function in the root of `rules_rust`.

**Comment by hlopko** [comment]
Oh that's a Bazel bug. I just found https://github.com/bazelbuild/bazel/issues/11734.

**Comment by UebelAndre** [comment]
Ah, neat. Should I close this issue then?

**Comment by hlopko** [comment]
Yeah let's do that.

Bazel team, if you're reading this, this is not resolved, we are just using a workaround and we don't want to keep the issue open only to wait for the fix in Bazel :)
