### ISSUE TITLE
Problems building in WSL Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by crusty-dave** [bazelbuild/rules_rust#765]
I am getting an  (Permission denied) during the extract, I have tried Rust version 1.47.0, 1.50.0 & 1.52.0 with the same result.  It seems to get quite far into the extraction before it hits the error.  I am building with bazel 3.6.0.  I tried running under sudo bash as well with the same issue.

```
(22:29:58) INFO: Repository rust_linux_x86_64 instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule rust_toolchain_repository defined at:
  /home/username/.cache/bazel/_bazel_username/a54ac4c9cd8c7407de9707a8bbb94397/external/rules_rust/rust/repositories.bzl:626:44: in <toplevel>
(22:29:58) ERROR: An error occurred during the fetch of repository 'rust_linux_x86_64':
   Traceback (most recent call last):
        File "/home/username/.cache/bazel/_bazel_username/a54ac4c9cd8c7407de9707a8bbb94397/external/rules_rust/rust/repositories.bzl", line 591, column 65, in _rust_toolchain_repository_impl
                build_components = [_load_rust_compiler(ctx), _load_rust_src(ctx)]
        File "/home/username/.cache/bazel/_bazel_username/a54ac4c9cd8c7407de9707a8bbb94397/external/rules_rust/rust/repositories.bzl", line 502, column 16, in _load_rust_src
                ctx.extract(
Error in extract: java.io.IOException: Error extracting /home/username/.cache/bazel/_bazel_username/a54ac4c9cd8c7407de9707a8bbb94397/external/rust_linux_x86_64/rustc-1.52.0-src.tar.gz to /home/username/.cache/bazel/_bazel_username/a54ac4c9cd8c7407de9707a8bbb94397/external/rust_linux_x86_64: /home/username/.cache/bazel/_bazel_username/a54ac4c9cd8c7407de9707a8bbb94397/external/rust_linux_x86_64/lib/rustlib/src/src/llvm-project/clang/test/CXX/over/over.match/over.match.best (Permission denied)
```

BUILD.bazel:

```
load("@rules_rust//rust:rust.bzl", "rust_binary")

rust_binary(
    name = "simple-test",
    srcs = ["src/main.rs"],
)
```

**Comment by UebelAndre** [comment]
What are the permissions of the file?

**Comment by crusty-dave** [comment]
The file doesn't pre-exist, which is why it is odd that it is complaining about a permission denied.  It seems to have created over.match.funcs & over.match.viable, so not sure why it cannot create over.match.best?

```
ls -l /home/username/.cache/bazel/_bazel_username/a54ac4c9cd8c7407de9707a8bbb9439
7/external/rust_linux_x86_64/lib/rustlib/src/src/llvm-project/clang/test/CXX/over/over.match/
total 0
drwxr-xr-x 1 username username 4096 Jun  8 22:29 over.match.funcs
drwxr-xr-x 1 username username 4096 Jun  8 22:29 over.match.viable
ls -l /home/username/.cache/bazel/_bazel_username/a54ac4c9cd8c7407de9707a8bbb94397/external/rust_linux_x86_64/lib/rustlib/src/src/llvm-project/clang/test/CXX/over/
total 0
drwxr-xr-x 1 username username 4096 Jun  8 22:29 over.built
drwxr-xr-x 1 username username  4096 Jun  8 22:29 over.match
drwxr-xr-x 1 username username 4096 Jun  8 22:29 over.oper

```

**Comment by hlopko** [comment]
CC @meteorcloudy (who regularly saves me when it comes to anything Windows-y :) just in case this is a known issue in Bazel.

**Comment by meteorcloudy** [comment]
Ah.. looks like you are running the Linux version of Bazel on Windows in WSL. Bazel is never tested in WSL and doesn't support it officially, so it's likely there will be errors like this.
Is it an option to run the native Windows version of Bazel?

**Comment by crusty-dave** [comment]
@meteorcloudy - unfortunately no.  I need an Ubuntu build and due to firewall policies, the only current option is with WSL on my laptop.

**Comment by hlopko** [comment]
Does it sound like an issue with Bazel, and not with the rules? I think so. Could you create an issue at github.com/bazelbuild/bazel?

**Comment by crusty-dave** [comment]
I happened to be looking at my McAfee logs today and I found the following:

<user> ran C:\Users\<user>\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\<user>\.cache\bazel\_bazel_<user>\install\4c21e876de560d3ed6010a2e5e2f9074\embedded_tools\jdk\bin\java, which tried to access C:\Users\<user>\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu20.04onWindows_79rhkp1fndgsc\LocalState\rootfs\home\<user>\.cache\bazel\_bazel_<user>\a54ac4c9cd8c7407de9707a8bbb94397\external\rust_linux_x86_64\lib\rustlib\src\src\llvm-project\clang\test\CXX\over\over.match\over.match.best, violating the rule "Blocked Bad File Extensions", and was blocked. For information about how to respond to this event, see KB85494.

I haven't tried any remediation yet, I will post here when I do.

**Comment by crusty-dave** [comment]
Our IT guy who deals with McAfee updated my rules to ignore .best files and now it builds!

Closing this issue, thanks to everyone who looked at it.
