### ISSUE TITLE
Why don't other rules use `_allowlist_function_transition`

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#767]
Or more specifically, do the other rules support [transitions](https://docs.bazel.build/versions/4.1.0/skylark/config.html#user-defined-transitions)?

Semi-related to https://github.com/bazelbuild/rules_rust/issues/276 since I'm interested in cross-compilation.

**Comment by UebelAndre** [comment]
cc @hlopko

**Comment by hlopko** [comment]
All the rules work under transitions. What is special about `rust_wasm_bindgen` is that the rule itself performs the transition when analyzing `wasm_file` attribute (the target passed as this attribute will be built with a different configuration than the `rust_wasm_bindgen`). Transitions are quite a special hammer that is rarely needed. And we currently don't need it for the core Rust rules.

Configuration transitions have the potential to explode Bazel memory, cpu, and execution times if used incorrectly. `_allowlist_function_transition` is a way to limit usage of the transition when you want to be careful. If the rule doesn't use a transition this attribute is useless.

But yeah when the need arises, we can use transitions with core Rust rules just fine.
