### ISSUE TITLE
Support for custom targets

### ISSUE THREAD

**Issue by davidskidmore** [bazelbuild/rules_rust#770]
I'm having difficulty using bazel with a [custom target](https://doc.rust-lang.org/rustc/targets/custom.html) based on `x86_64-unknown-linux-gnu`. In theory, given a simple library:

```rust
#![no_std]

#[no_mangle]
pub extern "C" fn rust_function() {}
```

After [bootstrapping](https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html) libcore and friends I can now build the library for my new target:

```sh
rustc --crate-type=lib foo.rs --target x86_64-unknown-none.json \
  -L dependency=~/rust_libs/ \
  --extern 'noprelude:core=~/rust_libs/libcore-7363d577ba15c1d7.rmeta' \
  --extern 'noprelude:compiler_builtins=~/rust_libs/libcompiler_builtins-b774e5dde03423fb.rmeta' \
  -Z unstable-options
```

I'm aware of how to accomplish the cross build with cargo, but I'm not sure how to do this with bazel. There doesn't seem to be a way for me to pass my target JSON through a new `rust_toolchain` definition.

**Comment by hlopko** [comment]
So AFAIU the request is to add a way to pass `target.json` to the `rust_toolchain`. That's quite a simple change, and I'd say not very controversial. @davidskidmore, do you want to give creating a PR a try?

**Comment by davidskidmore** [comment]
I've tried hacking something together, but haven't been able to get something working that will both accept the new json as a target and successfully use my prebuilt libraries.

**Comment by davidskidmore** [comment]
I have successfully built and linked my own libraries, and created #836 to show my approach in adding support for passing a custom target specification. I can't tell if this is the "right" way, so let me know if you have any feedback.
