### ISSUE TITLE
rust_test example code is incorrect, and should be run under doctest

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/rules_rust#777]
The current docs run assert_eq on a function that returns `()`.

current docs for `rust_test`:

```
pub struct Greeter {
    greeting: String,
}

impl Greeter {
    pub fn new(greeting: &str) -> Greeter {
        Greeter { greeting: greeting.to_string(), }
    }

    pub fn greet(&self, thing: &str) {
        println!("{} {}", &self.greeting, thing);
    }
}

#[cfg(test)]
mod test {
    use super::Greeter;

    #[test]
    fn test_greeting() {
        let hello = Greeter::new("Hi");
        assert_eq!("Hi Rust", hello.greet("Rust"));
    }
}
```
fixed:

```
pub struct Greeter {
    greeting: String,
}

impl Greeter {
    pub fn new(greeting: &str) -> Greeter {
        Greeter { greeting: greeting.to_string(), }
    }

    pub fn greet(&self, thing: &str) -> String {
        format!("{} {}", &self.greeting, thing)
    }
}

#[cfg(test)]
mod test {
    use super::Greeter;

    #[test]
    fn test_greeting() {
        let hello = Greeter::new("Hi");
        assert_eq!("Hi Rust", hello.greet("Rust"));
    }
}
```

**Comment by UebelAndre** [comment]
Nice catch! Would you be willing to throw that up in a PR? 🙏 😄

**Comment by sayrer** [comment]
What would be the best way to run it under the equivalent of `doctest`, so it doesn't break again?

**Comment by UebelAndre** [comment]
Hmmm, I don't think we have something like that. The documentation is written in a starlark docstring... I suppose we could add some functionality to render that into a file and build+test that but I don't know how volatile these docs are. If there's an easy and clean way to generate a test for it I think that'd be awesome but i suspect it's likely to be more effort than it's worth.
