### ISSUE TITLE
crate_universe doesn't support target-specific dependencies

### ISSUE THREAD

**Issue by sayrer** [bazelbuild/rules_rust#783]
Something like this:

```
[dependencies]
lazy_static = { version = "1.4.0" }

[target.'cfg(any(target_os = "android", target_os = "linux"))'.dependencies]
libc = { version = "0.2.84", default-features = false }
```

I get what looks like a serde error of this sort:

```
Caused by:
    unknown field `target` at line 370 column 1
```

**Comment by sayrer** [comment]
An example would be socket2-0.3.19.

`cargo raze` produces [selects for cfg](https://github.com/google/cargo-raze/blob/ee11d8a784eea867fafcc3f4e7289eb1f101597f/third_party/cargo/remote/BUILD.socket2-0.3.19.bazel) sections.

**Comment by illicitonion** [comment]
This should be ~trivial to implement, it just requires us to round-trip these fields from the `Cargo.toml` into the one we generate - I'll try to take a look soon :)

**Comment by illicitonion** [comment]
I started on this, and actually I think we should block this on https://github.com/bazelbuild/rules_rust/issues/700 - hopefully we'll get to it soon!

**Comment by UebelAndre** [comment]
With https://github.com/bazelbuild/rules_rust/issues/700 closed, is this issue also resolved? @illicitonion @sayrer?

**Comment by sayrer** [comment]
I think this is ok to close, I filed this when crate_universe was very new. Up to you, I'd say.

**Comment by illicitonion** [comment]
Yeah, pretty sure this got done fine :)
