### ISSUE TITLE
Latest release doesn't use depset

### ISSUE THREAD

**Issue by jglievano** [bazelbuild/rules_rust#80]
`set` is now deprecated in favor of `depset`. The git repo has these changes but importing the latest release with http_archive (0.0.5) is still not updated.

**Comment by acmcarther** [comment]
I just cut a new release (0.0.6) from master:

https://github.com/bazelbuild/rules_rust/releases/tag/0.0.6

**Comment by jglievano** [comment]
Shouldn't the documentation be updated to use 0.0.6?
