### ISSUE TITLE
Make darwin a supported host platform

### ISSUE THREAD

**Issue by hlopko** [bazelbuild/rules_rust#837]
From https://github.com/bazelbuild/rules_rust/pull/832#discussion_r669868748

![image](https://user-images.githubusercontent.com/814566/125737397-130ce941-663e-4f62-b4d7-16e1c1d1fcbf.png)

**Comment by hlopko** [comment]
CC @UebelAndre

**Comment by illicitonion** [comment]
Just to check - @hlopko, what is your proposed end-criteria for this issue? AFAICT the two things I've seen are:
1. All of our tests run on the platform (which is true for macos [except for one which is blocked on bazel 4.2.0](https://github.com/bazelbuild/rules_rust/blob/a814d859845c420fd105c629134c4a4cb47ba3f8/.bazelci/presubmit.yml#L34-L35))
2. One of the maintainers is invested in keeping the above true

Does that sound about right? If so, are there any concrete blockers to this today?

**Comment by hlopko** [comment]
For macos I'm not aware of any blockers. If you say you have the will and capacity to (from the top of my head, without any clear structure or anything, not even trying to be complete):

* Make sure the rules are usable on the platform (for example
  * does debugging work on macos?
  * can you build Rust binary which has C++ library as a dependency?
  * can you create and use a Rust "framework"?
* Figure out which Xcode versions you want to support
* Keep an eye on macos specific issues, help debug/resolve them
* Contribute macos expertise in design discussions

Then I'd just flip the bit and call it a supported platform. I'm less worried about supporting darwin than windows.

**Comment by illicitonion** [comment]
Yeah, I can sign up to that (assuming we're reasonably happy to decide most of these things as they come up, rather than proactively) :) Let's flip that bit!

**Comment by hlopko** [comment]
SGTM! Will update the policy doc.
