### ISSUE TITLE
crate aliases not supported

### ISSUE THREAD

**Issue by rbtcollins** [bazelbuild/rules_rust#852]
Ran into this failure:
```
error[E0433]: failed to resolve: use of undeclared crate or module `bytes_05`
   --> external/raze__async_compression__0_3_8/src/stream/macros/encoder.rs:58:41
    |
58  |             type Item = std::io::Result<bytes_05::Bytes>;
    |                                         ^^^^^^^^ use of undeclared crate or module `bytes_05`
    | 
   ::: external/raze__async_compression__0_3_8/src/stream/mod.rs:152:1
    |
```

The underlying cause can be found in async_compression's Cargo.toml: https://github.com/Nemo157/async-compression/blob/pr%C4%ABmum/Cargo.toml#L41
```
bytes-05 = { package = "bytes", version = "0.5.0", optional = true }
```

There was a dependency I was adding to reqwest 0.10, which uses async-compression with bytes-05 feature enabled, and that triggers the bug.

**Comment by illicitonion** [comment]
This is an issue with cargo-raze, rather than rules_rust itself (which I think _may_ be addressed by https://github.com/google/cargo-raze/pull/425) - I think this is a dupe of https://github.com/google/cargo-raze/issues/424?

**Comment by rbtcollins** [comment]
I'll re-file on raze, sorry for putting it in the wrong place. I don't think it is a dupe: 424 is about a an error case that cargo considers an error; this is about an error case that cargo considers success but bazel fails on.

**Comment by rbtcollins** [comment]
google/cargo-raze#113 is nearly a dupe, except that this is up a level: crate a -> reqwest 0.10.10 -> bytes-with-features.

**Comment by hlopko** [comment]
I think what @illicitonion meant was that the fix for this will happen in raze, not in this repository, so the issue should be filed over there. AFAIU there's nothing we need to do in the rules_rust, right?

**Comment by rbtcollins** [comment]
yes, got that - sorry I didn't close this when I opened on the other repo.
