### ISSUE TITLE
glibc version not included as a dependency 

### ISSUE THREAD

**Issue by rbtcollins** [bazelbuild/rules_rust#854]
Ubuntu 21.04 has glibc 2.33. Rust programs built on a 21.04 host end up with versioned symbols.

The cc image in the docker_rules repository includes a glibc version 2.31 (I think). Thus the resulting docker image is nonfunctional.

I'm still new to bazel but AIUI (and generalising a bit here from other systems), we should be able to have both the cc image and the rust binary depend on the same glibc binary as a target.

The strict requirement is just that the version in the image must be newer than the one the binary is built with, but matching is acceptable.

**Comment by djmarcin** [comment]
This isn't really a rules_rust issue, it's a toolchain issue -- I believe if you built a `cc_binary` on this system that linked against glibc you'd see the same issue. Sadly the most straightforward way to get an older version of glibc working is to build on a system with an older version of glibc. You _can_ configure a toolchain that uses a specific version of glibc instead of what's installed on the system, but toolchain configuration is fairly complicated (I've given up more than once 😭)

**Comment by rbtcollins** [comment]
@djmarcin yes, I imagine a cc_binary would have the same problem. So where should I take this bug?

To systematically fix this we could 
* have the cc_image have the latest glibc and rev quickly.
* have building glibc and providing hermetic behaviour against that be an out of the box capability that toolchains support
* default to using docker_execution rules for building rust targets, or perhaps document that thats needed and provide pointers?
* <...>?

**Comment by djmarcin** [comment]
The most expedient ways to fix your immediate problem are probably either 1) specify a different base image for your docker container that has a compatible version of glibc, or 2) build on a machine with an older version of glibc.

A toolchain helper for hermetic glibc would probably be useful, but it seems outside the scope of rules_rust. I’m not sure what you mean by defaulting to using docker for building rust targets, but maybe a project like dazel that lets you execute bazel in a container (where you could control the glibc version separate from your system version) would be helpful?

**Comment by rbtcollins** [comment]
Thank you. Referring to docker I meant something like https://docs.bazel.build/versions/main/remote-execution-sandbox.html#prerequisites

Anyhow, I'll follow the tips from here; whether you want to keep a note open as a backlog bug or close it is up to you.

**Comment by hlopko** [comment]
Thank you both for a nice informative discussion! I think we don't plan to address this in rules_rust, so I'll close this.
