### ISSUE TITLE
tools fetched from upstream rust static repo even when override URL template is provided

### ISSUE THREAD

**Issue by wt** [bazelbuild/rules_rust#867]
My WORKSPACE for the rules_rust looks like this:

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "rules_rust",
    path = "/Users/wturkal/projects/rust/rules_rust",
)

load("@rules_rust//rust:repositories.bzl", "rust_repositories")

rust_repositories(
    version="1.54.0",
    urls=[
        "https://{internal_mirror_site}/generic-3rdparty-local/bazel/build-support/rust/toolchains/1.54.0/{}.tar.gz"
    ],
)
```

When running a build, it still fetches from the default rust upstream location (i.e. "https://static.rust-lang.org/..."). This happens because the urls provided in my workspace config are just appended to a list whose first entry is always the default site. See https://github.com/bazelbuild/rules_rust/blob/main/rust/private/repository_utils.bzl#L529-L535 for the relevant code.

I think that the code should only add the default location iff urls are not specified.

**Comment by illicitonion** [comment]
This sounds very reasonable - if people really want the current behaviour, it's easy for them to re-add the default value.

Can I tempt you to put together a PR?

Thanks!

**Comment by wt** [comment]
You can. I am working on making sure I have appropriate permission from my company. We already have a corp CLA with you.

**Comment by wt** [comment]
Permission granted. :)
