### ISSUE TITLE
`rust_doc_test` targets are currently broken on windows

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#887]
A change to the Bazel CI windows runners broke the `rust_doc_test` targets currently defined in the repo. This issue tracks fixing these.

Related to:
- https://github.com/bazelbuild/continuous-integration/issues/1201

**Comment by UebelAndre** [comment]
I've opened https://github.com/bazelbuild/rules_rust/pull/888 to disable the tests while a solution is found. This way other PRs are not blocked.

**Comment by UebelAndre** [comment]
Currently RBE also does not work with `rust_doc_test`. I suspect that a solution to making RBE work would also fix the issues we're seeing with windows.

**Comment by sayrer** [comment]
Yes, see also: https://github.com/bazelbuild/rules_rust/issues/845

**Comment by sayrer** [comment]
I suspect the problem is here:

https://github.com/bazelbuild/rules_rust/blob/dd1c73e232ef5e1e8bf5c08e93c6fff557e18077/rust/private/rustdoc.bzl#L101

but I haven't had time to investigate further.

**Comment by UebelAndre** [comment]
This rule is unlike any rule in that it is compiling rust within a test. To try and make it clearer:
| build | execution |
| --- | --- |
| generate bash/batch script | run script -> build+run doc tests |

I suspect the issue is that the test environment is not the same as the sandboxed action environment that `rustc` normally runs in (or even `rustdoc` for the `rust_doc` rule).

I think the fix is either compile the tests in an action (but not run them) using the [--no-run](https://github.com/rust-lang/rust/issues/87022) feature so that the test execution is just running the test binary. I'd expect this to shape out like:
| build | execution |
| --- | --- |
| rustdoc --no-run --persist-doctests ${CRATE} | run ${CRATE}.doc_test |

Unfortunately, this is a nightly feature so not something that can be done now. The alternative is to figure out how to create a process-wrapper for the test that ensures the environment is sufficient for building and running the tests. This is probably the better path forward since it'd be backwards compatible (not needing the nightly flag) but I don't know how to do that...

**Comment by sayrer** [comment]
Given #845, I suspect we could do 

```
ctx.actions.run {
  ...
  env = {
    "CC": "...something from the toolchain..."
  }
  ...
}
```

It looks like we're hitting the [tool resolution](https://github.com/rust-lang/rust/blob/a28109a7679fbb254ca0962865a8b32b91ddbbd9/src/bootstrap/cc_detect.rs#L1) described in rustc (or similar logic in the `cc` crate.

**Comment by UebelAndre** [comment]
I spent last weekend trying a few things but didn't come up with anything that worked 😞 I'm happy to collaborate on more ideas though! 

I did try setting `CC` but ran into more issues on https://github.com/bazelbuild/rules_rust/pull/882

Feel free to take a look and I'm happy to try and answer any questions. But feeling kinda stumped on this issue... 😞

**Comment by sayrer** [comment]
I see. Looking at #882, I don't think `find_sysroot` is doing the right thing. I don't have more time to look for a few days, but happy to work on this.

**Comment by UebelAndre** [comment]
> I see. Looking at #882, I don't think `find_sysroot` is doing the right thing. I _think_ sysroot should be a directory containing the typical Unix root paths. Something like this: https://github.com/grafica/build/tree/main/sysroots/debian_sid_amd64-sysroot

`sysroot` in that case is a Rust sysroot which is expected to be passed to [rustc --sysroot](https://doc.rust-lang.org/rustc/command-line-arguments.html#--sysroot-override-the-system-root). There's another section which sets the `SYSROOT` environment variable from the `cc_toolchain`.

> I don't have more time to look for a few days, but happy to work on this.

I'd absolutely love the help 🤩  feeling stuck on this one...

**Comment by UebelAndre** [comment]
As mentioned earlier, I think fixing the sandboxing issues would likely solve for the issue here (which would close https://github.com/bazelbuild/rules_rust/issues/804).
