### ISSUE TITLE
Version 0.0.1 fails on 

### ISSUE THREAD

**Issue by djrenren** [bazelbuild/rules_rust#9]
Version 0.0.1 fails on bazel 0.2.3.

The fixes from this PR are required: https://github.com/bazelbuild/rules_rust/pull/6

Please tag a new release.

**Comment by davidzchen** [comment]
Thanks for reporting this. I will tag a new release once bazelbuild/rules_rust#10 is merged.

**Comment by davidzchen** [comment]
Just tagged release 0.0.2: https://github.com/bazelbuild/rules_rust/releases/tag/0.0.2
