### ISSUE TITLE
`crate_universe` fails on renamed dependencies

### ISSUE THREAD

**Issue by shikhar** [bazelbuild/rules_rust#904]
Cargo supports renaming the package when specifying dependencies, see https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml

`crate_universe` fails on such a rename:

```
Error: Error parsing "......./Cargo.toml"

Caused by:
    unknown field `package`, expected one of `default-features`, `features`, `version`, `git`, `rev`, `tag`, `path`, `optional` for key `dependencies.foobar` at line 27 column 18
```

**Comment by UebelAndre** [comment]
@shikhar Is this still happening? Can you provide a small repro if so?

**Comment by UebelAndre** [comment]
Closing this out since it seems https://github.com/bazelbuild/rules_rust/issues/1027 was the root cause.
