### ISSUE TITLE
FR: Add tonic/prost rules

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#915]
This is a fairly common request. It would be nice if there were some [tonic](https://crates.io/crates/tonic)/[prost](https://crates.io/crates/prost) rules in the `@rules_rust//proto` package since the existing rules there are using the [protobuf-rs](https://crates.io/crates/protobuf) crate which only supports a (now) [3 year old version of protobuf](https://github.com/protocolbuffers/protobuf/tree/b5fbb742af122b565925987e65c08957739976a7) (see https://github.com/stepancheg/rust-protobuf/issues/518).

**Comment by UebelAndre** [comment]
Right now there are two drafts for adding these rules:
- https://github.com/bazelbuild/rules_rust/pull/595
- https://github.com/bazelbuild/rules_rust/pull/479

As of right now, they're both pretty dated and likely will not work with the [current](https://github.com/bazelbuild/rules_rust/commit/e2f1ab9156e0ebff7f3bae64407efe3d320487e8) rev of the rules. Hopefully this effort is revived 😄

**Comment by UebelAndre** [comment]
Hopefully, for folks looking to use a modern version of protobuf for proto generation, `tonic`/`prost` rules can satisfy this need since the existing proto rules do not (https://github.com/bazelbuild/rules_rust/issues/302 - blocked by https://github.com/stepancheg/rust-protobuf/issues/518).

**Comment by shikhar** [comment]
Even without tonic/prost rules, which would certainly make for less boilerplate, it's not too bad. https://github.com/shikhar/bazel-tonic is an example project I created that entirely uses `rules_rust`. codegen via https://github.com/shikhar/bazel-tonic/blob/main/src/protogen/BUILD

**Comment by GregBowyer** [comment]
I _think_ it might be better to not have these in rules_rust but rather in `rules_grpc_proto`.

I have rules that can live in there in the works.

**Comment by UebelAndre** [comment]
I'd welcome it! I think it'd be better to keep proto/grpc rules all together. Even if they're for different languages.

**Comment by aaliddell** [comment]
Oh hi, I stubled across this from your cross-link :wave: 

I'm stuck at the moment with Tonic/Prost support in rules_proto_grpc since they don't have protoc plugins available and instead require you use their own generation method that itself wraps protoc. It seems there were previously plugins and could be again in the future if there's demand. Otherwise I may have to figure out a way to wrap their generation method in a pseudo-plugin just to satisfy protoc, similar to what was done in those links above.

**Comment by GregBowyer** [comment]
Its not plugins that were previously available, its more we are all on the bleeding edge.

You are waiting on this https://github.com/tokio-rs/prost/pull/492.

I am going to try to push up my rules as they are for getting that working, there is some abuse of patch in cargo-raze to pull a few small tweaks to let things work.

I am going to look at what @Tuetuopay has done w.r.t a single lib.rs for this (its not needed fully for rules_gprc, but I think its a generally good change), along with some tweaks to see if descriptors can be included for grpc-reflection.

**Comment by UebelAndre** [comment]
@GregBowyer is https://github.com/tokio-rs/prost/pull/492#issuecomment-966474758 meaningful info for you? If the changes there were to go in a separate crate, would it still be possible to use them to write prost/tonic rules?

**Comment by Sollimann** [comment]
I'm unable to use `tonic_build` with `prost` to generate stubs for my clients and serves when running my `build.rs` file. @shikhar https://github.com/shikhar/rules-rust-playground/tree/bazelify is this the solution to make it work? :thinking:

**Comment by Sollimann** [comment]
I have an alternative fix. It's not optimal, but this is a blocking issue for me, so I needed some way past it. First you like you always would with `cargo build` / `cargo build --release`. Normally when you `build.rs` file executes, the files go to the `/target` folder. Now, this didn't seem to work for me when using Bazel. So I figured that instead of having Bazel build the gRPC stubs and proto's, I'd rather do that with cargo, but I generate the stubs inside my `/src` folder instead of `/target` -folder. It works for me atleast.

```
cargo/
proto/
------ myproto.proto
src/
----- rust/
----------- mod.rs
----------- myproto.rs
----- lib.rs
BUILD.bazel
Cargo.toml
build.rs
```

build.rs
```rust
use std::fs;
use std::path::Path;
const PROTO_OUT_DIR: &str = "./src/rust";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    if Path::new(PROTO_OUT_DIR).is_dir() {
        fs::remove_dir_all(PROTO_OUT_DIR)?;
    }

    fs::create_dir(PROTO_OUT_DIR).expect("Failed to create out dir");
    fs::write(
        format!("{}/mod.rs", PROTO_OUT_DIR),
        "pub mod sensors_service;",
    )?;

    let files = vec!["proto/sensors_service.proto"];
    let includes = vec!["proto"];

    tonic_build::configure()
        .build_client(true)
        .build_server(true)
        .format(true)
        .out_dir(PROTO_OUT_DIR)
        .compile(&files, &includes)?;
    Ok(())
}
```
Cargo.toml
```toml

[package]
name = "protos"
version = "0.1.0"
authors = ["sollimann <user@myemail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = { version = "0.4", features = ["prost"] }
prost = "0.7"
prost-types = "0.7"
serde = { version = "1.0", features = ["derive"] }


[build-dependencies]
tonic-build = "0.4"
prost-build = "0.7"
```
BUILD.bazel
```bazel
load("@rules_rust//rust:defs.bzl", "rust_library")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "protos",
    srcs = glob(["**/*.rs"]),
    # crate_features = [
    #     "default",
    #     "std",
    # ],
    crate_root = "src/lib.rs",
    data = [],
    edition = "2021",
    rustc_flags = [
        "--cap-lints=allow",
    ],
    version = "0.1.0",
    visibility = [
        # had to add this line to be able to add /protos ass dep to grpc-connector-service
        "//services/grpc-connector-service:__subpackages__",
    ],
    deps = [
        "//protos/cargo:prost",
        "//protos/cargo:prost_build",
        "//protos/cargo:prost_types",
        "//protos/cargo:serde",
        "//protos/cargo:tonic",
        "//protos/cargo:tonic_build",
    ],
)
```

**Comment by UebelAndre** [comment]
https://github.com/tokio-rs/prost/pull/492#issuecomment-1079564170 seems like a relevant update to this thread

**Comment by Tuetuopay** [comment]
Popping in to let you know that I pushed [`protoc-gen-tonic`](https://github.com/Tuetuopay/protoc-gen-tonic), which can get handy.

**Comment by aidanalphafund** [comment]
Has anyone managed to get this to work with [protoc-gen-tonic](https://github.com/bazelbuild/rules_rust/issues/915#:~:text=that%20I%20pushed-,protoc%2Dgen%2Dtonic,-%2C%20which%20can%20get) and/or [protoc-gen-prost](https://github.com/Tuetuopay/protoc-gen-prost)?

**Comment by titanous** [comment]
I've implemented support for `protoc-gen-tonic` and `protoc-gen-prost` in https://github.com/rules-proto-grpc/rules_proto_grpc/pull/202.
