### ISSUE TITLE
rust_analyzer rule complains about no sources, even with `include_rustc_srcs`

### ISSUE THREAD

**Issue by Mythra** [bazelbuild/rules_rust#917]
👋  Thanks for all these rules! they've been incredibly helpful integrating Rust into our existing system. We're working through it, and trying to add in support for rust-analyzer.

To do this we've started adding rules for rust-analyzer, that are fairly simple, adding something simple like the following to our macros:

```starlark
  rust_analyzer(
    name = name + "-analyzer",
    targets = deps + [":" + name],
  )
```

Attempting to build these targets results in:

```
Error in fail: Current Rust toolchain doesn't contain rustc sources in `rustc_srcs` attribute. These are needed by rust analyzer. If you are using the default Rust toolchain, add `rust_repositories(include_rustc_srcs = True, ...).` to your WORKSPACE file.
```

However, when we look at our call to rust_repositories, we are passing that attribute:

```starlark
  bazel_toolchain_dependencies()
  llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "12.0.0",
  )
  rules_foreign_cc_dependencies()
  rust_repositories(include_rustc_srcs = True, edition = "2018", version = "1.54.0")
  cargo_raze_repositories()
  cargo_raze_transitive_deps()
  [...]
```

We are passing in this `include_rustc_srcs` attribute in. I Also noticed there was an environment variable: `RULES_RUST_TOOLCHAIN_INCLUDE_RUSTC_SRC`, manually setting this to: `export RULES_RUST_TOOLCHAIN_INCLUDE_RUSTC_SRC=1`, results in no change as well. I'm at a bit of a loss here, what can I do to tell rules_rust to include rustc_srcs so we can generate rust_analyzer rules?

**Comment by UebelAndre** [comment]
Hi! Sorry you're having troubles, this issue is odd indeed. Is there maybe another call to `rust_repositories` which is also defining toolchains? Though that seems unlikely to change anything if you're using `RULES_RUST_TOOLCHAIN_INCLUDE_RUSTC_SRC` which should apply to all `rust_repository_set` instances. Regardless, does applying the following diff have any impact?
```diff
diff --git a/rust/repositories.bzl b/rust/repositories.bzl
index f298a9a..ee61fcd 100644
--- a/rust/repositories.bzl
+++ b/rust/repositories.bzl
@@ -281,6 +281,10 @@ def rust_repository_set(
         urls (list, optional): A list of mirror urls containing the tools from the Rust-lang static file server. These must contain the '{}' used to substitute the tool being fetched (using .format). Defaults to ['https://static.rust-lang.org/dist/{}.tar.gz']
     """

+    # Early-out if the repository set is already defined
+    if name in native.existing_rules().keys():
+        return
+
     rust_toolchain_repository(
         name = name,
         exec_triple = exec_triple,
```

**Comment by Mythra** [comment]
Hey, thanks for the super quick reply!

There shouldn't be another call to `rust_repositories` coming before, our loading mechanism is split into 3 areas that are called from `WORKSPACE`.

- `preload`: which is just a series of `http_archive`, and `git_repository` rules but doesn't do anything else.
- `load`: which actually calls into those loaded http_archives
- `postload`: anything that depends on resources created in load.

In order to make debugging easier I've moved this stuff to the top of the 'load' phase (so the snippet I posted is run directly after all of our http_archive/git_repository 'fetches' which afaik cannot call rust_repositories), and as far as I could tell: ` bazel_toolchain_dependencies`, `llvm_toolchain`, and `rules_foreign_cc_dependencies` do not call `rust_repositories` anywhere.

I should also mention:

  - I'm using the latest commit of `rules_rust`.
  - I have been using `bazel clean --expunge` / building the binary / trying to build the rust_analyzer rule for the binary just to hopefully clear any sort of doubts.

---

As for applying the patch that seems to have worked 🎉 (even without the environment variable). Does that mean I have something wrong with my local working set which is why that return is needed?

**Comment by UebelAndre** [comment]
The call to [@cargo_raze//transitive_deps.bzl%cargo_raze_transitive_deps](https://github.com/google/cargo-raze/blob/v0.12.0/transitive_deps.bzl#L8) is also calling `rust_repositories` and appears to be triggering some undesirable behavior in toolchain resolution. If this solves your problem, I'd be happy to review a PR 😄

**Comment by Mythra** [comment]
I'd be happy to push up this patch, but is the better fix is for `cargo_raze` to not re-call rust_repositories? I'm not too familliar with how toolchains, and the like work, but just want to make sure we're making the best change rather than a small hack if it's possible.

**Comment by UebelAndre** [comment]
I think the correct fix is in is within `rules_rust`. As far as I know, without the use of [maybe](https://docs.bazel.build/versions/main/repo/utils.html#maybe) or some similar utility, the version of of a repository being used in your workspace will be inconsistent if defined multiple times. And I definitely do not know what the behavior is for registering multiple toolchains for the same platform. I think there's already a precedent for "the rule called first is the rule that defines the repository" and 'toolchain repositories' should be no different IMO. What do you think?

**Comment by UebelAndre** [comment]
Maybe this would be a better fix as it allows `rust_repository_set` to continue to behave exactly as other repository rules (more or less):
```diff
diff --git a/rust/repositories.bzl b/rust/repositories.bzl
index f298a9a..56efae8 100644
--- a/rust/repositories.bzl
+++ b/rust/repositories.bzl
@@ -96,7 +96,8 @@ def rust_repositories(
     )

     for exec_triple, name in DEFAULT_TOOLCHAIN_TRIPLES.items():
-        rust_repository_set(
+        maybe(
+            rust_repository_set,
             name = name,
             exec_triple = exec_triple,
             extra_target_triples = ["wasm32-unknown-unknown", "wasm32-wasi"],
```

**Comment by sayrer** [comment]
This is a bug in `cargo-raze`, I think. I added `include_rustc_srcs` to its `rust_repositories` call so I could use VSCode while hacking on it.

**Comment by sayrer** [comment]
See: https://github.com/google/cargo-raze/pull/444

**Comment by UebelAndre** [comment]
> This is a bug in `cargo-raze`, I think. I added `include_rustc_srcs` to its `rust_repositories` call so I could use VSCode while hacking on it.

I disagree. The decision to set `rust_repositories(include_rustc_srcs = True)` in your WORKSPACE file should always take affect no matter what else you load in your workspace (assuming the target you're building are actually using the toolchains it generates). If you then depend on repository `foo` and `bar` which both use `rules_rust` and have macros that call `rust_repositories` which you also load in your WORKSPACE file, I feel strongly that these should have no affect if the only thing they call is `rust_repositories()` (note, no arguments).

It definitely would be annoying not to have rust-analyzer support when working on `cargo-raze`, but this is a separate issue that should be filed on that project. I otherwise think the issue and fix for this are both in `rules_rust`.

Does that change any thoughts you have? 😅

**Comment by sayrer** [comment]
If both ways of approaching this issue are addressed, that's fine with me. I suspect I filed the `cargo-raze` issue above while you were writing your comment.
