### ISSUE TITLE
Build script executables not found on Windows

### ISSUE THREAD

**Issue by MatthieuCoder** [bazelbuild/rules_rust#926]
Hi! Today I ran into a problem while compiling many dependencies.
The cargo_build_script_runner.exe program seemed unable to execute the previously-built build script executables.
The error was a "The directory name is invalid." error

![image](https://user-images.githubusercontent.com/20992787/132096990-3d06b34a-3a8b-4a49-88de-fe4039339ea9.png)
 
I tracked down the error on windows and the problem seems to be a non-existent "manifest_dir" which causes an execution error (execution of a program from a directory that doesn't exist).

The problem only occurs on windows. 
I got it to work by removing [this line](https://github.com/bazelbuild/rules_rust/blob/main/cargo/cargo_build_script.bzl#L48) and replacing it by 
`
manifest_dir = "%s.runfiles" % (script.path)
`
And the build worked, same on Linux.

This seems like a bug to me, should a change like this be implemented or is there another way to fix the original error?

**Comment by UebelAndre** [comment]
Sorry to hear you're running I to build issues. Have you tried enabling symlinks per: https://docs.bazel.build/versions/main/windows.html#enable-symlink-support

**Comment by MatthieuCoder** [comment]
I'll try that!

**Comment by MatthieuCoder** [comment]
> Sorry to hear you're running I to build issues. Have you tried enabling symlinks per: https://docs.bazel.build/versions/main/windows.html#enable-symlink-support

It worked, thanks a lot!
