### ISSUE TITLE
`rust_doc` does not define `CARGO_MANIFST_DIR`

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/rules_rust#947]
I've had success using the following to consistently access files in both Cargo and Bazel builds (something prescribed in the [examples](https://github.com/bazelbuild/rules_rust/blob/75c63c36ab6a268d4de773437400d1d853723e84/examples/cargo_manifest_dir/external_crate/src/lib.rs)):
```rust
include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/path/to/file"));
```

Unfortunately, `CARGO_MANIFEST_DIR` is not defined in actions under [rust_doc](https://github.com/bazelbuild/rules_rust/blob/75c63c36ab6a268d4de773437400d1d853723e84/rust/private/rustdoc.bzl#L148-L198). I'm also not sure how to infer that information from a [CrateInfo](https://github.com/bazelbuild/rules_rust/blob/75c63c36ab6a268d4de773437400d1d853723e84/rust/private/providers.bzl#L17-L40) provider. Would love some ideas in how to define this or would like to know alternatives I could use for [include_str](https://doc.rust-lang.org/std/macro.include_str.html).

**Comment by dae** [comment]
For normal binaries/libs/tests, include_str!() references are relative to the file they fall in, so foo/bar.rs can reference baz/quux.txt with include_str!("../baz/quux.txt"). Is the doc code behaving differently?

**Comment by illicitonion** [comment]
This is how we set it for other things: https://github.com/bazelbuild/rules_rust/blob/75c63c36ab6a268d4de773437400d1d853723e84/rust/private/rustc.bzl#L396-L413

**Comment by UebelAndre** [comment]
> This is how we set it for other things:
> 
> https://github.com/bazelbuild/rules_rust/blob/75c63c36ab6a268d4de773437400d1d853723e84/rust/private/rustc.bzl#L396-L413

Yeah, It seems simple enough to expose `CARGO_MANIFEST_DIR` to the action but what is the value of it? What would represent the manifest dir? Seems like it'd be something on `CrateInfo` but I'm not sure what.

**Comment by UebelAndre** [comment]
> For normal binaries/libs/tests, include_str!() references are relative to the file they fall in, so foo/bar.rs can reference baz/quux.txt with include_str!("../baz/quux.txt"). Is the doc code behaving differently?

The issue is that Cargo and Bazel behave differently for those strings and it's valuable to me to support both (makes transitioning easy or even possible in some of my cases).

**Comment by illicitonion** [comment]
> > This is how we set it for other things:
> > https://github.com/bazelbuild/rules_rust/blob/75c63c36ab6a268d4de773437400d1d853723e84/rust/private/rustc.bzl#L396-L413
> 
> Yeah, It seems simple enough to expose `CARGO_MANIFEST_DIR` to the action but what is the value of it? What would represent the manifest dir? Seems like it'd be something on `CrateInfo` but I'm not sure what.

Up until now, we've been treating the directory containing the BUILD file as the CARGO_MANIFEST_DIR equivalent, which seems the closest analogue we have.

**Comment by dae** [comment]
> The issue is that Cargo and Bazel behave differently for those strings and it's valuable to me to support both (makes transitioning easy or even possible in some of my cases).

Hmm, that hasn't been my experience - I use both Cargo and Bazel as well, and things like https://github.com/ankitects/anki/blob/ca0374782e709b6877162328945b55181cdb2445/rslib/src/storage/config/mod.rs#L16 work for me in both. I wonder what is different?

**Comment by briansmith** [comment]
> For normal binaries/libs/tests, include_str!() references are relative to the file they fall in, so foo/bar.rs can reference baz/quux.txt with include_str!("../baz/quux.txt"). Is the doc code behaving differently?

`include_str!` might work, but consider a doctest that does `fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/data/whatever.txt")))`. Note that one cannot make assumptions about the current working directory in a doctest and also these variables aren't guaranteed to be set at runtime, only at compile-time, by Cargo's rules at https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates. 

FWIW, my goal is to have the same source code work, unmodified, both when building with Cargo and when building with rules_rust. (In my case, I'm trying to migrate a Cargo-based build system to Bazel incrementally.)

**Comment by hlopko** [comment]
> > For normal binaries/libs/tests, include_str!() references are relative to the file they fall in, so foo/bar.rs can reference baz/quux.txt with include_str!("../baz/quux.txt"). Is the doc code behaving differently?
> 
> `include_str!` might work, but consider a doctest that does `fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/data/whatever.txt")))`. Note that one cannot make assumptions about the current working directory in a doctest and also these variables aren't guaranteed to be set at runtime, only at compile-time, by Cargo's rules at [doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates).
> 
> FWIW, my goal is to have the same source code work, unmodified, both when building with Cargo and when building with rules_rust. (In my case, I'm trying to migrate a Cargo-based build system to Bazel incrementally.)

Have the cargo docs changes? Or is it just me reading "Cargo exposes these environment variables to your crate when it is compiled. Note that this applies for running binaries with cargo run and cargo test as well. " as "you can rely on these variables be set at runtime"?

**Comment by briansmith** [comment]
> > `include_str!` might work, but consider a doctest that does `fs::read_to_string(concat!(env!("CARGO_MANIFEST_DIR"), "/data/whatever.txt")))`. 

[snip]

> Have the cargo docs changes? Or is it just me reading "Cargo exposes these environment variables to your crate when it is compiled. Note that this applies for running binaries with cargo run and cargo test as well. " as "you can rely on these variables be set at runtime"?

In my example above, `concat!(env!("CARGO_MANIFEST_DIR"), "/data/whatever.txt"))` is resolved at compile time to a constant string. `fs::read_to_string(THAT_CONSTANT)` is executed at runtime. In other words, the tests I'm trying to get working need `CARGO_MANIFEST_DIR` to be set *at compile time* to the path that will succeed at finding the files *at runtime*.

**Comment by UebelAndre** [comment]
side note: I think I'm realizing I closed this with open questions still on it. Could someone make a new issue if there is to help triage it? No need to stop conversation here but I'd love to know clearly what's broken so it can get fixed 😄
