### ISSUE TITLE
Integrate with RLS

### ISSUE THREAD

**Issue by damienmg** [bazelbuild/rules_rust#95]
I am working with VSCode and while it is super nice with Rust & Cargo, RLS bugs out with Bazel. I am actually contemplating shaving that yak further and modifying RLS and VSCode RLS to support generic build system but I have resisted the temptation so far so I am creating a bug here so it doesn't get lost.

Might be a workaround to use https://github.com/bazelbuild/rules_rust/issues/71.

**Comment by mfarrugi** [comment]
If there's not a way better than #71, I am happy to polish it up.

I've been using intellij-rust and don't think it's worth trying to fix all
of the things downstream of Cargo.toml`s

**Comment by damienmg** [comment]
#71 would only provide a workaround by generated a file, you would still need to generate that file or use ibazel to do so... Maybe #71 and ibazel would be good enough though. I should try it ;)

**Comment by damienmg** [comment]
Ok so I think #71 and bazel-watcher is going to make an acceptable solution. Not as nice as getting RLS to understand other build system (although seeing RLS code, that shouldn't be too hard) but it seems to be the more straightforward version. I'll leave some more comment about the prototype on #71.

**Comment by damienmg** [comment]
I digged a bit more in RLS source code and they basically runs cargo to get the list of rustc call it perform (see https://github.com/rust-lang-nursery/rls/blob/master/src/build/cargo.rs#L332). This should be quite easy to adapt to Bazel except that the current rust files create a symlink tree that is not exposed. This could be done by simply moving the setup_cmd in a separate command that would output a directory artifact. So the rustc execution would all be a single command.

I actually don't follow why we need to do all that set-up, why can't we point rustc to the deps directly? I reviewed that original code but I was knowing nothing of rust at that time.

**Comment by damienmg** [comment]
Ok there is one reason we might want to put all deps in one dir is to avoid explosion in the command line size but there is a standard way to fix that is by using params file. It seems like rustc does not support it at the moment but I am pretty sure it wouldn't be hard to upstream that.

**Comment by damienmg** [comment]
I'll probably tackle this during my next flight (this week).

My current plan is to use `bazel aquary` to generate a build plan and pass it to RLS. RLS support getting a JSON build plan (see `cargo build --build-plan`) from a custom command (specified as part of RLS config here: https://github.com/rust-lang-nursery/rls/blob/master/src/config.rs#L165).

**Comment by mfarrugi** [comment]
@damienmg why is this approach preferable to generating the `Cargo.toml`? If we do that, we should be able to have cargo run the RLS under a bazel workspace as well.

**Comment by beefsack** [comment]
Perhaps integrating with [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) would be easier at the moment. rust-analyzer is part of a larger rls-2.0 effort and already has some [build system agnostic functionality](https://github.com/rust-analyzer/rust-analyzer/pull/939).

**Comment by dayfine** [comment]
So what's the recommended way now to have RLS in VSCode works with Bazel?

**Comment by purkhusid** [comment]
Anybody got anything that works OK?

**Comment by mpereira** [comment]
I'm interested as well.

**Comment by m3rcuriel** [comment]
I was thinking about messing around with aspects to generate the config that rust-analyzer expects. I know some compilation database setups _really_ emphasize not having to do a rebuild but I think that makes the most sense.

**Comment by mfarrugi** [comment]
What do you mean about avoiding a rebuild? The aspect running would re-do a minimal portion of loading the build graph, and should cache very well. If you really wanted to, you could generate the Cargo.toml and whatever other metadata as part of the various crate rules themselves.

**Comment by UebelAndre** [comment]
Is this still necessary after https://github.com/bazelbuild/rules_rust/pull/505?

I thought RLS was being replaced by rust_analyzer

**Comment by beefsack** [comment]
I believe the plan is for [rust-analyzer to essentially become RLS 2.0](https://rust-lang.github.io/compiler-team/working-groups/rls-2.0/). rust-analyzer is already in a better spot than the original RLS, generally it is recommended over the original RLS.

**Comment by UebelAndre** [comment]
I'm gonna close this for now. Happy to reopen it if someone feels there's still value in doing this.
