### ISSUE TITLE
Performance of rust_analyzer

### ISSUE THREAD

**Issue by purkhusid** [bazelbuild/rules_rust#962]
The performance for the rust_analyzer rule is not that great when you have a lot of targets included in the `targets` list.

The issue seems to compound if you have a deep hierarchy where there are a lot of duplicate dependencies and there are a lot of dependencies between targets.

Unfortunately I can't share a reproduction since the repository is proprietary but here is a profile of a `bazel build //:rust_analyzer`:

![image](https://user-images.githubusercontent.com/5622403/135894312-b615ac60-3339-4d69-a9f7-a0365b4b2cee.png)

**Comment by purkhusid** [comment]
The issue is very likely with this here for loop: https://github.com/bazelbuild/rules_rust/blob/238b998f108a099e5a227dbe312526406dda1f2d/rust/private/rust_analyzer.bzl#L219

**Comment by purkhusid** [comment]
If rust-analyzer can be made lazy then that would be the ideal approach IMO, this needs upstream changes in rust-analyzer though? 

I also wonder if we get more flexibility if we move into the execution phase since we might be able to have better caching during the execution, e.g. a lookup table for each crate so that we don't process them more than once.

I'm not too familiar with the internals of rust-analyzer to be of much help there but I can definitely test out any changes to the rules on our repo and see if there are improvemtents.

**Comment by hlopko** [comment]
Could you check if https://github.com/bazelbuild/rules_rust/pull/1010 made any difference in the performance?

**Comment by purkhusid** [comment]
@hlopko This seems to have improved the performance significantly, it still takes some 10s of seconds for my repo but it's not too bad compared to how it was. Thanks for following up on this!
