### ISSUE TITLE
Disabling formatting of generated bindgen code is not possible

### ISSUE THREAD

**Issue by csmulhern** [bazelbuild/rules_rust#992]
The bindgen rule falls back on the rustfmt target specified by the rust_toolchain if the rust_bindgen_toolchain has rustfmt set to None. See:
https://github.com/bazelbuild/rules_rust/blob/d974e0ea173f5b5dc0ebd56946881b24ebe23248/bindgen/bindgen.bzl#L94

If rustfmt_version is set to None when calling rust_repositories, a rust version is used instead. See:
https://github.com/bazelbuild/rules_rust/blob/d974e0ea173f5b5dc0ebd56946881b24ebe23248/rust/repositories.bzl#L77

Because of this, it's not possible to disable formatting when generating bindgen code. It would be nice to be able to disable this for performance reasons.

It seems like the project should either:
1) Not try to intelligently fallback on the rustfmt of the rust toolchain if the rust bindgen toolchain rustfmt target is None in _rust_bindgen_impl (my recommendation).
2) Allow rustfmt to be unset on the rust toolchain itself (I'm not sure of the implications of this, but I'm not sure why it would be required).

**Comment by djmarcin** [comment]
This is particularly problematic when the nightly version of rustfmt is broken. Right now, the output of the nightly rustfmt on my generated code is an empty file.
